<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            [ 'id' => 1, 'state_id' => 1, 'city'=> 'Maroa', 'capital' => 0 ],
            [ 'id' => 2, 'state_id' => 1, 'city'=> 'Puerto Ayacucho', 'capital' => 1 ],
            [ 'id' => 3, 'state_id' => 1, 'city'=> 'San Fernando de Atabapo', 'capital' => 0 ],
            [ 'id' => 4, 'state_id' => 2, 'city'=> 'Anaco', 'capital' => 0 ],
            [ 'id' => 5, 'state_id' => 2, 'city'=> 'Aragua de Barcelona', 'capital' => 0 ],
            [ 'id' => 6, 'state_id' => 2, 'city'=> 'Barcelona', 'capital' => 1 ],
            [ 'id' => 7, 'state_id' => 2, 'city'=> 'Boca de Uchire', 'capital' => 0 ],
            [ 'id' => 8, 'state_id' => 2, 'city'=> 'Cantaura', 'capital' => 0 ],
            [ 'id' => 9, 'state_id' => 2, 'city'=> 'Clarines', 'capital' => 0 ],
            [ 'id' => 10, 'state_id' => 2, 'city'=> 'El Chaparro', 'capital' => 0 ],
            [ 'id' => 11, 'state_id' => 2, 'city'=> 'El Pao Anzoátegui', 'capital' => 0 ],
            [ 'id' => 12, 'state_id' => 2, 'city'=> 'El Tigre', 'capital' => 0 ],
            [ 'id' => 13, 'state_id' => 2, 'city'=> 'El Tigrito', 'capital' => 0 ],
            [ 'id' => 14, 'state_id' => 2, 'city'=> 'Guanape', 'capital' => 0 ],
            [ 'id' => 15, 'state_id' => 2, 'city'=> 'Guanta', 'capital' => 0 ],
            [ 'id' => 16, 'state_id' => 2, 'city'=> 'Lechería', 'capital' => 0 ],
            [ 'id' => 17, 'state_id' => 2, 'city'=> 'Onoto', 'capital' => 0 ],
            [ 'id' => 18, 'state_id' => 2, 'city'=> 'Pariaguán', 'capital' => 0 ],
            [ 'id' => 19, 'state_id' => 2, 'city'=> 'Píritu', 'capital' => 0 ],
            [ 'id' => 20, 'state_id' => 2, 'city'=> 'Puerto La Cruz', 'capital' => 0 ],
            [ 'id' => 21, 'state_id' => 2, 'city'=> 'Puerto Píritu', 'capital' => 0 ],
            [ 'id' => 22, 'state_id' => 2, 'city'=> 'Sabana de Uchire', 'capital' => 0 ],
            [ 'id' => 23, 'state_id' => 2, 'city'=> 'San Mateo Anzoátegui', 'capital' => 0 ],
            [ 'id' => 24, 'state_id' => 2, 'city'=> 'San Pablo Anzoátegui', 'capital' => 0 ],
            [ 'id' => 25, 'state_id' => 2, 'city'=> 'San Tomé', 'capital' => 0 ],
            [ 'id' => 26, 'state_id' => 2, 'city'=> 'Santa Ana de Anzoátegui', 'capital' => 0 ],
            [ 'id' => 27, 'state_id' => 2, 'city'=> 'Santa Fe Anzoátegui', 'capital' => 0 ],
            [ 'id' => 28, 'state_id' => 2, 'city'=> 'Santa Rosa', 'capital' => 0 ],
            [ 'id' => 29, 'state_id' => 2, 'city'=> 'Soledad', 'capital' => 0 ],
            [ 'id' => 30, 'state_id' => 2, 'city'=> 'Urica', 'capital' => 0 ],
            [ 'id' => 31, 'state_id' => 2, 'city'=> 'Valle de Guanape', 'capital' => 0 ],
            [ 'id' => 43, 'state_id' => 3, 'city'=> 'Achaguas', 'capital' => 0 ],
            [ 'id' => 44, 'state_id' => 3, 'city'=> 'Biruaca', 'capital' => 0 ],
            [ 'id' => 45, 'state_id' => 3, 'city'=> 'Bruzual', 'capital' => 0 ],
            [ 'id' => 46, 'state_id' => 3, 'city'=> 'El Amparo', 'capital' => 0 ],
            [ 'id' => 47, 'state_id' => 3, 'city'=> 'El Nula', 'capital' => 0 ],
            [ 'id' => 48, 'state_id' => 3, 'city'=> 'Elorza', 'capital' => 0 ],
            [ 'id' => 49, 'state_id' => 3, 'city'=> 'Guasdualito', 'capital' => 0 ],
            [ 'id' => 50, 'state_id' => 3, 'city'=> 'Mantecal', 'capital' => 0 ],
            [ 'id' => 51, 'state_id' => 3, 'city'=> 'Puerto Páez', 'capital' => 0 ],
            [ 'id' => 52, 'state_id' => 3, 'city'=> 'San Fernando de Apure', 'capital' => 1 ],
            [ 'id' => 53, 'state_id' => 3, 'city'=> 'San Juan de Payara', 'capital' => 0 ],
            [ 'id' => 54, 'state_id' => 4, 'city'=> 'Barbacoas', 'capital' => 0 ],
            [ 'id' => 55, 'state_id' => 4, 'city'=> 'Cagua', 'capital' => 0 ],
            [ 'id' => 56, 'state_id' => 4, 'city'=> 'Camatagua', 'capital' => 0 ],
            [ 'id' => 58, 'state_id' => 4, 'city'=> 'Choroní', 'capital' => 0 ],
            [ 'id' => 59, 'state_id' => 4, 'city'=> 'Colonia Tovar', 'capital' => 0 ],
            [ 'id' => 60, 'state_id' => 4, 'city'=> 'El Consejo', 'capital' => 0 ],
            [ 'id' => 61, 'state_id' => 4, 'city'=> 'La Victoria', 'capital' => 0 ],
            [ 'id' => 62, 'state_id' => 4, 'city'=> 'Las Tejerías', 'capital' => 0 ],
            [ 'id' => 63, 'state_id' => 4, 'city'=> 'Magdaleno', 'capital' => 0 ],
            [ 'id' => 64, 'state_id' => 4, 'city'=> 'Maracay', 'capital' => 1 ],
            [ 'id' => 65, 'state_id' => 4, 'city'=> 'Ocumare de La Costa', 'capital' => 0 ],
            [ 'id' => 66, 'state_id' => 4, 'city'=> 'Palo Negro', 'capital' => 0 ],
            [ 'id' => 67, 'state_id' => 4, 'city'=> 'San Casimiro', 'capital' => 0 ],
            [ 'id' => 68, 'state_id' => 4, 'city'=> 'San Mateo', 'capital' => 0 ],
            [ 'id' => 69, 'state_id' => 4, 'city'=> 'San Sebastián', 'capital' => 0 ],
            [ 'id' => 70, 'state_id' => 4, 'city'=> 'Santa Cruz de Aragua', 'capital' => 0 ],
            [ 'id' => 71, 'state_id' => 4, 'city'=> 'Tocorón', 'capital' => 0 ],
            [ 'id' => 72, 'state_id' => 4, 'city'=> 'Turmero', 'capital' => 0 ],
            [ 'id' => 73, 'state_id' => 4, 'city'=> 'Villa de Cura', 'capital' => 0 ],
            [ 'id' => 74, 'state_id' => 4, 'city'=> 'Zuata', 'capital' => 0 ],
            [ 'id' => 75, 'state_id' => 5, 'city'=> 'Barinas', 'capital' => 1 ],
            [ 'id' => 76, 'state_id' => 5, 'city'=> 'Barinitas', 'capital' => 0 ],
            [ 'id' => 77, 'state_id' => 5, 'city'=> 'Barrancas', 'capital' => 0 ],
            [ 'id' => 78, 'state_id' => 5, 'city'=> 'Calderas', 'capital' => 0 ],
            [ 'id' => 79, 'state_id' => 5, 'city'=> 'Capitanejo', 'capital' => 0 ],
            [ 'id' => 80, 'state_id' => 5, 'city'=> 'Ciudad Bolivia', 'capital' => 0 ],
            [ 'id' => 81, 'state_id' => 5, 'city'=> 'El Cantón', 'capital' => 0 ],
            [ 'id' => 82, 'state_id' => 5, 'city'=> 'Las Veguitas', 'capital' => 0 ],
            [ 'id' => 83, 'state_id' => 5, 'city'=> 'Libertad de Barinas', 'capital' => 0 ],
            [ 'id' => 84, 'state_id' => 5, 'city'=> 'Sabaneta', 'capital' => 0 ],
            [ 'id' => 85, 'state_id' => 5, 'city'=> 'Santa Bárbara de Barinas', 'capital' => 0 ],
            [ 'id' => 86, 'state_id' => 5, 'city'=> 'Socopó', 'capital' => 0 ],
            [ 'id' => 87, 'state_id' => 6, 'city'=> 'Caicara del Orinoco', 'capital' => 0 ],
            [ 'id' => 88, 'state_id' => 6, 'city'=> 'Canaima', 'capital' => 0 ],
            [ 'id' => 89, 'state_id' => 6, 'city'=> 'Ciudad Bolívar', 'capital' => 1 ],
            [ 'id' => 90, 'state_id' => 6, 'city'=> 'Ciudad Piar', 'capital' => 0 ],
            [ 'id' => 91, 'state_id' => 6, 'city'=> 'El Callao', 'capital' => 0 ],
            [ 'id' => 92, 'state_id' => 6, 'city'=> 'El Dorado', 'capital' => 0 ],
            [ 'id' => 93, 'state_id' => 6, 'city'=> 'El Manteco', 'capital' => 0 ],
            [ 'id' => 94, 'state_id' => 6, 'city'=> 'El Palmar', 'capital' => 0 ],
            [ 'id' => 95, 'state_id' => 6, 'city'=> 'El Pao', 'capital' => 0 ],
            [ 'id' => 96, 'state_id' => 6, 'city'=> 'Guasipati', 'capital' => 0 ],
            [ 'id' => 97, 'state_id' => 6, 'city'=> 'Guri', 'capital' => 0 ],
            [ 'id' => 98, 'state_id' => 6, 'city'=> 'La Paragua', 'capital' => 0 ],
            [ 'id' => 99, 'state_id' => 6, 'city'=> 'Matanzas', 'capital' => 0 ],
            [ 'id' => 100, 'state_id' => 6, 'city'=> 'Puerto Ordaz', 'capital' => 0 ],
            [ 'id' => 101, 'state_id' => 6, 'city'=> 'San Félix', 'capital' => 0 ],
            [ 'id' => 102, 'state_id' => 6, 'city'=> 'Santa Elena de Uairén', 'capital' => 0 ],
            [ 'id' => 103, 'state_id' => 6, 'city'=> 'Tumeremo', 'capital' => 0 ],
            [ 'id' => 104, 'state_id' => 6, 'city'=> 'Unare', 'capital' => 0 ],
            [ 'id' => 105, 'state_id' => 6, 'city'=> 'Upata', 'capital' => 0 ],
            [ 'id' => 106, 'state_id' => 7, 'city'=> 'Bejuma', 'capital' => 0 ],
            [ 'id' => 107, 'state_id' => 7, 'city'=> 'Belén', 'capital' => 0 ],
            [ 'id' => 108, 'state_id' => 7, 'city'=> 'Campo de Carabobo', 'capital' => 0 ],
            [ 'id' => 109, 'state_id' => 7, 'city'=> 'Canoabo', 'capital' => 0 ],
            [ 'id' => 110, 'state_id' => 7, 'city'=> 'Central Tacarigua', 'capital' => 0 ],
            [ 'id' => 111, 'state_id' => 7, 'city'=> 'Chirgua', 'capital' => 0 ],
            [ 'id' => 112, 'state_id' => 7, 'city'=> 'Ciudad Alianza', 'capital' => 0 ],
            [ 'id' => 113, 'state_id' => 7, 'city'=> 'El Palito', 'capital' => 0 ],
            [ 'id' => 114, 'state_id' => 7, 'city'=> 'Guacara', 'capital' => 0 ],
            [ 'id' => 115, 'state_id' => 7, 'city'=> 'Guigue', 'capital' => 0 ],
            [ 'id' => 116, 'state_id' => 7, 'city'=> 'Las Trincheras', 'capital' => 0 ],
            [ 'id' => 117, 'state_id' => 7, 'city'=> 'Los Guayos', 'capital' => 0 ],
            [ 'id' => 118, 'state_id' => 7, 'city'=> 'Mariara', 'capital' => 0 ],
            [ 'id' => 119, 'state_id' => 7, 'city'=> 'Miranda', 'capital' => 0 ],
            [ 'id' => 120, 'state_id' => 7, 'city'=> 'Montalbán', 'capital' => 0 ],
            [ 'id' => 121, 'state_id' => 7, 'city'=> 'Morón', 'capital' => 0 ],
            [ 'id' => 122, 'state_id' => 7, 'city'=> 'Naguanagua', 'capital' => 0 ],
            [ 'id' => 123, 'state_id' => 7, 'city'=> 'Puerto Cabello', 'capital' => 0 ],
            [ 'id' => 124, 'state_id' => 7, 'city'=> 'San Joaquín', 'capital' => 0 ],
            [ 'id' => 125, 'state_id' => 7, 'city'=> 'Tocuyito', 'capital' => 0 ],
            [ 'id' => 126, 'state_id' => 7, 'city'=> 'Urama', 'capital' => 0 ],
            [ 'id' => 127, 'state_id' => 7, 'city'=> 'Valencia', 'capital' => 1 ],
            [ 'id' => 128, 'state_id' => 7, 'city'=> 'Vigirimita', 'capital' => 0 ],
            [ 'id' => 129, 'state_id' => 8, 'city'=> 'Aguirre', 'capital' => 0 ],
            [ 'id' => 130, 'state_id' => 8, 'city'=> 'Apartaderos Cojedes', 'capital' => 0 ],
            [ 'id' => 131, 'state_id' => 8, 'city'=> 'Arismendi', 'capital' => 0 ],
            [ 'id' => 132, 'state_id' => 8, 'city'=> 'Camuriquito', 'capital' => 0 ],
            [ 'id' => 133, 'state_id' => 8, 'city'=> 'El Baúl', 'capital' => 0 ],
            [ 'id' => 134, 'state_id' => 8, 'city'=> 'El Limón', 'capital' => 0 ],
            [ 'id' => 135, 'state_id' => 8, 'city'=> 'El Pao Cojedes', 'capital' => 0 ],
            [ 'id' => 136, 'state_id' => 8, 'city'=> 'El Socorro', 'capital' => 0 ],
            [ 'id' => 137, 'state_id' => 8, 'city'=> 'La Aguadita', 'capital' => 0 ],
            [ 'id' => 138, 'state_id' => 8, 'city'=> 'Las Vegas', 'capital' => 0 ],
            [ 'id' => 139, 'state_id' => 8, 'city'=> 'Libertad de Cojedes', 'capital' => 0 ],
            [ 'id' => 140, 'state_id' => 8, 'city'=> 'Mapuey', 'capital' => 0 ],
            [ 'id' => 141, 'state_id' => 8, 'city'=> 'Piñedo', 'capital' => 0 ],
            [ 'id' => 142, 'state_id' => 8, 'city'=> 'Samancito', 'capital' => 0 ],
            [ 'id' => 143, 'state_id' => 8, 'city'=> 'San Carlos', 'capital' => 1 ],
            [ 'id' => 144, 'state_id' => 8, 'city'=> 'Sucre', 'capital' => 0 ],
            [ 'id' => 145, 'state_id' => 8, 'city'=> 'Tinaco', 'capital' => 0 ],
            [ 'id' => 146, 'state_id' => 8, 'city'=> 'Tinaquillo', 'capital' => 0 ],
            [ 'id' => 147, 'state_id' => 8, 'city'=> 'Vallecito', 'capital' => 0 ],
            [ 'id' => 148, 'state_id' => 9, 'city'=> 'Tucupita', 'capital' => 1 ],
            [ 'id' => 149, 'state_id' => 24, 'city'=> 'Caracas', 'capital' => 1 ],
            [ 'id' => 150, 'state_id' => 24, 'city'=> 'El Junquito', 'capital' => 0 ],
            [ 'id' => 151, 'state_id' => 10, 'city'=> 'Adícora', 'capital' => 0 ],
            [ 'id' => 152, 'state_id' => 10, 'city'=> 'Boca de Aroa', 'capital' => 0 ],
            [ 'id' => 153, 'state_id' => 10, 'city'=> 'Cabure', 'capital' => 0 ],
            [ 'id' => 154, 'state_id' => 10, 'city'=> 'Capadare', 'capital' => 0 ],
            [ 'id' => 155, 'state_id' => 10, 'city'=> 'Capatárida', 'capital' => 0 ],
            [ 'id' => 156, 'state_id' => 10, 'city'=> 'Chichiriviche', 'capital' => 0 ],
            [ 'id' => 157, 'state_id' => 10, 'city'=> 'Churuguara', 'capital' => 0 ],
            [ 'id' => 158, 'state_id' => 10, 'city'=> 'Coro', 'capital' => 1 ],
            [ 'id' => 159, 'state_id' => 10, 'city'=> 'Cumarebo', 'capital' => 0 ],
            [ 'id' => 160, 'state_id' => 10, 'city'=> 'Dabajuro', 'capital' => 0 ],
            [ 'id' => 161, 'state_id' => 10, 'city'=> 'Judibana', 'capital' => 0 ],
            [ 'id' => 162, 'state_id' => 10, 'city'=> 'La Cruz de Taratara', 'capital' => 0 ],
            [ 'id' => 163, 'state_id' => 10, 'city'=> 'La Vela de Coro', 'capital' => 0 ],
            [ 'id' => 164, 'state_id' => 10, 'city'=> 'Los Taques', 'capital' => 0 ],
            [ 'id' => 165, 'state_id' => 10, 'city'=> 'Maparari', 'capital' => 0 ],
            [ 'id' => 166, 'state_id' => 10, 'city'=> 'Mene de Mauroa', 'capital' => 0 ],
            [ 'id' => 167, 'state_id' => 10, 'city'=> 'Mirimire', 'capital' => 0 ],
            [ 'id' => 168, 'state_id' => 10, 'city'=> 'Pedregal', 'capital' => 0 ],
            [ 'id' => 169, 'state_id' => 10, 'city'=> 'Píritu Falcón', 'capital' => 0 ],
            [ 'id' => 170, 'state_id' => 10, 'city'=> 'Pueblo Nuevo Falcón', 'capital' => 0 ],
            [ 'id' => 171, 'state_id' => 10, 'city'=> 'Puerto Cumarebo', 'capital' => 0 ],
            [ 'id' => 172, 'state_id' => 10, 'city'=> 'Punta Cardón', 'capital' => 0 ],
            [ 'id' => 173, 'state_id' => 10, 'city'=> 'Punto Fijo', 'capital' => 0 ],
            [ 'id' => 174, 'state_id' => 10, 'city'=> 'San Juan de Los Cayos', 'capital' => 0 ],
            [ 'id' => 175, 'state_id' => 10, 'city'=> 'San Luis', 'capital' => 0 ],
            [ 'id' => 176, 'state_id' => 10, 'city'=> 'Santa Ana Falcón', 'capital' => 0 ],
            [ 'id' => 177, 'state_id' => 10, 'city'=> 'Santa Cruz De Bucaral', 'capital' => 0 ],
            [ 'id' => 178, 'state_id' => 10, 'city'=> 'Tocopero', 'capital' => 0 ],
            [ 'id' => 179, 'state_id' => 10, 'city'=> 'Tocuyo de La Costa', 'capital' => 0 ],
            [ 'id' => 180, 'state_id' => 10, 'city'=> 'Tucacas', 'capital' => 0 ],
            [ 'id' => 181, 'state_id' => 10, 'city'=> 'Yaracal', 'capital' => 0 ],
            [ 'id' => 182, 'state_id' => 11, 'city'=> 'Altagracia de Orituco', 'capital' => 0 ],
            [ 'id' => 183, 'state_id' => 11, 'city'=> 'Cabruta', 'capital' => 0 ],
            [ 'id' => 184, 'state_id' => 11, 'city'=> 'Calabozo', 'capital' => 0 ],
            [ 'id' => 185, 'state_id' => 11, 'city'=> 'Camaguán', 'capital' => 0 ],
            [ 'id' => 196, 'state_id' => 11, 'city'=> 'Chaguaramas Guárico', 'capital' => 0 ],
            [ 'id' => 197, 'state_id' => 11, 'city'=> 'El Socorro', 'capital' => 0 ],
            [ 'id' => 198, 'state_id' => 11, 'city'=> 'El Sombrero', 'capital' => 0 ],
            [ 'id' => 199, 'state_id' => 11, 'city'=> 'Las Mercedes de Los Llanos', 'capital' => 0 ],
            [ 'id' => 200, 'state_id' => 11, 'city'=> 'Lezama', 'capital' => 0 ],
            [ 'id' => 201, 'state_id' => 11, 'city'=> 'Onoto', 'capital' => 0 ],
            [ 'id' => 202, 'state_id' => 11, 'city'=> 'Ortíz', 'capital' => 0 ],
            [ 'id' => 203, 'state_id' => 11, 'city'=> 'San José de Guaribe', 'capital' => 0 ],
            [ 'id' => 204, 'state_id' => 11, 'city'=> 'San Juan de Los Morros', 'capital' => 1 ],
            [ 'id' => 205, 'state_id' => 11, 'city'=> 'San Rafael de Laya', 'capital' => 0 ],
            [ 'id' => 206, 'state_id' => 11, 'city'=> 'Santa María de Ipire', 'capital' => 0 ],
            [ 'id' => 207, 'state_id' => 11, 'city'=> 'Tucupido', 'capital' => 0 ],
            [ 'id' => 208, 'state_id' => 11, 'city'=> 'Valle de La Pascua', 'capital' => 0 ],
            [ 'id' => 209, 'state_id' => 11, 'city'=> 'Zaraza', 'capital' => 0 ],
            [ 'id' => 210, 'state_id' => 12, 'city'=> 'Aguada Grande', 'capital' => 0 ],
            [ 'id' => 211, 'state_id' => 12, 'city'=> 'Atarigua', 'capital' => 0 ],
            [ 'id' => 212, 'state_id' => 12, 'city'=> 'Barquisimeto', 'capital' => 1 ],
            [ 'id' => 213, 'state_id' => 12, 'city'=> 'Bobare', 'capital' => 0 ],
            [ 'id' => 214, 'state_id' => 12, 'city'=> 'Cabudare', 'capital' => 0 ],
            [ 'id' => 215, 'state_id' => 12, 'city'=> 'Carora', 'capital' => 0 ],
            [ 'id' => 216, 'state_id' => 12, 'city'=> 'Cubiro', 'capital' => 0 ],
            [ 'id' => 217, 'state_id' => 12, 'city'=> 'Cují', 'capital' => 0 ],
            [ 'id' => 218, 'state_id' => 12, 'city'=> 'Duaca', 'capital' => 0 ],
            [ 'id' => 219, 'state_id' => 12, 'city'=> 'El Manzano', 'capital' => 0 ],
            [ 'id' => 220, 'state_id' => 12, 'city'=> 'El Tocuyo', 'capital' => 0 ],
            [ 'id' => 221, 'state_id' => 12, 'city'=> 'Guaríco', 'capital' => 0 ],
            [ 'id' => 222, 'state_id' => 12, 'city'=> 'Humocaro Alto', 'capital' => 0 ],
            [ 'id' => 223, 'state_id' => 12, 'city'=> 'Humocaro Bajo', 'capital' => 0 ],
            [ 'id' => 224, 'state_id' => 12, 'city'=> 'La Miel', 'capital' => 0 ],
            [ 'id' => 225, 'state_id' => 12, 'city'=> 'Moroturo', 'capital' => 0 ],
            [ 'id' => 226, 'state_id' => 12, 'city'=> 'Quíbor', 'capital' => 0 ],
            [ 'id' => 227, 'state_id' => 12, 'city'=> 'Río Claro', 'capital' => 0 ],
            [ 'id' => 228, 'state_id' => 12, 'city'=> 'Sanare', 'capital' => 0 ],
            [ 'id' => 229, 'state_id' => 12, 'city'=> 'Santa Inés', 'capital' => 0 ],
            [ 'id' => 230, 'state_id' => 12, 'city'=> 'Sarare', 'capital' => 0 ],
            [ 'id' => 231, 'state_id' => 12, 'city'=> 'Siquisique', 'capital' => 0 ],
            [ 'id' => 232, 'state_id' => 12, 'city'=> 'Tintorero', 'capital' => 0 ],
            [ 'id' => 233, 'state_id' => 13, 'city'=> 'Apartaderos Mérida', 'capital' => 0 ],
            [ 'id' => 234, 'state_id' => 13, 'city'=> 'Arapuey', 'capital' => 0 ],
            [ 'id' => 235, 'state_id' => 13, 'city'=> 'Bailadores', 'capital' => 0 ],
            [ 'id' => 236, 'state_id' => 13, 'city'=> 'Caja Seca', 'capital' => 0 ],
            [ 'id' => 237, 'state_id' => 13, 'city'=> 'Canaguá', 'capital' => 0 ],
            [ 'id' => 238, 'state_id' => 13, 'city'=> 'Chachopo', 'capital' => 0 ],
            [ 'id' => 239, 'state_id' => 13, 'city'=> 'Chiguara', 'capital' => 0 ],
            [ 'id' => 240, 'state_id' => 13, 'city'=> 'Ejido', 'capital' => 0 ],
            [ 'id' => 241, 'state_id' => 13, 'city'=> 'El Vigía', 'capital' => 0 ],
            [ 'id' => 242, 'state_id' => 13, 'city'=> 'La Azulita', 'capital' => 0 ],
            [ 'id' => 243, 'state_id' => 13, 'city'=> 'La Playa', 'capital' => 0 ],
            [ 'id' => 244, 'state_id' => 13, 'city'=> 'Lagunillas Mérida', 'capital' => 0 ],
            [ 'id' => 245, 'state_id' => 13, 'city'=> 'Mérida', 'capital' => 1 ],
            [ 'id' => 246, 'state_id' => 13, 'city'=> 'Mesa de Bolívar', 'capital' => 0 ],
            [ 'id' => 247, 'state_id' => 13, 'city'=> 'Mucuchíes', 'capital' => 0 ],
            [ 'id' => 248, 'state_id' => 13, 'city'=> 'Mucujepe', 'capital' => 0 ],
            [ 'id' => 249, 'state_id' => 13, 'city'=> 'Mucuruba', 'capital' => 0 ],
            [ 'id' => 250, 'state_id' => 13, 'city'=> 'Nueva Bolivia', 'capital' => 0 ],
            [ 'id' => 251, 'state_id' => 13, 'city'=> 'Palmarito', 'capital' => 0 ],
            [ 'id' => 252, 'state_id' => 13, 'city'=> 'Pueblo Llano', 'capital' => 0 ],
            [ 'id' => 253, 'state_id' => 13, 'city'=> 'Santa Cruz de Mora', 'capital' => 0 ],
            [ 'id' => 254, 'state_id' => 13, 'city'=> 'Santa Elena de Arenales', 'capital' => 0 ],
            [ 'id' => 255, 'state_id' => 13, 'city'=> 'Santo Domingo', 'capital' => 0 ],
            [ 'id' => 256, 'state_id' => 13, 'city'=> 'Tabáy', 'capital' => 0 ],
            [ 'id' => 257, 'state_id' => 13, 'city'=> 'Timotes', 'capital' => 0 ],
            [ 'id' => 258, 'state_id' => 13, 'city'=> 'Torondoy', 'capital' => 0 ],
            [ 'id' => 259, 'state_id' => 13, 'city'=> 'Tovar', 'capital' => 0 ],
            [ 'id' => 260, 'state_id' => 13, 'city'=> 'Tucani', 'capital' => 0 ],
            [ 'id' => 261, 'state_id' => 13, 'city'=> 'Zea', 'capital' => 0 ],
            [ 'id' => 262, 'state_id' => 14, 'city'=> 'Araguita', 'capital' => 0 ],
            [ 'id' => 263, 'state_id' => 14, 'city'=> 'Carrizal', 'capital' => 0 ],
            [ 'id' => 264, 'state_id' => 14, 'city'=> 'Caucagua', 'capital' => 0 ],
            [ 'id' => 265, 'state_id' => 14, 'city'=> 'Chaguaramas Miranda', 'capital' => 0 ],
            [ 'id' => 266, 'state_id' => 14, 'city'=> 'Charallave', 'capital' => 0 ],
            [ 'id' => 267, 'state_id' => 14, 'city'=> 'Chirimena', 'capital' => 0 ],
            [ 'id' => 268, 'state_id' => 14, 'city'=> 'Chuspa', 'capital' => 0 ],
            [ 'id' => 269, 'state_id' => 14, 'city'=> 'Cúa', 'capital' => 0 ],
            [ 'id' => 270, 'state_id' => 14, 'city'=> 'Cupira', 'capital' => 0 ],
            [ 'id' => 271, 'state_id' => 14, 'city'=> 'Curiepe', 'capital' => 0 ],
            [ 'id' => 272, 'state_id' => 14, 'city'=> 'El Guapo', 'capital' => 0 ],
            [ 'id' => 273, 'state_id' => 14, 'city'=> 'El Jarillo', 'capital' => 0 ],
            [ 'id' => 274, 'state_id' => 14, 'city'=> 'Filas de Mariche', 'capital' => 0 ],
            [ 'id' => 275, 'state_id' => 14, 'city'=> 'Guarenas', 'capital' => 0 ],
            [ 'id' => 276, 'state_id' => 14, 'city'=> 'Guatire', 'capital' => 0 ],
            [ 'id' => 277, 'state_id' => 14, 'city'=> 'Higuerote', 'capital' => 0 ],
            [ 'id' => 278, 'state_id' => 14, 'city'=> 'Los Anaucos', 'capital' => 0 ],
            [ 'id' => 279, 'state_id' => 14, 'city'=> 'Los Teques', 'capital' => 1 ],
            [ 'id' => 280, 'state_id' => 14, 'city'=> 'Ocumare del Tuy', 'capital' => 0 ],
            [ 'id' => 281, 'state_id' => 14, 'city'=> 'Panaquire', 'capital' => 0 ],
            [ 'id' => 282, 'state_id' => 14, 'city'=> 'Paracotos', 'capital' => 0 ],
            [ 'id' => 283, 'state_id' => 14, 'city'=> 'Río Chico', 'capital' => 0 ],
            [ 'id' => 284, 'state_id' => 14, 'city'=> 'San Antonio de Los Altos', 'capital' => 0 ],
            [ 'id' => 285, 'state_id' => 14, 'city'=> 'San Diego de Los Altos', 'capital' => 0 ],
            [ 'id' => 286, 'state_id' => 14, 'city'=> 'San Fernando del Guapo', 'capital' => 0 ],
            [ 'id' => 287, 'state_id' => 14, 'city'=> 'San Francisco de Yare', 'capital' => 0 ],
            [ 'id' => 288, 'state_id' => 14, 'city'=> 'San José de Los Altos', 'capital' => 0 ],
            [ 'id' => 289, 'state_id' => 14, 'city'=> 'San José de Río Chico', 'capital' => 0 ],
            [ 'id' => 290, 'state_id' => 14, 'city'=> 'San Pedro de Los Altos', 'capital' => 0 ],
            [ 'id' => 291, 'state_id' => 14, 'city'=> 'Santa Lucía', 'capital' => 0 ],
            [ 'id' => 292, 'state_id' => 14, 'city'=> 'Santa Teresa', 'capital' => 0 ],
            [ 'id' => 293, 'state_id' => 14, 'city'=> 'Tacarigua de La Laguna', 'capital' => 0 ],
            [ 'id' => 294, 'state_id' => 14, 'city'=> 'Tacarigua de Mamporal', 'capital' => 0 ],
            [ 'id' => 295, 'state_id' => 14, 'city'=> 'Tácata', 'capital' => 0 ],
            [ 'id' => 296, 'state_id' => 14, 'city'=> 'Turumo', 'capital' => 0 ],
            [ 'id' => 297, 'state_id' => 15, 'city'=> 'Aguasay', 'capital' => 0 ],
            [ 'id' => 298, 'state_id' => 15, 'city'=> 'Aragua de Maturín', 'capital' => 0 ],
            [ 'id' => 299, 'state_id' => 15, 'city'=> 'Barrancas del Orinoco', 'capital' => 0 ],
            [ 'id' => 300, 'state_id' => 15, 'city'=> 'Caicara de Maturín', 'capital' => 0 ],
            [ 'id' => 301, 'state_id' => 15, 'city'=> 'Caripe', 'capital' => 0 ],
            [ 'id' => 302, 'state_id' => 15, 'city'=> 'Caripito', 'capital' => 0 ],
            [ 'id' => 303, 'state_id' => 15, 'city'=> 'Chaguaramal', 'capital' => 0 ],
            [ 'id' => 305, 'state_id' => 15, 'city'=> 'Chaguaramas Monagas', 'capital' => 0 ],
            [ 'id' => 307, 'state_id' => 15, 'city'=> 'El Furrial', 'capital' => 0 ],
            [ 'id' => 308, 'state_id' => 15, 'city'=> 'El Tejero', 'capital' => 0 ],
            [ 'id' => 309, 'state_id' => 15, 'city'=> 'Jusepín', 'capital' => 0 ],
            [ 'id' => 310, 'state_id' => 15, 'city'=> 'La Toscana', 'capital' => 0 ],
            [ 'id' => 311, 'state_id' => 15, 'city'=> 'Maturín', 'capital' => 1 ],
            [ 'id' => 312, 'state_id' => 15, 'city'=> 'Miraflores', 'capital' => 0 ],
            [ 'id' => 313, 'state_id' => 15, 'city'=> 'Punta de Mata', 'capital' => 0 ],
            [ 'id' => 314, 'state_id' => 15, 'city'=> 'Quiriquire', 'capital' => 0 ],
            [ 'id' => 315, 'state_id' => 15, 'city'=> 'San Antonio de Maturín', 'capital' => 0 ],
            [ 'id' => 316, 'state_id' => 15, 'city'=> 'San Vicente Monagas', 'capital' => 0 ],
            [ 'id' => 317, 'state_id' => 15, 'city'=> 'Santa Bárbara', 'capital' => 0 ],
            [ 'id' => 318, 'state_id' => 15, 'city'=> 'Temblador', 'capital' => 0 ],
            [ 'id' => 319, 'state_id' => 15, 'city'=> 'Teresen', 'capital' => 0 ],
            [ 'id' => 320, 'state_id' => 15, 'city'=> 'Uracoa', 'capital' => 0 ],
            [ 'id' => 321, 'state_id' => 16, 'city'=> 'Altagracia', 'capital' => 0 ],
            [ 'id' => 322, 'state_id' => 16, 'city'=> 'Boca de Pozo', 'capital' => 0 ],
            [ 'id' => 323, 'state_id' => 16, 'city'=> 'Boca de Río', 'capital' => 0 ],
            [ 'id' => 324, 'state_id' => 16, 'city'=> 'El Espinal', 'capital' => 0 ],
            [ 'id' => 325, 'state_id' => 16, 'city'=> 'El Valle del Espíritu Santo', 'capital' => 0 ],
            [ 'id' => 326, 'state_id' => 16, 'city'=> 'El Yaque', 'capital' => 0 ],
            [ 'id' => 327, 'state_id' => 16, 'city'=> 'Juangriego', 'capital' => 0 ],
            [ 'id' => 328, 'state_id' => 16, 'city'=> 'La Asunción', 'capital' => 1 ],
            [ 'id' => 329, 'state_id' => 16, 'city'=> 'La Guardia', 'capital' => 0 ],
            [ 'id' => 330, 'state_id' => 16, 'city'=> 'Pampatar', 'capital' => 0 ],
            [ 'id' => 331, 'state_id' => 16, 'city'=> 'Porlamar', 'capital' => 0 ],
            [ 'id' => 332, 'state_id' => 16, 'city'=> 'Puerto Fermín', 'capital' => 0 ],
            [ 'id' => 333, 'state_id' => 16, 'city'=> 'Punta de Piedras', 'capital' => 0 ],
            [ 'id' => 334, 'state_id' => 16, 'city'=> 'San Francisco de Macanao', 'capital' => 0 ],
            [ 'id' => 335, 'state_id' => 16, 'city'=> 'San Juan Bautista', 'capital' => 0 ],
            [ 'id' => 336, 'state_id' => 16, 'city'=> 'San Pedro de Coche', 'capital' => 0 ],
            [ 'id' => 337, 'state_id' => 16, 'city'=> 'Santa Ana de Nueva Esparta', 'capital' => 0 ],
            [ 'id' => 338, 'state_id' => 16, 'city'=> 'Villa Rosa', 'capital' => 0 ],
            [ 'id' => 339, 'state_id' => 17, 'city'=> 'Acarigua', 'capital' => 0 ],
            [ 'id' => 340, 'state_id' => 17, 'city'=> 'Agua Blanca', 'capital' => 0 ],
            [ 'id' => 341, 'state_id' => 17, 'city'=> 'Araure', 'capital' => 0 ],
            [ 'id' => 342, 'state_id' => 17, 'city'=> 'Biscucuy', 'capital' => 0 ],
            [ 'id' => 343, 'state_id' => 17, 'city'=> 'Boconoito', 'capital' => 0 ],
            [ 'id' => 344, 'state_id' => 17, 'city'=> 'Campo Elías', 'capital' => 0 ],
            [ 'id' => 345, 'state_id' => 17, 'city'=> 'Chabasquén', 'capital' => 0 ],
            [ 'id' => 346, 'state_id' => 17, 'city'=> 'Guanare', 'capital' => 1 ],
            [ 'id' => 347, 'state_id' => 17, 'city'=> 'Guanarito', 'capital' => 0 ],
            [ 'id' => 348, 'state_id' => 17, 'city'=> 'La Aparición', 'capital' => 0 ],
            [ 'id' => 349, 'state_id' => 17, 'city'=> 'La Misión', 'capital' => 0 ],
            [ 'id' => 350, 'state_id' => 17, 'city'=> 'Mesa de Cavacas', 'capital' => 0 ],
            [ 'id' => 351, 'state_id' => 17, 'city'=> 'Ospino', 'capital' => 0 ],
            [ 'id' => 352, 'state_id' => 17, 'city'=> 'Papelón', 'capital' => 0 ],
            [ 'id' => 353, 'state_id' => 17, 'city'=> 'Payara', 'capital' => 0 ],
            [ 'id' => 354, 'state_id' => 17, 'city'=> 'Pimpinela', 'capital' => 0 ],
            [ 'id' => 355, 'state_id' => 17, 'city'=> 'Píritu de Portuguesa', 'capital' => 0 ],
            [ 'id' => 356, 'state_id' => 17, 'city'=> 'San Rafael de Onoto', 'capital' => 0 ],
            [ 'id' => 357, 'state_id' => 17, 'city'=> 'Santa Rosalía', 'capital' => 0 ],
            [ 'id' => 358, 'state_id' => 17, 'city'=> 'Turén', 'capital' => 0 ],
            [ 'id' => 359, 'state_id' => 18, 'city'=> 'Altos de Sucre', 'capital' => 0 ],
            [ 'id' => 360, 'state_id' => 18, 'city'=> 'Araya', 'capital' => 0 ],
            [ 'id' => 361, 'state_id' => 18, 'city'=> 'Cariaco', 'capital' => 0 ],
            [ 'id' => 362, 'state_id' => 18, 'city'=> 'Carúpano', 'capital' => 0 ],
            [ 'id' => 363, 'state_id' => 18, 'city'=> 'Casanay', 'capital' => 0 ],
            [ 'id' => 364, 'state_id' => 18, 'city'=> 'Cumaná', 'capital' => 1 ],
            [ 'id' => 365, 'state_id' => 18, 'city'=> 'Cumanacoa', 'capital' => 0 ],
            [ 'id' => 366, 'state_id' => 18, 'city'=> 'El Morro Puerto Santo', 'capital' => 0 ],
            [ 'id' => 367, 'state_id' => 18, 'city'=> 'El Pilar', 'capital' => 0 ],
            [ 'id' => 368, 'state_id' => 18, 'city'=> 'El Poblado', 'capital' => 0 ],
            [ 'id' => 369, 'state_id' => 18, 'city'=> 'Guaca', 'capital' => 0 ],
            [ 'id' => 370, 'state_id' => 18, 'city'=> 'Guiria', 'capital' => 0 ],
            [ 'id' => 371, 'state_id' => 18, 'city'=> 'Irapa', 'capital' => 0 ],
            [ 'id' => 372, 'state_id' => 18, 'city'=> 'Manicuare', 'capital' => 0 ],
            [ 'id' => 373, 'state_id' => 18, 'city'=> 'Mariguitar', 'capital' => 0 ],
            [ 'id' => 374, 'state_id' => 18, 'city'=> 'Río Caribe', 'capital' => 0 ],
            [ 'id' => 375, 'state_id' => 18, 'city'=> 'San Antonio del Golfo', 'capital' => 0 ],
            [ 'id' => 376, 'state_id' => 18, 'city'=> 'San José de Aerocuar', 'capital' => 0 ],
            [ 'id' => 377, 'state_id' => 18, 'city'=> 'San Vicente de Sucre', 'capital' => 0 ],
            [ 'id' => 378, 'state_id' => 18, 'city'=> 'Santa Fe de Sucre', 'capital' => 0 ],
            [ 'id' => 379, 'state_id' => 18, 'city'=> 'Tunapuy', 'capital' => 0 ],
            [ 'id' => 380, 'state_id' => 18, 'city'=> 'Yaguaraparo', 'capital' => 0 ],
            [ 'id' => 381, 'state_id' => 18, 'city'=> 'Yoco', 'capital' => 0 ],
            [ 'id' => 382, 'state_id' => 19, 'city'=> 'Abejales', 'capital' => 0 ],
            [ 'id' => 383, 'state_id' => 19, 'city'=> 'Borota', 'capital' => 0 ],
            [ 'id' => 384, 'state_id' => 19, 'city'=> 'Bramon', 'capital' => 0 ],
            [ 'id' => 385, 'state_id' => 19, 'city'=> 'Capacho', 'capital' => 0 ],
            [ 'id' => 386, 'state_id' => 19, 'city'=> 'Colón', 'capital' => 0 ],
            [ 'id' => 387, 'state_id' => 19, 'city'=> 'Coloncito', 'capital' => 0 ],
            [ 'id' => 388, 'state_id' => 19, 'city'=> 'Cordero', 'capital' => 0 ],
            [ 'id' => 389, 'state_id' => 19, 'city'=> 'El Cobre', 'capital' => 0 ],
            [ 'id' => 390, 'state_id' => 19, 'city'=> 'El Pinal', 'capital' => 0 ],
            [ 'id' => 391, 'state_id' => 19, 'city'=> 'Independencia', 'capital' => 0 ],
            [ 'id' => 392, 'state_id' => 19, 'city'=> 'La Fría', 'capital' => 0 ],
            [ 'id' => 393, 'state_id' => 19, 'city'=> 'La Grita', 'capital' => 0 ],
            [ 'id' => 394, 'state_id' => 19, 'city'=> 'La Pedrera', 'capital' => 0 ],
            [ 'id' => 395, 'state_id' => 19, 'city'=> 'La Tendida', 'capital' => 0 ],
            [ 'id' => 396, 'state_id' => 19, 'city'=> 'Las Delicias', 'capital' => 0 ],
            [ 'id' => 397, 'state_id' => 19, 'city'=> 'Las Hernández', 'capital' => 0 ],
            [ 'id' => 398, 'state_id' => 19, 'city'=> 'Lobatera', 'capital' => 0 ],
            [ 'id' => 399, 'state_id' => 19, 'city'=> 'Michelena', 'capital' => 0 ],
            [ 'id' => 400, 'state_id' => 19, 'city'=> 'Palmira', 'capital' => 0 ],
            [ 'id' => 401, 'state_id' => 19, 'city'=> 'Pregonero', 'capital' => 0 ],
            [ 'id' => 402, 'state_id' => 19, 'city'=> 'Queniquea', 'capital' => 0 ],
            [ 'id' => 403, 'state_id' => 19, 'city'=> 'Rubio', 'capital' => 0 ],
            [ 'id' => 404, 'state_id' => 19, 'city'=> 'San Antonio del Tachira', 'capital' => 0 ],
            [ 'id' => 405, 'state_id' => 19, 'city'=> 'San Cristobal', 'capital' => 1 ],
            [ 'id' => 406, 'state_id' => 19, 'city'=> 'San José de Bolívar', 'capital' => 0 ],
            [ 'id' => 407, 'state_id' => 19, 'city'=> 'San Josecito', 'capital' => 0 ],
            [ 'id' => 408, 'state_id' => 19, 'city'=> 'San Pedro del Río', 'capital' => 0 ],
            [ 'id' => 409, 'state_id' => 19, 'city'=> 'Santa Ana Táchira', 'capital' => 0 ],
            [ 'id' => 410, 'state_id' => 19, 'city'=> 'Seboruco', 'capital' => 0 ],
            [ 'id' => 411, 'state_id' => 19, 'city'=> 'Táriba', 'capital' => 0 ],
            [ 'id' => 412, 'state_id' => 19, 'city'=> 'Umuquena', 'capital' => 0 ],
            [ 'id' => 413, 'state_id' => 19, 'city'=> 'Ureña', 'capital' => 0 ],
            [ 'id' => 414, 'state_id' => 20, 'city'=> 'Batatal', 'capital' => 0 ],
            [ 'id' => 415, 'state_id' => 20, 'city'=> 'Betijoque', 'capital' => 0 ],
            [ 'id' => 416, 'state_id' => 20, 'city'=> 'Boconó', 'capital' => 0 ],
            [ 'id' => 417, 'state_id' => 20, 'city'=> 'Carache', 'capital' => 0 ],
            [ 'id' => 418, 'state_id' => 20, 'city'=> 'Chejende', 'capital' => 0 ],
            [ 'id' => 419, 'state_id' => 20, 'city'=> 'Cuicas', 'capital' => 0 ],
            [ 'id' => 420, 'state_id' => 20, 'city'=> 'El Dividive', 'capital' => 0 ],
            [ 'id' => 421, 'state_id' => 20, 'city'=> 'El Jaguito', 'capital' => 0 ],
            [ 'id' => 422, 'state_id' => 20, 'city'=> 'Escuque', 'capital' => 0 ],
            [ 'id' => 423, 'state_id' => 20, 'city'=> 'Isnotú', 'capital' => 0 ],
            [ 'id' => 424, 'state_id' => 20, 'city'=> 'Jajó', 'capital' => 0 ],
            [ 'id' => 425, 'state_id' => 20, 'city'=> 'La Ceiba', 'capital' => 0 ],
            [ 'id' => 426, 'state_id' => 20, 'city'=> 'La Concepción de Trujllo', 'capital' => 0 ],
            [ 'id' => 427, 'state_id' => 20, 'city'=> 'La Mesa de Esnujaque', 'capital' => 0 ],
            [ 'id' => 428, 'state_id' => 20, 'city'=> 'La Puerta', 'capital' => 0 ],
            [ 'id' => 429, 'state_id' => 20, 'city'=> 'La Quebrada', 'capital' => 0 ],
            [ 'id' => 430, 'state_id' => 20, 'city'=> 'Mendoza Fría', 'capital' => 0 ],
            [ 'id' => 431, 'state_id' => 20, 'city'=> 'Meseta de Chimpire', 'capital' => 0 ],
            [ 'id' => 432, 'state_id' => 20, 'city'=> 'Monay', 'capital' => 0 ],
            [ 'id' => 433, 'state_id' => 20, 'city'=> 'Motatán', 'capital' => 0 ],
            [ 'id' => 434, 'state_id' => 20, 'city'=> 'Pampán', 'capital' => 0 ],
            [ 'id' => 435, 'state_id' => 20, 'city'=> 'Pampanito', 'capital' => 0 ],
            [ 'id' => 436, 'state_id' => 20, 'city'=> 'Sabana de Mendoza', 'capital' => 0 ],
            [ 'id' => 437, 'state_id' => 20, 'city'=> 'San Lázaro', 'capital' => 0 ],
            [ 'id' => 438, 'state_id' => 20, 'city'=> 'Santa Ana de Trujillo', 'capital' => 0 ],
            [ 'id' => 439, 'state_id' => 20, 'city'=> 'Tostós', 'capital' => 0 ],
            [ 'id' => 440, 'state_id' => 20, 'city'=> 'Trujillo', 'capital' => 1 ],
            [ 'id' => 441, 'state_id' => 20, 'city'=> 'Valera', 'capital' => 0 ],
            [ 'id' => 442, 'state_id' => 21, 'city'=> 'Carayaca', 'capital' => 0 ],
            [ 'id' => 443, 'state_id' => 21, 'city'=> 'Litoral', 'capital' => 0 ],
            [ 'id' => 444, 'state_id' => 25, 'city'=> 'Archipiélago Los Roques', 'capital' => 0 ],
            [ 'id' => 445, 'state_id' => 22, 'city'=> 'Aroa', 'capital' => 0 ],
            [ 'id' => 446, 'state_id' => 22, 'city'=> 'Boraure', 'capital' => 0 ],
            [ 'id' => 447, 'state_id' => 22, 'city'=> 'Campo Elías de Yaracuy', 'capital' => 0 ],
            [ 'id' => 448, 'state_id' => 22, 'city'=> 'Chivacoa', 'capital' => 0 ],
            [ 'id' => 449, 'state_id' => 22, 'city'=> 'Cocorote', 'capital' => 0 ],
            [ 'id' => 450, 'state_id' => 22, 'city'=> 'Farriar', 'capital' => 0 ],
            [ 'id' => 451, 'state_id' => 22, 'city'=> 'Guama', 'capital' => 0 ],
            [ 'id' => 452, 'state_id' => 22, 'city'=> 'Marín', 'capital' => 0 ],
            [ 'id' => 453, 'state_id' => 22, 'city'=> 'Nirgua', 'capital' => 0 ],
            [ 'id' => 454, 'state_id' => 22, 'city'=> 'Sabana de Parra', 'capital' => 0 ],
            [ 'id' => 455, 'state_id' => 22, 'city'=> 'Salom', 'capital' => 0 ],
            [ 'id' => 456, 'state_id' => 22, 'city'=> 'San Felipe', 'capital' => 1 ],
            [ 'id' => 457, 'state_id' => 22, 'city'=> 'San Pablo de Yaracuy', 'capital' => 0 ],
            [ 'id' => 458, 'state_id' => 22, 'city'=> 'Urachiche', 'capital' => 0 ],
            [ 'id' => 459, 'state_id' => 22, 'city'=> 'Yaritagua', 'capital' => 0 ],
            [ 'id' => 460, 'state_id' => 22, 'city'=> 'Yumare', 'capital' => 0 ],
            [ 'id' => 461, 'state_id' => 23, 'city'=> 'Bachaquero', 'capital' => 0 ],
            [ 'id' => 462, 'state_id' => 23, 'city'=> 'Bobures', 'capital' => 0 ],
            [ 'id' => 463, 'state_id' => 23, 'city'=> 'Cabimas', 'capital' => 0 ],
            [ 'id' => 464, 'state_id' => 23, 'city'=> 'Campo Concepción', 'capital' => 0 ],
            [ 'id' => 465, 'state_id' => 23, 'city'=> 'Campo Mara', 'capital' => 0 ],
            [ 'id' => 466, 'state_id' => 23, 'city'=> 'Campo Rojo', 'capital' => 0 ],
            [ 'id' => 467, 'state_id' => 23, 'city'=> 'Carrasquero', 'capital' => 0 ],
            [ 'id' => 468, 'state_id' => 23, 'city'=> 'Casigua', 'capital' => 0 ],
            [ 'id' => 469, 'state_id' => 23, 'city'=> 'Chiquinquirá', 'capital' => 0 ],
            [ 'id' => 470, 'state_id' => 23, 'city'=> 'Ciudad Ojeda', 'capital' => 0 ],
            [ 'id' => 471, 'state_id' => 23, 'city'=> 'El Batey', 'capital' => 0 ],
            [ 'id' => 472, 'state_id' => 23, 'city'=> 'El Carmelo', 'capital' => 0 ],
            [ 'id' => 473, 'state_id' => 23, 'city'=> 'El Chivo', 'capital' => 0 ],
            [ 'id' => 474, 'state_id' => 23, 'city'=> 'El Guayabo', 'capital' => 0 ],
            [ 'id' => 475, 'state_id' => 23, 'city'=> 'El Mene', 'capital' => 0 ],
            [ 'id' => 476, 'state_id' => 23, 'city'=> 'El Venado', 'capital' => 0 ],
            [ 'id' => 477, 'state_id' => 23, 'city'=> 'Encontrados', 'capital' => 0 ],
            [ 'id' => 478, 'state_id' => 23, 'city'=> 'Gibraltar', 'capital' => 0 ],
            [ 'id' => 479, 'state_id' => 23, 'city'=> 'Isla de Toas', 'capital' => 0 ],
            [ 'id' => 480, 'state_id' => 23, 'city'=> 'La Concepción del Zulia', 'capital' => 0 ],
            [ 'id' => 481, 'state_id' => 23, 'city'=> 'La Paz', 'capital' => 0 ],
            [ 'id' => 482, 'state_id' => 23, 'city'=> 'La Sierrita', 'capital' => 0 ],
            [ 'id' => 483, 'state_id' => 23, 'city'=> 'Lagunillas del Zulia', 'capital' => 0 ],
            [ 'id' => 484, 'state_id' => 23, 'city'=> 'Las Piedras de Perijá', 'capital' => 0 ],
            [ 'id' => 485, 'state_id' => 23, 'city'=> 'Los Cortijos', 'capital' => 0 ],
            [ 'id' => 486, 'state_id' => 23, 'city'=> 'Machiques', 'capital' => 0 ],
            [ 'id' => 487, 'state_id' => 23, 'city'=> 'Maracaibo', 'capital' => 1 ],
            [ 'id' => 488, 'state_id' => 23, 'city'=> 'Mene Grande', 'capital' => 0 ],
            [ 'id' => 489, 'state_id' => 23, 'city'=> 'Palmarejo', 'capital' => 0 ],
            [ 'id' => 490, 'state_id' => 23, 'city'=> 'Paraguaipoa', 'capital' => 0 ],
            [ 'id' => 491, 'state_id' => 23, 'city'=> 'Potrerito', 'capital' => 0 ],
            [ 'id' => 492, 'state_id' => 23, 'city'=> 'Pueblo Nuevo del Zulia', 'capital' => 0 ],
            [ 'id' => 493, 'state_id' => 23, 'city'=> 'Puertos de Altagracia', 'capital' => 0 ],
            [ 'id' => 494, 'state_id' => 23, 'city'=> 'Punta Gorda', 'capital' => 0 ],
            [ 'id' => 495, 'state_id' => 23, 'city'=> 'Sabaneta de Palma', 'capital' => 0 ],
            [ 'id' => 496, 'state_id' => 23, 'city'=> 'San Francisco', 'capital' => 0 ],
            [ 'id' => 497, 'state_id' => 23, 'city'=> 'San José de Perijá', 'capital' => 0 ],
            [ 'id' => 498, 'state_id' => 23, 'city'=> 'San Rafael del Moján', 'capital' => 0 ],
            [ 'id' => 499, 'state_id' => 23, 'city'=> 'San Timoteo', 'capital' => 0 ],
            [ 'id' => 500, 'state_id' => 23, 'city'=> 'Santa Bárbara Del Zulia', 'capital' => 0 ],
            [ 'id' => 501, 'state_id' => 23, 'city'=> 'Santa Cruz de Mara', 'capital' => 0 ],
            [ 'id' => 502, 'state_id' => 23, 'city'=> 'Santa Cruz del Zulia', 'capital' => 0 ],
            [ 'id' => 503, 'state_id' => 23, 'city'=> 'Santa Rita', 'capital' => 0 ],
            [ 'id' => 504, 'state_id' => 23, 'city'=> 'Sinamaica', 'capital' => 0 ],
            [ 'id' => 505, 'state_id' => 23, 'city'=> 'Tamare', 'capital' => 0 ],
            [ 'id' => 506, 'state_id' => 23, 'city'=> 'Tía Juana', 'capital' => 0 ],
            [ 'id' => 507, 'state_id' => 23, 'city'=> 'Villa del Rosario', 'capital' => 0 ],
            [ 'id' => 508, 'state_id' => 21, 'city'=> 'La Guaira', 'capital' => 1 ],
            [ 'id' => 509, 'state_id' => 21, 'city'=> 'Catia La Mar', 'capital' => 0 ],
            [ 'id' => 510, 'state_id' => 21, 'city'=> 'Macuto', 'capital' => 0 ],
            [ 'id' => 511, 'state_id' => 21, 'city'=> 'Naiguatá', 'capital' => 0 ],
            [ 'id' => 512, 'state_id' => 25, 'city'=> 'Archipiélago Los Monjes', 'capital' => 0 ],
            [ 'id' => 513, 'state_id' => 25, 'city'=> 'Isla La Tortuga y Cayos adyacentes', 'capital' => 0 ],
            [ 'id' => 514, 'state_id' => 25, 'city'=> 'Isla La Sola', 'capital' => 0 ],
            [ 'id' => 515, 'state_id' => 25, 'city'=> 'Islas Los Testigos', 'capital' => 0 ],
            [ 'id' => 516, 'state_id' => 25, 'city'=> 'Islas Los Frailes', 'capital' => 0 ],
            [ 'id' => 517, 'state_id' => 25, 'city'=> 'Isla La Orchila', 'capital' => 0 ],
            [ 'id' => 518, 'state_id' => 25, 'city'=> 'Archipiélago Las Aves', 'capital' => 0 ],
            [ 'id' => 519, 'state_id' => 25, 'city'=> 'Isla de Aves', 'capital' => 0 ],
            [ 'id' => 520, 'state_id' => 25, 'city'=> 'Isla La Blanquilla', 'capital' => 0 ],
            [ 'id' => 521, 'state_id' => 25, 'city'=> 'Isla de Patos', 'capital' => 0 ],
            [ 'id' => 522, 'state_id' => 25, 'city'=> 'Islas Los Hermanos', 'capital' => 0 ],
        ];

        foreach ($cities as $row) {
            App\City::create($row);
        }
    }
}
