<?php

use Illuminate\Database\Seeder;

class CiudadesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ciudad = [
            ['estado_id' => 1, 'ciudad' => 'Maroa', 'capital' => 0],
            ['estado_id' => 1, 'ciudad' => 'Puerto Ayacucho', 'capital' => 1],
            ['estado_id' => 1, 'ciudad' => 'San Fernando de Atabapo', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Anaco', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Aragua de Barcelona', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Barcelona', 'capital' => 1],
            ['estado_id' => 2, 'ciudad' => 'Boca de Uchire', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Cantaura', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Clarines', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'El Chaparro', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'El Pao Anzoátegui', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'El Tigre', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'El Tigrito', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Guanape', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Guanta', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Lechería', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Onoto', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Pariaguán', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Píritu', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Puerto La Cruz', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Puerto Píritu', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Sabana de Uchire', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'San Mateo Anzoátegui', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'San Pablo Anzoátegui', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'San Tomé', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Santa Ana de Anzoátegui', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Santa Fe Anzoátegui', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Santa Rosa', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Soledad', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Urica', 'capital' => 0],
            ['estado_id' => 2, 'ciudad' => 'Valle de Guanape', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'Achaguas', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'Biruaca', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'Bruzual', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'El Amparo', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'El Nula', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'Elorza', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'Guasdualito', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'Mantecal', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'Puerto Páez', 'capital' => 0],
            ['estado_id' => 3, 'ciudad' => 'San Fernando de Apure', 'capital' => 1],
            ['estado_id' => 3, 'ciudad' => 'San Juan de Payara', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Barbacoas', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Cagua', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Camatagua', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Choroní', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Colonia Tovar', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'El Consejo', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'La Victoria', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Las Tejerías', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Magdaleno', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Maracay', 'capital' => 1],
            ['estado_id' => 4, 'ciudad' => 'Ocumare de La Costa', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Palo Negro', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'San Casimiro', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'San Mateo', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'San Sebastián', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Santa Cruz de Aragua', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Tocorón', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Turmero', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Villa de Cura', 'capital' => 0],
            ['estado_id' => 4, 'ciudad' => 'Zuata', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Barinas', 'capital' => 1],
            ['estado_id' => 5, 'ciudad' => 'Barinitas', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Barrancas', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Calderas', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Capitanejo', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Ciudad Bolivia', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'El Cantón', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Las Veguitas', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Libertad de Barinas', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Sabaneta', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Santa Bárbara de Barinas', 'capital' => 0],
            ['estado_id' => 5, 'ciudad' => 'Socopó', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Caicara del Orinoco', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Canaima', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Ciudad Bolívar', 'capital' => 1],
            ['estado_id' => 6, 'ciudad' => 'Ciudad Piar', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'El Callao', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'El Dorado', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'El Manteco', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'El Palmar', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'El Pao', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Guasipati', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Guri', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'La Paragua', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Matanzas', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Puerto Ordaz', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'San Félix', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Santa Elena de Uairén', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Tumeremo', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Unare', 'capital' => 0],
            ['estado_id' => 6, 'ciudad' => 'Upata', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Bejuma', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Belén', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Campo de Carabobo', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Canoabo', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Central Tacarigua', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Chirgua', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Ciudad Alianza', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'El Palito', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Guacara', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Guigue', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Las Trincheras', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Los Guayos', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Mariara', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Miranda', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Montalbán', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Morón', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Naguanagua', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Puerto Cabello', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'San Joaquín', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Tocuyito', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Urama', 'capital' => 0],
            ['estado_id' => 7, 'ciudad' => 'Valencia', 'capital' => 1],
            ['estado_id' => 7, 'ciudad' => 'Vigirimita', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Aguirre', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Apartaderos Cojedes', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Arismendi', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Camuriquito', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'El Baúl', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'El Limón', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'El Pao Cojedes', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'El Socorro', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'La Aguadita', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Las Vegas', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Libertad de Cojedes', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Mapuey', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Piñedo', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Samancito', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'San Carlos', 'capital' => 1],
            ['estado_id' => 8, 'ciudad' => 'Sucre', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Tinaco', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Tinaquillo', 'capital' => 0],
            ['estado_id' => 8, 'ciudad' => 'Vallecito', 'capital' => 0],
            ['estado_id' => 9, 'ciudad' => 'Tucupita', 'capital' => 1],
            ['estado_id' => 24, 'ciudad' => 'Caracas', 'capital' => 1],
            ['estado_id' => 24, 'ciudad' => 'El Junquito', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Adícora', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Boca de Aroa', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Cabure', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Capadare', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Capatárida', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Chichiriviche', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Churuguara', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Coro', 'capital' => 1],
            ['estado_id' => 10, 'ciudad' => 'Cumarebo', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Dabajuro', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Judibana', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'La Cruz de Taratara', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'La Vela de Coro', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Los Taques', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Maparari', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Mene de Mauroa', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Mirimire', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Pedregal', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Píritu Falcón', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Pueblo Nuevo Falcón', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Puerto Cumarebo', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Punta Cardón', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Punto Fijo', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'San Juan de Los Cayos', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'San Luis', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Santa Ana Falcón', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Santa Cruz De Bucaral', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Tocopero', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Tocuyo de La Costa', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Tucacas', 'capital' => 0],
            ['estado_id' => 10, 'ciudad' => 'Yaracal', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Altagracia de Orituco', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Cabruta', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Calabozo', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Camaguán', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Chaguaramas Guárico', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'El Socorro', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'El Sombrero', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Las Mercedes de Los Llanos', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Lezama', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Onoto', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Ortíz', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'San José de Guaribe', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'San Juan de Los Morros', 'capital' => 1],
            ['estado_id' => 11, 'ciudad' => 'San Rafael de Laya', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Santa María de Ipire', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Tucupido', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Valle de La Pascua', 'capital' => 0],
            ['estado_id' => 11, 'ciudad' => 'Zaraza', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Aguada Grande', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Atarigua', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Barquisimeto', 'capital' => 1],
            ['estado_id' => 12, 'ciudad' => 'Bobare', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Cabudare', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Carora', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Cubiro', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Cují', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Duaca', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'El Manzano', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'El Tocuyo', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Guaríco', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Humocaro Alto', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Humocaro Bajo', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'La Miel', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Moroturo', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Quíbor', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Río Claro', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Sanare', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Santa Inés', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Sarare', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Siquisique', 'capital' => 0],
            ['estado_id' => 12, 'ciudad' => 'Tintorero', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Apartaderos Mérida', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Arapuey', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Bailadores', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Caja Seca', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Canaguá', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Chachopo', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Chiguara', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Ejido', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'El Vigía', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'La Azulita', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'La Playa', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Lagunillas Mérida', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Mérida', 'capital' => 1],
            ['estado_id' => 13, 'ciudad' => 'Mesa de Bolívar', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Mucuchíes', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Mucujepe', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Mucuruba', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Nueva Bolivia', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Palmarito', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Pueblo Llano', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Santa Cruz de Mora', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Santa Elena de Arenales', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Santo Domingo', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Tabáy', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Timotes', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Torondoy', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Tovar', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Tucani', 'capital' => 0],
            ['estado_id' => 13, 'ciudad' => 'Zea', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Araguita', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Carrizal', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Caucagua', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Chaguaramas Miranda', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Charallave', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Chirimena', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Chuspa', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Cúa', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Cupira', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Curiepe', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'El Guapo', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'El Jarillo', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Filas de Mariche', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Guarenas', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Guatire', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Higuerote', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Los Anaucos', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Los Teques', 'capital' => 1],
            ['estado_id' => 14, 'ciudad' => 'Ocumare del Tuy', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Panaquire', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Paracotos', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Río Chico', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'San Antonio de Los Altos', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'San Diego de Los Altos', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'San Fernando del Guapo', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'San Francisco de Yare', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'San José de Los Altos', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'San José de Río Chico', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'San Pedro de Los Altos', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Santa Lucía', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Santa Teresa', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Tacarigua de La Laguna', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Tacarigua de Mamporal', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Tácata', 'capital' => 0],
            ['estado_id' => 14, 'ciudad' => 'Turumo', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Aguasay', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Aragua de Maturín', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Barrancas del Orinoco', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Caicara de Maturín', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Caripe', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Caripito', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Chaguaramal', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Chaguaramas Monagas', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'El Furrial', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'El Tejero', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Jusepín', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'La Toscana', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Maturín', 'capital' => 1],
            ['estado_id' => 15, 'ciudad' => 'Miraflores', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Punta de Mata', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Quiriquire', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'San Antonio de Maturín', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'San Vicente Monagas', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Santa Bárbara', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Temblador', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Teresen', 'capital' => 0],
            ['estado_id' => 15, 'ciudad' => 'Uracoa', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Altagracia', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Boca de Pozo', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Boca de Río', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'El Espinal', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'El Valle del Espíritu Santo', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'El Yaque', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Juangriego', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'La Asunción', 'capital' => 1],
            ['estado_id' => 16, 'ciudad' => 'La Guardia', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Pampatar', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Porlamar', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Puerto Fermín', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Punta de Piedras', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'San Francisco de Macanao', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'San Juan Bautista', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'San Pedro de Coche', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Santa Ana de Nueva Esparta', 'capital' => 0],
            ['estado_id' => 16, 'ciudad' => 'Villa Rosa', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Acarigua', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Agua Blanca', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Araure', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Biscucuy', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Boconoito', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Campo Elías', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Chabasquén', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Guanare', 'capital' => 1],
            ['estado_id' => 17, 'ciudad' => 'Guanarito', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'La Aparición', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'La Misión', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Mesa de Cavacas', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Ospino', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Papelón', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Payara', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Pimpinela', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Píritu de Portuguesa', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'San Rafael de Onoto', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Santa Rosalía', 'capital' => 0],
            ['estado_id' => 17, 'ciudad' => 'Turén', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Altos de Sucre', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Araya', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Cariaco', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Carúpano', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Casanay', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Cumaná', 'capital' => 1],
            ['estado_id' => 18, 'ciudad' => 'Cumanacoa', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'El Morro Puerto Santo', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'El Pilar', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'El Poblado', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Guaca', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Guiria', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Irapa', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Manicuare', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Mariguitar', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Río Caribe', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'San Antonio del Golfo', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'San José de Aerocuar', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'San Vicente de Sucre', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Santa Fe de Sucre', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Tunapuy', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Yaguaraparo', 'capital' => 0],
            ['estado_id' => 18, 'ciudad' => 'Yoco', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Abejales', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Borota', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Bramon', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Capacho', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Colón', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Coloncito', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Cordero', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'El Cobre', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'El Pinal', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Independencia', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'La Fría', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'La Grita', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'La Pedrera', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'La Tendida', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Las Delicias', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Las Hernández', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Lobatera', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Michelena', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Palmira', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Pregonero', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Queniquea', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Rubio', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'San Antonio del Tachira', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'San Cristobal', 'capital' => 1],
            ['estado_id' => 19, 'ciudad' => 'San José de Bolívar', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'San Josecito', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'San Pedro del Río', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Santa Ana Táchira', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Seboruco', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Táriba', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Umuquena', 'capital' => 0],
            ['estado_id' => 19, 'ciudad' => 'Ureña', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Batatal', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Betijoque', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Boconó', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Carache', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Chejende', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Cuicas', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'El Dividive', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'El Jaguito', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Escuque', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Isnotú', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Jajó', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'La Ceiba', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'La Concepción de Trujllo', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'La Mesa de Esnujaque', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'La Puerta', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'La Quebrada', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Mendoza Fría', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Meseta de Chimpire', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Monay', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Motatán', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Pampán', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Pampanito', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Sabana de Mendoza', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'San Lázaro', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Santa Ana de Trujillo', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Tostós', 'capital' => 0],
            ['estado_id' => 20, 'ciudad' => 'Trujillo', 'capital' => 1],
            ['estado_id' => 20, 'ciudad' => 'Valera', 'capital' => 0],
            ['estado_id' => 21, 'ciudad' => 'Carayaca', 'capital' => 0],
            ['estado_id' => 21, 'ciudad' => 'Litoral', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Archipiélago Los Roques', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Aroa', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Boraure', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Campo Elías de Yaracuy', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Chivacoa', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Cocorote', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Farriar', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Guama', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Marín', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Nirgua', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Sabana de Parra', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Salom', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'San Felipe', 'capital' => 1],
            ['estado_id' => 22, 'ciudad' => 'San Pablo de Yaracuy', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Urachiche', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Yaritagua', 'capital' => 0],
            ['estado_id' => 22, 'ciudad' => 'Yumare', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Bachaquero', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Bobures', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Cabimas', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Campo Concepción', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Campo Mara', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Campo Rojo', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Carrasquero', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Casigua', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Chiquinquirá', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Ciudad Ojeda', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'El Batey', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'El Carmelo', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'El Chivo', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'El Guayabo', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'El Mene', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'El Venado', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Encontrados', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Gibraltar', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Isla de Toas', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'La Concepción del Zulia', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'La Paz', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'La Sierrita', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Lagunillas del Zulia', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Las Piedras de Perijá', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Los Cortijos', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Machiques', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Maracaibo', 'capital' => 1],
            ['estado_id' => 23, 'ciudad' => 'Mene Grande', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Palmarejo', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Paraguaipoa', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Potrerito', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Pueblo Nuevo del Zulia', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Puertos de Altagracia', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Punta Gorda', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Sabaneta de Palma', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'San Francisco', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'San José de Perijá', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'San Rafael del Moján', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'San Timoteo', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Santa Bárbara Del Zulia', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Santa Cruz de Mara', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Santa Cruz del Zulia', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Santa Rita', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Sinamaica', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Tamare', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Tía Juana', 'capital' => 0],
            ['estado_id' => 23, 'ciudad' => 'Villa del Rosario', 'capital' => 0],
            ['estado_id' => 21, 'ciudad' => 'La Guaira', 'capital' => 1],
            ['estado_id' => 21, 'ciudad' => 'Catia La Mar', 'capital' => 0],
            ['estado_id' => 21, 'ciudad' => 'Macuto', 'capital' => 0],
            ['estado_id' => 21, 'ciudad' => 'Naiguatá', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Archipiélago Los Monjes', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Isla La Tortuga y Cayos adyacentes', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Isla La Sola', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Islas Los Testigos', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Islas Los Frailes', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Isla La Orchila', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Archipiélago Las Aves', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Isla de Aves', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Isla La Blanquilla', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Isla de Patos', 'capital' => 0],
            ['estado_id' => 25, 'ciudad' => 'Islas Los Hermanos', 'capital' => 0]
        ];

        foreach ($ciudades as $row) {
            App\Ciudad::create($row);
        }
    }
}
