<?php

use Illuminate\Database\Seeder;

class MunicipalitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $municipalities = [
            [ 'id' => 1, 'state_id' => 1, 'municipality'=> 'Alto Orinoco' ],
            [ 'id' => 2, 'state_id' => 1, 'municipality'=> 'Atabapo' ],
            [ 'id' => 3, 'state_id' => 1, 'municipality'=> 'Atures' ],
            [ 'id' => 4, 'state_id' => 1, 'municipality'=> 'Autana' ],
            [ 'id' => 5, 'state_id' => 1, 'municipality'=> 'Manapiare' ],
            [ 'id' => 6, 'state_id' => 1, 'municipality'=> 'Maroa' ],
            [ 'id' => 7, 'state_id' => 1, 'municipality'=> 'Río Negro' ],
            [ 'id' => 8, 'state_id' => 2, 'municipality'=> 'Anaco' ],
            [ 'id' => 9, 'state_id' => 2, 'municipality'=> 'Aragua' ],
            [ 'id' => 10, 'state_id' => 2, 'municipality'=> 'Manuel Ezequiel Bruzual' ],
            [ 'id' => 11, 'state_id' => 2, 'municipality'=> 'Diego Bautista Urbaneja' ],
            [ 'id' => 12, 'state_id' => 2, 'municipality'=> 'Fernando Peñalver' ],
            [ 'id' => 13, 'state_id' => 2, 'municipality'=> 'Francisco Del Carmen Carvajal' ],
            [ 'id' => 14, 'state_id' => 2, 'municipality'=> 'General Sir Arthur McGregor' ],
            [ 'id' => 15, 'state_id' => 2, 'municipality'=> 'Guanta' ],
            [ 'id' => 16, 'state_id' => 2, 'municipality'=> 'Independencia' ],
            [ 'id' => 17, 'state_id' => 2, 'municipality'=> 'José Gregorio Monagas' ],
            [ 'id' => 18, 'state_id' => 2, 'municipality'=> 'Juan Antonio Sotillo' ],
            [ 'id' => 19, 'state_id' => 2, 'municipality'=> 'Juan Manuel Cajigal' ],
            [ 'id' => 20, 'state_id' => 2, 'municipality'=> 'Libertad' ],
            [ 'id' => 21, 'state_id' => 2, 'municipality'=> 'Francisco de Miranda' ],
            [ 'id' => 22, 'state_id' => 2, 'municipality'=> 'Pedro María Freites' ],
            [ 'id' => 23, 'state_id' => 2, 'municipality'=> 'Píritu' ],
            [ 'id' => 24, 'state_id' => 2, 'municipality'=> 'San José de Guanipa' ],
            [ 'id' => 25, 'state_id' => 2, 'municipality'=> 'San Juan de Capistrano' ],
            [ 'id' => 26, 'state_id' => 2, 'municipality'=> 'Santa Ana' ],
            [ 'id' => 27, 'state_id' => 2, 'municipality'=> 'Simón Bolívar' ],
            [ 'id' => 28, 'state_id' => 2, 'municipality'=> 'Simón Rodríguez' ],
            [ 'id' => 29, 'state_id' => 3, 'municipality'=> 'Achaguas' ],
            [ 'id' => 30, 'state_id' => 3, 'municipality'=> 'Biruaca' ],
            [ 'id' => 31, 'state_id' => 3, 'municipality'=> 'Muñóz' ],
            [ 'id' => 32, 'state_id' => 3, 'municipality'=> 'Páez' ],
            [ 'id' => 33, 'state_id' => 3, 'municipality'=> 'Pedro Camejo' ],
            [ 'id' => 34, 'state_id' => 3, 'municipality'=> 'Rómulo Gallegos' ],
            [ 'id' => 35, 'state_id' => 3, 'municipality'=> 'San Fernando' ],
            [ 'id' => 36, 'state_id' => 4, 'municipality'=> 'Atanasio Girardot' ],
            [ 'id' => 37, 'state_id' => 4, 'municipality'=> 'Bolívar' ],
            [ 'id' => 38, 'state_id' => 4, 'municipality'=> 'Camatagua' ],
            [ 'id' => 39, 'state_id' => 4, 'municipality'=> 'Francisco Linares Alcántara' ],
            [ 'id' => 40, 'state_id' => 4, 'municipality'=> 'José Ángel Lamas' ],
            [ 'id' => 41, 'state_id' => 4, 'municipality'=> 'José Félix Ribas' ],
            [ 'id' => 42, 'state_id' => 4, 'municipality'=> 'José Rafael Revenga' ],
            [ 'id' => 43, 'state_id' => 4, 'municipality'=> 'Libertador' ],
            [ 'id' => 44, 'state_id' => 4, 'municipality'=> 'Mario Briceño Iragorry' ],
            [ 'id' => 45, 'state_id' => 4, 'municipality'=> 'Ocumare de la Costa de Oro' ],
            [ 'id' => 46, 'state_id' => 4, 'municipality'=> 'San Casimiro' ],
            [ 'id' => 47, 'state_id' => 4, 'municipality'=> 'San Sebastián' ],
            [ 'id' => 48, 'state_id' => 4, 'municipality'=> 'Santiago Mariño' ],
            [ 'id' => 49, 'state_id' => 4, 'municipality'=> 'Santos Michelena' ],
            [ 'id' => 50, 'state_id' => 4, 'municipality'=> 'Sucre' ],
            [ 'id' => 51, 'state_id' => 4, 'municipality'=> 'Tovar' ],
            [ 'id' => 52, 'state_id' => 4, 'municipality'=> 'Urdaneta' ],
            [ 'id' => 53, 'state_id' => 4, 'municipality'=> 'Zamora' ],
            [ 'id' => 54, 'state_id' => 5, 'municipality'=> 'Alberto Arvelo Torrealba' ],
            [ 'id' => 55, 'state_id' => 5, 'municipality'=> 'Andrés Eloy Blanco' ],
            [ 'id' => 56, 'state_id' => 5, 'municipality'=> 'Antonio José de Sucre' ],
            [ 'id' => 57, 'state_id' => 5, 'municipality'=> 'Arismendi' ],
            [ 'id' => 58, 'state_id' => 5, 'municipality'=> 'Barinas' ],
            [ 'id' => 59, 'state_id' => 5, 'municipality'=> 'Bolívar' ],
            [ 'id' => 60, 'state_id' => 5, 'municipality'=> 'Cruz Paredes' ],
            [ 'id' => 61, 'state_id' => 5, 'municipality'=> 'Ezequiel Zamora' ],
            [ 'id' => 62, 'state_id' => 5, 'municipality'=> 'Obispos' ],
            [ 'id' => 63, 'state_id' => 5, 'municipality'=> 'Pedraza' ],
            [ 'id' => 64, 'state_id' => 5, 'municipality'=> 'Rojas' ],
            [ 'id' => 65, 'state_id' => 5, 'municipality'=> 'Sosa' ],
            [ 'id' => 66, 'state_id' => 6, 'municipality'=> 'Caroní' ],
            [ 'id' => 67, 'state_id' => 6, 'municipality'=> 'Cedeño' ],
            [ 'id' => 68, 'state_id' => 6, 'municipality'=> 'El Callao' ],
            [ 'id' => 69, 'state_id' => 6, 'municipality'=> 'Gran Sabana' ],
            [ 'id' => 70, 'state_id' => 6, 'municipality'=> 'Heres' ],
            [ 'id' => 71, 'state_id' => 6, 'municipality'=> 'Piar' ],
            [ 'id' => 72, 'state_id' => 6, 'municipality'=> 'Angostura (Raúl Leoni)' ],
            [ 'id' => 73, 'state_id' => 6, 'municipality'=> 'Roscio' ],
            [ 'id' => 74, 'state_id' => 6, 'municipality'=> 'Sifontes' ],
            [ 'id' => 75, 'state_id' => 6, 'municipality'=> 'Sucre' ],
            [ 'id' => 76, 'state_id' => 6, 'municipality'=> 'Padre Pedro Chien' ],
            [ 'id' => 77, 'state_id' => 7, 'municipality'=> 'Bejuma' ],
            [ 'id' => 78, 'state_id' => 7, 'municipality'=> 'Carlos Arvelo' ],
            [ 'id' => 79, 'state_id' => 7, 'municipality'=> 'Diego Ibarra' ],
            [ 'id' => 80, 'state_id' => 7, 'municipality'=> 'Guacara' ],
            [ 'id' => 81, 'state_id' => 7, 'municipality'=> 'Juan José Mora' ],
            [ 'id' => 82, 'state_id' => 7, 'municipality'=> 'Libertador' ],
            [ 'id' => 83, 'state_id' => 7, 'municipality'=> 'Los Guayos' ],
            [ 'id' => 84, 'state_id' => 7, 'municipality'=> 'Miranda' ],
            [ 'id' => 85, 'state_id' => 7, 'municipality'=> 'Montalbán' ],
            [ 'id' => 86, 'state_id' => 7, 'municipality'=> 'Naguanagua' ],
            [ 'id' => 87, 'state_id' => 7, 'municipality'=> 'Puerto Cabello' ],
            [ 'id' => 88, 'state_id' => 7, 'municipality'=> 'San Diego' ],
            [ 'id' => 89, 'state_id' => 7, 'municipality'=> 'San Joaquín' ],
            [ 'id' => 90, 'state_id' => 7, 'municipality'=> 'Valencia' ],
            [ 'id' => 91, 'state_id' => 8, 'municipality'=> 'Anzoátegui' ],
            [ 'id' => 92, 'state_id' => 8, 'municipality'=> 'Tinaquillo' ],
            [ 'id' => 93, 'state_id' => 8, 'municipality'=> 'Girardot' ],
            [ 'id' => 94, 'state_id' => 8, 'municipality'=> 'Lima Blanco' ],
            [ 'id' => 95, 'state_id' => 8, 'municipality'=> 'Pao de San Juan Bautista' ],
            [ 'id' => 96, 'state_id' => 8, 'municipality'=> 'Ricaurte' ],
            [ 'id' => 97, 'state_id' => 8, 'municipality'=> 'Rómulo Gallegos' ],
            [ 'id' => 98, 'state_id' => 8, 'municipality'=> 'San Carlos' ],
            [ 'id' => 99, 'state_id' => 8, 'municipality'=> 'Tinaco' ],
            [ 'id' => 100, 'state_id' => 9, 'municipality'=> 'Antonio Díaz' ],
            [ 'id' => 101, 'state_id' => 9, 'municipality'=> 'Casacoima' ],
            [ 'id' => 102, 'state_id' => 9, 'municipality'=> 'Pedernales' ],
            [ 'id' => 103, 'state_id' => 9, 'municipality'=> 'Tucupita' ],
            [ 'id' => 104, 'state_id' => 10, 'municipality'=> 'Acosta' ],
            [ 'id' => 105, 'state_id' => 10, 'municipality'=> 'Bolívar' ],
            [ 'id' => 106, 'state_id' => 10, 'municipality'=> 'Buchivacoa' ],
            [ 'id' => 107, 'state_id' => 10, 'municipality'=> 'Cacique Manaure' ],
            [ 'id' => 108, 'state_id' => 10, 'municipality'=> 'Carirubana' ],
            [ 'id' => 109, 'state_id' => 10, 'municipality'=> 'Colina' ],
            [ 'id' => 110, 'state_id' => 10, 'municipality'=> 'Dabajuro' ],
            [ 'id' => 111, 'state_id' => 10, 'municipality'=> 'Democracia' ],
            [ 'id' => 112, 'state_id' => 10, 'municipality'=> 'Falcón' ],
            [ 'id' => 113, 'state_id' => 10, 'municipality'=> 'Federación' ],
            [ 'id' => 114, 'state_id' => 10, 'municipality'=> 'Jacura' ],
            [ 'id' => 115, 'state_id' => 10, 'municipality'=> 'José Laurencio Silva' ],
            [ 'id' => 116, 'state_id' => 10, 'municipality'=> 'Los Taques' ],
            [ 'id' => 117, 'state_id' => 10, 'municipality'=> 'Mauroa' ],
            [ 'id' => 118, 'state_id' => 10, 'municipality'=> 'Miranda' ],
            [ 'id' => 119, 'state_id' => 10, 'municipality'=> 'Monseñor Iturriza' ],
            [ 'id' => 120, 'state_id' => 10, 'municipality'=> 'Palmasola' ],
            [ 'id' => 121, 'state_id' => 10, 'municipality'=> 'Petit' ],
            [ 'id' => 122, 'state_id' => 10, 'municipality'=> 'Píritu' ],
            [ 'id' => 123, 'state_id' => 10, 'municipality'=> 'San Francisco' ],
            [ 'id' => 124, 'state_id' => 10, 'municipality'=> 'Sucre' ],
            [ 'id' => 125, 'state_id' => 10, 'municipality'=> 'Tocópero' ],
            [ 'id' => 126, 'state_id' => 10, 'municipality'=> 'Unión' ],
            [ 'id' => 127, 'state_id' => 10, 'municipality'=> 'Urumaco' ],
            [ 'id' => 128, 'state_id' => 10, 'municipality'=> 'Zamora' ],
            [ 'id' => 129, 'state_id' => 11, 'municipality'=> 'Camaguán' ],
            [ 'id' => 130, 'state_id' => 11, 'municipality'=> 'Chaguaramas' ],
            [ 'id' => 131, 'state_id' => 11, 'municipality'=> 'El Socorro' ],
            [ 'id' => 132, 'state_id' => 11, 'municipality'=> 'José Félix Ribas' ],
            [ 'id' => 133, 'state_id' => 11, 'municipality'=> 'José Tadeo Monagas' ],
            [ 'id' => 134, 'state_id' => 11, 'municipality'=> 'Juan Germán Roscio' ],
            [ 'id' => 135, 'state_id' => 11, 'municipality'=> 'Julián Mellado' ],
            [ 'id' => 136, 'state_id' => 11, 'municipality'=> 'Las Mercedes' ],
            [ 'id' => 137, 'state_id' => 11, 'municipality'=> 'Leonardo Infante' ],
            [ 'id' => 138, 'state_id' => 11, 'municipality'=> 'Pedro Zaraza' ],
            [ 'id' => 139, 'state_id' => 11, 'municipality'=> 'Ortíz' ],
            [ 'id' => 140, 'state_id' => 11, 'municipality'=> 'San Gerónimo de Guayabal' ],
            [ 'id' => 141, 'state_id' => 11, 'municipality'=> 'San José de Guaribe' ],
            [ 'id' => 142, 'state_id' => 11, 'municipality'=> 'Santa María de Ipire' ],
            [ 'id' => 143, 'state_id' => 11, 'municipality'=> 'Sebastián Francisco de Miranda' ],
            [ 'id' => 144, 'state_id' => 12, 'municipality'=> 'Andrés Eloy Blanco' ],
            [ 'id' => 145, 'state_id' => 12, 'municipality'=> 'Crespo' ],
            [ 'id' => 146, 'state_id' => 12, 'municipality'=> 'Iribarren' ],
            [ 'id' => 147, 'state_id' => 12, 'municipality'=> 'Jiménez' ],
            [ 'id' => 148, 'state_id' => 12, 'municipality'=> 'Morán' ],
            [ 'id' => 149, 'state_id' => 12, 'municipality'=> 'Palavecino' ],
            [ 'id' => 150, 'state_id' => 12, 'municipality'=> 'Simón Planas' ],
            [ 'id' => 151, 'state_id' => 12, 'municipality'=> 'Torres' ],
            [ 'id' => 152, 'state_id' => 12, 'municipality'=> 'Urdaneta' ],
            [ 'id' => 179, 'state_id' => 13, 'municipality'=> 'Alberto Adriani' ],
            [ 'id' => 180, 'state_id' => 13, 'municipality'=> 'Andrés Bello' ],
            [ 'id' => 181, 'state_id' => 13, 'municipality'=> 'Antonio Pinto Salinas' ],
            [ 'id' => 182, 'state_id' => 13, 'municipality'=> 'Aricagua' ],
            [ 'id' => 183, 'state_id' => 13, 'municipality'=> 'Arzobispo Chacón' ],
            [ 'id' => 184, 'state_id' => 13, 'municipality'=> 'Campo Elías' ],
            [ 'id' => 185, 'state_id' => 13, 'municipality'=> 'Caracciolo Parra Olmedo' ],
            [ 'id' => 186, 'state_id' => 13, 'municipality'=> 'Cardenal Quintero' ],
            [ 'id' => 187, 'state_id' => 13, 'municipality'=> 'Guaraque' ],
            [ 'id' => 188, 'state_id' => 13, 'municipality'=> 'Julio César Salas' ],
            [ 'id' => 189, 'state_id' => 13, 'municipality'=> 'Justo Briceño' ],
            [ 'id' => 190, 'state_id' => 13, 'municipality'=> 'Libertador' ],
            [ 'id' => 191, 'state_id' => 13, 'municipality'=> 'Miranda' ],
            [ 'id' => 192, 'state_id' => 13, 'municipality'=> 'Obispo Ramos de Lora' ],
            [ 'id' => 193, 'state_id' => 13, 'municipality'=> 'Padre Noguera' ],
            [ 'id' => 194, 'state_id' => 13, 'municipality'=> 'Pueblo Llano' ],
            [ 'id' => 195, 'state_id' => 13, 'municipality'=> 'Rangel' ],
            [ 'id' => 196, 'state_id' => 13, 'municipality'=> 'Rivas Dávila' ],
            [ 'id' => 197, 'state_id' => 13, 'municipality'=> 'Santos Marquina' ],
            [ 'id' => 198, 'state_id' => 13, 'municipality'=> 'Sucre' ],
            [ 'id' => 199, 'state_id' => 13, 'municipality'=> 'Tovar' ],
            [ 'id' => 200, 'state_id' => 13, 'municipality'=> 'Tulio Febres Cordero' ],
            [ 'id' => 201, 'state_id' => 13, 'municipality'=> 'Zea' ],
            [ 'id' => 223, 'state_id' => 14, 'municipality'=> 'Acevedo' ],
            [ 'id' => 224, 'state_id' => 14, 'municipality'=> 'Andrés Bello' ],
            [ 'id' => 225, 'state_id' => 14, 'municipality'=> 'Baruta' ],
            [ 'id' => 226, 'state_id' => 14, 'municipality'=> 'Brión' ],
            [ 'id' => 227, 'state_id' => 14, 'municipality'=> 'Buroz' ],
            [ 'id' => 228, 'state_id' => 14, 'municipality'=> 'Carrizal' ],
            [ 'id' => 229, 'state_id' => 14, 'municipality'=> 'Chacao' ],
            [ 'id' => 230, 'state_id' => 14, 'municipality'=> 'Cristóbal Rojas' ],
            [ 'id' => 231, 'state_id' => 14, 'municipality'=> 'El Hatillo' ],
            [ 'id' => 232, 'state_id' => 14, 'municipality'=> 'Guaicaipuro' ],
            [ 'id' => 233, 'state_id' => 14, 'municipality'=> 'Independencia' ],
            [ 'id' => 234, 'state_id' => 14, 'municipality'=> 'Lander' ],
            [ 'id' => 235, 'state_id' => 14, 'municipality'=> 'Los Salias' ],
            [ 'id' => 236, 'state_id' => 14, 'municipality'=> 'Páez' ],
            [ 'id' => 237, 'state_id' => 14, 'municipality'=> 'Paz Castillo' ],
            [ 'id' => 238, 'state_id' => 14, 'municipality'=> 'Pedro Gual' ],
            [ 'id' => 239, 'state_id' => 14, 'municipality'=> 'Plaza' ],
            [ 'id' => 240, 'state_id' => 14, 'municipality'=> 'Simón Bolívar' ],
            [ 'id' => 241, 'state_id' => 14, 'municipality'=> 'Sucre' ],
            [ 'id' => 242, 'state_id' => 14, 'municipality'=> 'Urdaneta' ],
            [ 'id' => 243, 'state_id' => 14, 'municipality'=> 'Zamora' ],
            [ 'id' => 258, 'state_id' => 15, 'municipality'=> 'Acosta' ],
            [ 'id' => 259, 'state_id' => 15, 'municipality'=> 'Aguasay' ],
            [ 'id' => 260, 'state_id' => 15, 'municipality'=> 'Bolívar' ],
            [ 'id' => 261, 'state_id' => 15, 'municipality'=> 'Caripe' ],
            [ 'id' => 262, 'state_id' => 15, 'municipality'=> 'Cedeño' ],
            [ 'id' => 263, 'state_id' => 15, 'municipality'=> 'Ezequiel Zamora' ],
            [ 'id' => 264, 'state_id' => 15, 'municipality'=> 'Libertador' ],
            [ 'id' => 265, 'state_id' => 15, 'municipality'=> 'Maturín' ],
            [ 'id' => 266, 'state_id' => 15, 'municipality'=> 'Piar' ],
            [ 'id' => 267, 'state_id' => 15, 'municipality'=> 'Punceres' ],
            [ 'id' => 268, 'state_id' => 15, 'municipality'=> 'Santa Bárbara' ],
            [ 'id' => 269, 'state_id' => 15, 'municipality'=> 'Sotillo' ],
            [ 'id' => 270, 'state_id' => 15, 'municipality'=> 'Uracoa' ],
            [ 'id' => 271, 'state_id' => 16, 'municipality'=> 'Antolín del Campo' ],
            [ 'id' => 272, 'state_id' => 16, 'municipality'=> 'Arismendi' ],
            [ 'id' => 273, 'state_id' => 16, 'municipality'=> 'García' ],
            [ 'id' => 274, 'state_id' => 16, 'municipality'=> 'Gómez' ],
            [ 'id' => 275, 'state_id' => 16, 'municipality'=> 'Maneiro' ],
            [ 'id' => 276, 'state_id' => 16, 'municipality'=> 'Marcano' ],
            [ 'id' => 277, 'state_id' => 16, 'municipality'=> 'Mariño' ],
            [ 'id' => 278, 'state_id' => 16, 'municipality'=> 'Península de Macanao' ],
            [ 'id' => 279, 'state_id' => 16, 'municipality'=> 'Tubores' ],
            [ 'id' => 280, 'state_id' => 16, 'municipality'=> 'Villalba' ],
            [ 'id' => 281, 'state_id' => 16, 'municipality'=> 'Díaz' ],
            [ 'id' => 282, 'state_id' => 17, 'municipality'=> 'Agua Blanca' ],
            [ 'id' => 283, 'state_id' => 17, 'municipality'=> 'Araure' ],
            [ 'id' => 284, 'state_id' => 17, 'municipality'=> 'Esteller' ],
            [ 'id' => 285, 'state_id' => 17, 'municipality'=> 'Guanare' ],
            [ 'id' => 286, 'state_id' => 17, 'municipality'=> 'Guanarito' ],
            [ 'id' => 287, 'state_id' => 17, 'municipality'=> 'Monseñor José Vicente de Unda' ],
            [ 'id' => 288, 'state_id' => 17, 'municipality'=> 'Ospino' ],
            [ 'id' => 289, 'state_id' => 17, 'municipality'=> 'Páez' ],
            [ 'id' => 290, 'state_id' => 17, 'municipality'=> 'Papelón' ],
            [ 'id' => 291, 'state_id' => 17, 'municipality'=> 'San Genaro de Boconoíto' ],
            [ 'id' => 292, 'state_id' => 17, 'municipality'=> 'San Rafael de Onoto' ],
            [ 'id' => 293, 'state_id' => 17, 'municipality'=> 'Santa Rosalía' ],
            [ 'id' => 294, 'state_id' => 17, 'municipality'=> 'Sucre' ],
            [ 'id' => 295, 'state_id' => 17, 'municipality'=> 'Turén' ],
            [ 'id' => 296, 'state_id' => 18, 'municipality'=> 'Andrés Eloy Blanco' ],
            [ 'id' => 297, 'state_id' => 18, 'municipality'=> 'Andrés Mata' ],
            [ 'id' => 298, 'state_id' => 18, 'municipality'=> 'Arismendi' ],
            [ 'id' => 299, 'state_id' => 18, 'municipality'=> 'Benítez' ],
            [ 'id' => 300, 'state_id' => 18, 'municipality'=> 'Bermúdez' ],
            [ 'id' => 301, 'state_id' => 18, 'municipality'=> 'Bolívar' ],
            [ 'id' => 302, 'state_id' => 18, 'municipality'=> 'Cajigal' ],
            [ 'id' => 303, 'state_id' => 18, 'municipality'=> 'Cruz Salmerón Acosta' ],
            [ 'id' => 304, 'state_id' => 18, 'municipality'=> 'Libertador' ],
            [ 'id' => 305, 'state_id' => 18, 'municipality'=> 'Mariño' ],
            [ 'id' => 306, 'state_id' => 18, 'municipality'=> 'Mejía' ],
            [ 'id' => 307, 'state_id' => 18, 'municipality'=> 'Montes' ],
            [ 'id' => 308, 'state_id' => 18, 'municipality'=> 'Ribero' ],
            [ 'id' => 309, 'state_id' => 18, 'municipality'=> 'Sucre' ],
            [ 'id' => 310, 'state_id' => 18, 'municipality'=> 'Valdéz' ],
            [ 'id' => 341, 'state_id' => 19, 'municipality'=> 'Andrés Bello' ],
            [ 'id' => 342, 'state_id' => 19, 'municipality'=> 'Antonio Rómulo Costa' ],
            [ 'id' => 343, 'state_id' => 19, 'municipality'=> 'Ayacucho' ],
            [ 'id' => 344, 'state_id' => 19, 'municipality'=> 'Bolívar' ],
            [ 'id' => 345, 'state_id' => 19, 'municipality'=> 'Cárdenas' ],
            [ 'id' => 346, 'state_id' => 19, 'municipality'=> 'Córdoba' ],
            [ 'id' => 347, 'state_id' => 19, 'municipality'=> 'Fernández Feo' ],
            [ 'id' => 348, 'state_id' => 19, 'municipality'=> 'Francisco de Miranda' ],
            [ 'id' => 349, 'state_id' => 19, 'municipality'=> 'García de Hevia' ],
            [ 'id' => 350, 'state_id' => 19, 'municipality'=> 'Guásimos' ],
            [ 'id' => 351, 'state_id' => 19, 'municipality'=> 'Independencia' ],
            [ 'id' => 352, 'state_id' => 19, 'municipality'=> 'Jáuregui' ],
            [ 'id' => 353, 'state_id' => 19, 'municipality'=> 'José María Vargas' ],
            [ 'id' => 354, 'state_id' => 19, 'municipality'=> 'Junín' ],
            [ 'id' => 355, 'state_id' => 19, 'municipality'=> 'Libertad' ],
            [ 'id' => 356, 'state_id' => 19, 'municipality'=> 'Libertador' ],
            [ 'id' => 357, 'state_id' => 19, 'municipality'=> 'Lobatera' ],
            [ 'id' => 358, 'state_id' => 19, 'municipality'=> 'Michelena' ],
            [ 'id' => 359, 'state_id' => 19, 'municipality'=> 'Panamericano' ],
            [ 'id' => 360, 'state_id' => 19, 'municipality'=> 'Pedro María Ureña' ],
            [ 'id' => 361, 'state_id' => 19, 'municipality'=> 'Rafael Urdaneta' ],
            [ 'id' => 362, 'state_id' => 19, 'municipality'=> 'Samuel Darío Maldonado' ],
            [ 'id' => 363, 'state_id' => 19, 'municipality'=> 'San Cristóbal' ],
            [ 'id' => 364, 'state_id' => 19, 'municipality'=> 'Seboruco' ],
            [ 'id' => 365, 'state_id' => 19, 'municipality'=> 'Simón Rodríguez' ],
            [ 'id' => 366, 'state_id' => 19, 'municipality'=> 'Sucre' ],
            [ 'id' => 367, 'state_id' => 19, 'municipality'=> 'Torbes' ],
            [ 'id' => 368, 'state_id' => 19, 'municipality'=> 'Uribante' ],
            [ 'id' => 369, 'state_id' => 19, 'municipality'=> 'San Judas Tadeo' ],
            [ 'id' => 370, 'state_id' => 20, 'municipality'=> 'Andrés Bello' ],
            [ 'id' => 371, 'state_id' => 20, 'municipality'=> 'Boconó' ],
            [ 'id' => 372, 'state_id' => 20, 'municipality'=> 'Bolívar' ],
            [ 'id' => 373, 'state_id' => 20, 'municipality'=> 'Candelaria' ],
            [ 'id' => 374, 'state_id' => 20, 'municipality'=> 'Carache' ],
            [ 'id' => 375, 'state_id' => 20, 'municipality'=> 'Escuque' ],
            [ 'id' => 376, 'state_id' => 20, 'municipality'=> 'José Felipe Márquez Cañizalez' ],
            [ 'id' => 377, 'state_id' => 20, 'municipality'=> 'Juan Vicente Campos Elías' ],
            [ 'id' => 378, 'state_id' => 20, 'municipality'=> 'La Ceiba' ],
            [ 'id' => 379, 'state_id' => 20, 'municipality'=> 'Miranda' ],
            [ 'id' => 380, 'state_id' => 20, 'municipality'=> 'Monte Carmelo' ],
            [ 'id' => 381, 'state_id' => 20, 'municipality'=> 'Motatán' ],
            [ 'id' => 382, 'state_id' => 20, 'municipality'=> 'Pampán' ],
            [ 'id' => 383, 'state_id' => 20, 'municipality'=> 'Pampanito' ],
            [ 'id' => 384, 'state_id' => 20, 'municipality'=> 'Rafael Rangel' ],
            [ 'id' => 385, 'state_id' => 20, 'municipality'=> 'San Rafael de Carvajal' ],
            [ 'id' => 386, 'state_id' => 20, 'municipality'=> 'Sucre' ],
            [ 'id' => 387, 'state_id' => 20, 'municipality'=> 'Trujillo' ],
            [ 'id' => 388, 'state_id' => 20, 'municipality'=> 'Urdaneta' ],
            [ 'id' => 389, 'state_id' => 20, 'municipality'=> 'Valera' ],
            [ 'id' => 390, 'state_id' => 21, 'municipality'=> 'Vargas' ],
            [ 'id' => 391, 'state_id' => 22, 'municipality'=> 'Arístides Bastidas' ],
            [ 'id' => 392, 'state_id' => 22, 'municipality'=> 'Bolívar' ],
            [ 'id' => 407, 'state_id' => 22, 'municipality'=> 'Bruzual' ],
            [ 'id' => 408, 'state_id' => 22, 'municipality'=> 'Cocorote' ],
            [ 'id' => 409, 'state_id' => 22, 'municipality'=> 'Independencia' ],
            [ 'id' => 410, 'state_id' => 22, 'municipality'=> 'José Antonio Páez' ],
            [ 'id' => 411, 'state_id' => 22, 'municipality'=> 'La Trinidad' ],
            [ 'id' => 412, 'state_id' => 22, 'municipality'=> 'Manuel Monge' ],
            [ 'id' => 413, 'state_id' => 22, 'municipality'=> 'Nirgua' ],
            [ 'id' => 414, 'state_id' => 22, 'municipality'=> 'Peña' ],
            [ 'id' => 415, 'state_id' => 22, 'municipality'=> 'San Felipe' ],
            [ 'id' => 416, 'state_id' => 22, 'municipality'=> 'Sucre' ],
            [ 'id' => 417, 'state_id' => 22, 'municipality'=> 'Urachiche' ],
            [ 'id' => 418, 'state_id' => 22, 'municipality'=> 'José Joaquín Veroes' ],
            [ 'id' => 441, 'state_id' => 23, 'municipality'=> 'Almirante Padilla' ],
            [ 'id' => 442, 'state_id' => 23, 'municipality'=> 'Baralt' ],
            [ 'id' => 443, 'state_id' => 23, 'municipality'=> 'Cabimas' ],
            [ 'id' => 444, 'state_id' => 23, 'municipality'=> 'Catatumbo' ],
            [ 'id' => 445, 'state_id' => 23, 'municipality'=> 'Colón' ],
            [ 'id' => 446, 'state_id' => 23, 'municipality'=> 'Francisco Javier Pulgar' ],
            [ 'id' => 447, 'state_id' => 23, 'municipality'=> 'Páez' ],
            [ 'id' => 448, 'state_id' => 23, 'municipality'=> 'Jesús Enrique Losada' ],
            [ 'id' => 449, 'state_id' => 23, 'municipality'=> 'Jesús María Semprún' ],
            [ 'id' => 450, 'state_id' => 23, 'municipality'=> 'La Cañada de Urdaneta' ],
            [ 'id' => 451, 'state_id' => 23, 'municipality'=> 'Lagunillas' ],
            [ 'id' => 452, 'state_id' => 23, 'municipality'=> 'Machiques de Perijá' ],
            [ 'id' => 453, 'state_id' => 23, 'municipality'=> 'Mara' ],
            [ 'id' => 454, 'state_id' => 23, 'municipality'=> 'Maracaibo' ],
            [ 'id' => 455, 'state_id' => 23, 'municipality'=> 'Miranda' ],
            [ 'id' => 456, 'state_id' => 23, 'municipality'=> 'Rosario de Perijá' ],
            [ 'id' => 457, 'state_id' => 23, 'municipality'=> 'San Francisco' ],
            [ 'id' => 458, 'state_id' => 23, 'municipality'=> 'Santa Rita' ],
            [ 'id' => 459, 'state_id' => 23, 'municipality'=> 'Simón Bolívar' ],
            [ 'id' => 460, 'state_id' => 23, 'municipality'=> 'Sucre' ],
            [ 'id' => 461, 'state_id' => 23, 'municipality'=> 'Valmore Rodríguez' ],
            [ 'id' => 462, 'state_id' => 24, 'municipality'=> 'Libertador' ],
        ];

        foreach ($municipalities as $row) {
            App\Municipality::create($row);
        }
    }
}
