<?php

use Illuminate\Database\Seeder;

class ParishesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $parishes = [
            [ 'id' => 1, 'municipality_id' => 1, 'parish'=> 'Alto Orinoco' ],
            [ 'id' => 2, 'municipality_id' => 1, 'parish'=> 'Huachamacare Acanaña' ],
            [ 'id' => 3, 'municipality_id' => 1, 'parish'=> 'Marawaka Toky Shamanaña' ],
            [ 'id' => 4, 'municipality_id' => 1, 'parish'=> 'Mavaka Mavaka' ],
            [ 'id' => 5, 'municipality_id' => 1, 'parish'=> 'Sierra Parima Parimabé' ],
            [ 'id' => 6, 'municipality_id' => 2, 'parish'=> 'Ucata Laja Lisa' ],
            [ 'id' => 7, 'municipality_id' => 2, 'parish'=> 'Yapacana Macuruco' ],
            [ 'id' => 8, 'municipality_id' => 2, 'parish'=> 'Caname Guarinuma' ],
            [ 'id' => 9, 'municipality_id' => 3, 'parish'=> 'Fernando Girón Tovar' ],
            [ 'id' => 10, 'municipality_id' => 3, 'parish'=> 'Luis Alberto Gómez' ],
            [ 'id' => 11, 'municipality_id' => 3, 'parish'=> 'Pahueña Limón de Parhueña' ],
            [ 'id' => 12, 'municipality_id' => 3, 'parish'=> 'Platanillal Platanillal' ],
            [ 'id' => 13, 'municipality_id' => 4, 'parish'=> 'Samariapo' ],
            [ 'id' => 14, 'municipality_id' => 4, 'parish'=> 'Sipapo' ],
            [ 'id' => 15, 'municipality_id' => 4, 'parish'=> 'Munduapo' ],
            [ 'id' => 16, 'municipality_id' => 4, 'parish'=> 'Guayapo' ],
            [ 'id' => 17, 'municipality_id' => 5, 'parish'=> 'Alto Ventuari' ],
            [ 'id' => 18, 'municipality_id' => 5, 'parish'=> 'Medio Ventuari' ],
            [ 'id' => 19, 'municipality_id' => 5, 'parish'=> 'Bajo Ventuari' ],
            [ 'id' => 20, 'municipality_id' => 6, 'parish'=> 'Victorino' ],
            [ 'id' => 21, 'municipality_id' => 6, 'parish'=> 'Comunidad' ],
            [ 'id' => 22, 'municipality_id' => 7, 'parish'=> 'Casiquiare' ],
            [ 'id' => 23, 'municipality_id' => 7, 'parish'=> 'Cocuy' ],
            [ 'id' => 24, 'municipality_id' => 7, 'parish'=> 'San Carlos de Río Negro' ],
            [ 'id' => 25, 'municipality_id' => 7, 'parish'=> 'Solano' ],
            [ 'id' => 26, 'municipality_id' => 8, 'parish'=> 'Anaco' ],
            [ 'id' => 27, 'municipality_id' => 8, 'parish'=> 'San Joaquín' ],
            [ 'id' => 28, 'municipality_id' => 9, 'parish'=> 'Cachipo' ],
            [ 'id' => 29, 'municipality_id' => 9, 'parish'=> 'Aragua de Barcelona' ],
            [ 'id' => 30, 'municipality_id' => 11, 'parish'=> 'Lechería' ],
            [ 'id' => 31, 'municipality_id' => 11, 'parish'=> 'El Morro' ],
            [ 'id' => 32, 'municipality_id' => 12, 'parish'=> 'Puerto Píritu' ],
            [ 'id' => 33, 'municipality_id' => 12, 'parish'=> 'San Miguel' ],
            [ 'id' => 34, 'municipality_id' => 12, 'parish'=> 'Sucre' ],
            [ 'id' => 35, 'municipality_id' => 13, 'parish'=> 'Valle de Guanape' ],
            [ 'id' => 36, 'municipality_id' => 13, 'parish'=> 'Santa Bárbara' ],
            [ 'id' => 37, 'municipality_id' => 14, 'parish'=> 'El Chaparro' ],
            [ 'id' => 38, 'municipality_id' => 14, 'parish'=> 'Tomás Alfaro' ],
            [ 'id' => 39, 'municipality_id' => 14, 'parish'=> 'Calatrava' ],
            [ 'id' => 40, 'municipality_id' => 15, 'parish'=> 'Guanta' ],
            [ 'id' => 41, 'municipality_id' => 15, 'parish'=> 'Chorrerón' ],
            [ 'id' => 42, 'municipality_id' => 16, 'parish'=> 'Mamo' ],
            [ 'id' => 43, 'municipality_id' => 16, 'parish'=> 'Soledad' ],
            [ 'id' => 44, 'municipality_id' => 17, 'parish'=> 'Mapire' ],
            [ 'id' => 45, 'municipality_id' => 17, 'parish'=> 'Piar' ],
            [ 'id' => 46, 'municipality_id' => 17, 'parish'=> 'Santa Clara' ],
            [ 'id' => 47, 'municipality_id' => 17, 'parish'=> 'San Diego de Cabrutica' ],
            [ 'id' => 48, 'municipality_id' => 17, 'parish'=> 'Uverito' ],
            [ 'id' => 49, 'municipality_id' => 17, 'parish'=> 'Zuata' ],
            [ 'id' => 50, 'municipality_id' => 18, 'parish'=> 'Puerto La Cruz' ],
            [ 'id' => 51, 'municipality_id' => 18, 'parish'=> 'Pozuelos' ],
            [ 'id' => 52, 'municipality_id' => 19, 'parish'=> 'Onoto' ],
            [ 'id' => 53, 'municipality_id' => 19, 'parish'=> 'San Pablo' ],
            [ 'id' => 54, 'municipality_id' => 20, 'parish'=> 'San Mateo' ],
            [ 'id' => 55, 'municipality_id' => 20, 'parish'=> 'El Carito' ],
            [ 'id' => 56, 'municipality_id' => 20, 'parish'=> 'Santa Inés' ],
            [ 'id' => 57, 'municipality_id' => 20, 'parish'=> 'La Romereña' ],
            [ 'id' => 58, 'municipality_id' => 21, 'parish'=> 'Atapirire' ],
            [ 'id' => 59, 'municipality_id' => 21, 'parish'=> 'Boca del Pao' ],
            [ 'id' => 60, 'municipality_id' => 21, 'parish'=> 'El Pao' ],
            [ 'id' => 61, 'municipality_id' => 21, 'parish'=> 'Pariaguán' ],
            [ 'id' => 62, 'municipality_id' => 22, 'parish'=> 'Cantaura' ],
            [ 'id' => 63, 'municipality_id' => 22, 'parish'=> 'Libertador' ],
            [ 'id' => 64, 'municipality_id' => 22, 'parish'=> 'Santa Rosa' ],
            [ 'id' => 65, 'municipality_id' => 22, 'parish'=> 'Urica' ],
            [ 'id' => 66, 'municipality_id' => 23, 'parish'=> 'Píritu' ],
            [ 'id' => 67, 'municipality_id' => 23, 'parish'=> 'San Francisco' ],
            [ 'id' => 68, 'municipality_id' => 24, 'parish'=> 'San José de Guanipa' ],
            [ 'id' => 69, 'municipality_id' => 25, 'parish'=> 'Boca de Uchire' ],
            [ 'id' => 70, 'municipality_id' => 25, 'parish'=> 'Boca de Chávez' ],
            [ 'id' => 71, 'municipality_id' => 26, 'parish'=> 'Pueblo Nuevo' ],
            [ 'id' => 72, 'municipality_id' => 26, 'parish'=> 'Santa Ana' ],
            [ 'id' => 73, 'municipality_id' => 27, 'parish'=> 'Bergatín' ],
            [ 'id' => 74, 'municipality_id' => 27, 'parish'=> 'Caigua' ],
            [ 'id' => 75, 'municipality_id' => 27, 'parish'=> 'El Carmen' ],
            [ 'id' => 76, 'municipality_id' => 27, 'parish'=> 'El Pilar' ],
            [ 'id' => 77, 'municipality_id' => 27, 'parish'=> 'Naricual' ],
            [ 'id' => 78, 'municipality_id' => 27, 'parish'=> 'San Crsitóbal' ],
            [ 'id' => 79, 'municipality_id' => 28, 'parish'=> 'Edmundo Barrios' ],
            [ 'id' => 80, 'municipality_id' => 28, 'parish'=> 'Miguel Otero Silva' ],
            [ 'id' => 81, 'municipality_id' => 29, 'parish'=> 'Achaguas' ],
            [ 'id' => 82, 'municipality_id' => 29, 'parish'=> 'Apurito' ],
            [ 'id' => 83, 'municipality_id' => 29, 'parish'=> 'El Yagual' ],
            [ 'id' => 84, 'municipality_id' => 29, 'parish'=> 'Guachara' ],
            [ 'id' => 85, 'municipality_id' => 29, 'parish'=> 'Mucuritas' ],
            [ 'id' => 86, 'municipality_id' => 29, 'parish'=> 'Queseras del medio' ],
            [ 'id' => 87, 'municipality_id' => 30, 'parish'=> 'Biruaca' ],
            [ 'id' => 88, 'municipality_id' => 31, 'parish'=> 'Bruzual' ],
            [ 'id' => 89, 'municipality_id' => 31, 'parish'=> 'Mantecal' ],
            [ 'id' => 90, 'municipality_id' => 31, 'parish'=> 'Quintero' ],
            [ 'id' => 91, 'municipality_id' => 31, 'parish'=> 'Rincón Hondo' ],
            [ 'id' => 92, 'municipality_id' => 31, 'parish'=> 'San Vicente' ],
            [ 'id' => 93, 'municipality_id' => 32, 'parish'=> 'Guasdualito' ],
            [ 'id' => 94, 'municipality_id' => 32, 'parish'=> 'Aramendi' ],
            [ 'id' => 95, 'municipality_id' => 32, 'parish'=> 'El Amparo' ],
            [ 'id' => 96, 'municipality_id' => 32, 'parish'=> 'San Camilo' ],
            [ 'id' => 97, 'municipality_id' => 32, 'parish'=> 'Urdaneta' ],
            [ 'id' => 98, 'municipality_id' => 33, 'parish'=> 'San Juan de Payara' ],
            [ 'id' => 99, 'municipality_id' => 33, 'parish'=> 'Codazzi' ],
            [ 'id' => 100, 'municipality_id' => 33, 'parish'=> 'Cunaviche' ],
            [ 'id' => 101, 'municipality_id' => 34, 'parish'=> 'Elorza' ],
            [ 'id' => 102, 'municipality_id' => 34, 'parish'=> 'La Trinidad' ],
            [ 'id' => 103, 'municipality_id' => 35, 'parish'=> 'San Fernando' ],
            [ 'id' => 104, 'municipality_id' => 35, 'parish'=> 'El Recreo' ],
            [ 'id' => 105, 'municipality_id' => 35, 'parish'=> 'Peñalver' ],
            [ 'id' => 106, 'municipality_id' => 35, 'parish'=> 'San Rafael de Atamaica' ],
            [ 'id' => 107, 'municipality_id' => 36, 'parish'=> 'Pedro José Ovalles' ],
            [ 'id' => 108, 'municipality_id' => 36, 'parish'=> 'Joaquín Crespo' ],
            [ 'id' => 109, 'municipality_id' => 36, 'parish'=> 'José Casanova Godoy' ],
            [ 'id' => 110, 'municipality_id' => 36, 'parish'=> 'Madre María de San José' ],
            [ 'id' => 111, 'municipality_id' => 36, 'parish'=> 'Andrés Eloy Blanco' ],
            [ 'id' => 112, 'municipality_id' => 36, 'parish'=> 'Los Tacarigua' ],
            [ 'id' => 113, 'municipality_id' => 36, 'parish'=> 'Las Delicias' ],
            [ 'id' => 114, 'municipality_id' => 36, 'parish'=> 'Choroní' ],
            [ 'id' => 115, 'municipality_id' => 37, 'parish'=> 'Bolívar' ],
            [ 'id' => 116, 'municipality_id' => 38, 'parish'=> 'Camatagua' ],
            [ 'id' => 117, 'municipality_id' => 38, 'parish'=> 'Carmen de Cura' ],
            [ 'id' => 118, 'municipality_id' => 39, 'parish'=> 'Santa Rita' ],
            [ 'id' => 119, 'municipality_id' => 39, 'parish'=> 'Francisco de Miranda' ],
            [ 'id' => 120, 'municipality_id' => 39, 'parish'=> 'Moseñor Feliciano González' ],
            [ 'id' => 121, 'municipality_id' => 40, 'parish'=> 'Santa Cruz' ],
            [ 'id' => 122, 'municipality_id' => 41, 'parish'=> 'José Félix Ribas' ],
            [ 'id' => 123, 'municipality_id' => 41, 'parish'=> 'Castor Nieves Ríos' ],
            [ 'id' => 124, 'municipality_id' => 41, 'parish'=> 'Las Guacamayas' ],
            [ 'id' => 125, 'municipality_id' => 41, 'parish'=> 'Pao de Zárate' ],
            [ 'id' => 126, 'municipality_id' => 41, 'parish'=> 'Zuata' ],
            [ 'id' => 127, 'municipality_id' => 42, 'parish'=> 'José Rafael Revenga' ],
            [ 'id' => 128, 'municipality_id' => 43, 'parish'=> 'Palo Negro' ],
            [ 'id' => 129, 'municipality_id' => 43, 'parish'=> 'San Martín de Porres' ],
            [ 'id' => 130, 'municipality_id' => 44, 'parish'=> 'El Limón' ],
            [ 'id' => 131, 'municipality_id' => 44, 'parish'=> 'Caña de Azúcar' ],
            [ 'id' => 132, 'municipality_id' => 45, 'parish'=> 'Ocumare de la Costa' ],
            [ 'id' => 133, 'municipality_id' => 46, 'parish'=> 'San Casimiro' ],
            [ 'id' => 134, 'municipality_id' => 46, 'parish'=> 'Güiripa' ],
            [ 'id' => 135, 'municipality_id' => 46, 'parish'=> 'Ollas de Caramacate' ],
            [ 'id' => 136, 'municipality_id' => 46, 'parish'=> 'Valle Morín' ],
            [ 'id' => 137, 'municipality_id' => 47, 'parish'=> 'San Sebastían' ],
            [ 'id' => 138, 'municipality_id' => 48, 'parish'=> 'Turmero' ],
            [ 'id' => 139, 'municipality_id' => 48, 'parish'=> 'Arevalo Aponte' ],
            [ 'id' => 140, 'municipality_id' => 48, 'parish'=> 'Chuao' ],
            [ 'id' => 141, 'municipality_id' => 48, 'parish'=> 'Samán de Güere' ],
            [ 'id' => 142, 'municipality_id' => 48, 'parish'=> 'Alfredo Pacheco Miranda' ],
            [ 'id' => 143, 'municipality_id' => 49, 'parish'=> 'Santos Michelena' ],
            [ 'id' => 144, 'municipality_id' => 49, 'parish'=> 'Tiara' ],
            [ 'id' => 145, 'municipality_id' => 50, 'parish'=> 'Cagua' ],
            [ 'id' => 146, 'municipality_id' => 50, 'parish'=> 'Bella Vista' ],
            [ 'id' => 147, 'municipality_id' => 51, 'parish'=> 'Tovar' ],
            [ 'id' => 148, 'municipality_id' => 52, 'parish'=> 'Urdaneta' ],
            [ 'id' => 149, 'municipality_id' => 52, 'parish'=> 'Las Peñitas' ],
            [ 'id' => 150, 'municipality_id' => 52, 'parish'=> 'San Francisco de Cara' ],
            [ 'id' => 151, 'municipality_id' => 52, 'parish'=> 'Taguay' ],
            [ 'id' => 152, 'municipality_id' => 53, 'parish'=> 'Zamora' ],
            [ 'id' => 153, 'municipality_id' => 53, 'parish'=> 'Magdaleno' ],
            [ 'id' => 154, 'municipality_id' => 53, 'parish'=> 'San Francisco de Asís' ],
            [ 'id' => 155, 'municipality_id' => 53, 'parish'=> 'Valles de Tucutunemo' ],
            [ 'id' => 156, 'municipality_id' => 53, 'parish'=> 'Augusto Mijares' ],
            [ 'id' => 157, 'municipality_id' => 54, 'parish'=> 'Sabaneta' ],
            [ 'id' => 158, 'municipality_id' => 54, 'parish'=> 'Juan Antonio Rodríguez Domínguez' ],
            [ 'id' => 159, 'municipality_id' => 55, 'parish'=> 'El Cantón' ],
            [ 'id' => 160, 'municipality_id' => 55, 'parish'=> 'Santa Cruz de Guacas' ],
            [ 'id' => 161, 'municipality_id' => 55, 'parish'=> 'Puerto Vivas' ],
            [ 'id' => 162, 'municipality_id' => 56, 'parish'=> 'Ticoporo' ],
            [ 'id' => 163, 'municipality_id' => 56, 'parish'=> 'Nicolás Pulido' ],
            [ 'id' => 164, 'municipality_id' => 56, 'parish'=> 'Andrés Bello' ],
            [ 'id' => 165, 'municipality_id' => 57, 'parish'=> 'Arismendi' ],
            [ 'id' => 166, 'municipality_id' => 57, 'parish'=> 'Guadarrama' ],
            [ 'id' => 167, 'municipality_id' => 57, 'parish'=> 'La Unión' ],
            [ 'id' => 168, 'municipality_id' => 57, 'parish'=> 'San Antonio' ],
            [ 'id' => 169, 'municipality_id' => 58, 'parish'=> 'Barinas' ],
            [ 'id' => 170, 'municipality_id' => 58, 'parish'=> 'Alberto Arvelo Larriva' ],
            [ 'id' => 171, 'municipality_id' => 58, 'parish'=> 'San Silvestre' ],
            [ 'id' => 172, 'municipality_id' => 58, 'parish'=> 'Santa Inés' ],
            [ 'id' => 173, 'municipality_id' => 58, 'parish'=> 'Santa Lucía' ],
            [ 'id' => 174, 'municipality_id' => 58, 'parish'=> 'Torumos' ],
            [ 'id' => 175, 'municipality_id' => 58, 'parish'=> 'El Carmen' ],
            [ 'id' => 176, 'municipality_id' => 58, 'parish'=> 'Rómulo Betancourt' ],
            [ 'id' => 177, 'municipality_id' => 58, 'parish'=> 'Corazón de Jesús' ],
            [ 'id' => 178, 'municipality_id' => 58, 'parish'=> 'Ramón Ignacio Méndez' ],
            [ 'id' => 179, 'municipality_id' => 58, 'parish'=> 'Alto Barinas' ],
            [ 'id' => 180, 'municipality_id' => 58, 'parish'=> 'Manuel Palacio Fajardo' ],
            [ 'id' => 181, 'municipality_id' => 58, 'parish'=> 'Juan Antonio Rodríguez Domínguez' ],
            [ 'id' => 182, 'municipality_id' => 58, 'parish'=> 'Dominga Ortiz de Páez' ],
            [ 'id' => 183, 'municipality_id' => 59, 'parish'=> 'Barinitas' ],
            [ 'id' => 184, 'municipality_id' => 59, 'parish'=> 'Altamira de Cáceres' ],
            [ 'id' => 185, 'municipality_id' => 59, 'parish'=> 'Calderas' ],
            [ 'id' => 186, 'municipality_id' => 60, 'parish'=> 'Barrancas' ],
            [ 'id' => 187, 'municipality_id' => 60, 'parish'=> 'El Socorro' ],
            [ 'id' => 188, 'municipality_id' => 60, 'parish'=> 'Mazparrito' ],
            [ 'id' => 189, 'municipality_id' => 61, 'parish'=> 'Santa Bárbara' ],
            [ 'id' => 190, 'municipality_id' => 61, 'parish'=> 'Pedro Briceño Méndez' ],
            [ 'id' => 191, 'municipality_id' => 61, 'parish'=> 'Ramón Ignacio Méndez' ],
            [ 'id' => 192, 'municipality_id' => 61, 'parish'=> 'José Ignacio del Pumar' ],
            [ 'id' => 193, 'municipality_id' => 62, 'parish'=> 'Obispos' ],
            [ 'id' => 194, 'municipality_id' => 62, 'parish'=> 'Guasimitos' ],
            [ 'id' => 195, 'municipality_id' => 62, 'parish'=> 'El Real' ],
            [ 'id' => 196, 'municipality_id' => 62, 'parish'=> 'La Luz' ],
            [ 'id' => 197, 'municipality_id' => 63, 'parish'=> 'City Bolívia' ],
            [ 'id' => 198, 'municipality_id' => 63, 'parish'=> 'José Ignacio Briceño' ],
            [ 'id' => 199, 'municipality_id' => 63, 'parish'=> 'José Félix Ribas' ],
            [ 'id' => 200, 'municipality_id' => 63, 'parish'=> 'Páez' ],
            [ 'id' => 201, 'municipality_id' => 64, 'parish'=> 'Libertad' ],
            [ 'id' => 202, 'municipality_id' => 64, 'parish'=> 'Dolores' ],
            [ 'id' => 203, 'municipality_id' => 64, 'parish'=> 'Santa Rosa' ],
            [ 'id' => 204, 'municipality_id' => 64, 'parish'=> 'Palacio Fajardo' ],
            [ 'id' => 205, 'municipality_id' => 65, 'parish'=> 'City de Nutrias' ],
            [ 'id' => 206, 'municipality_id' => 65, 'parish'=> 'El Regalo' ],
            [ 'id' => 207, 'municipality_id' => 65, 'parish'=> 'Puerto Nutrias' ],
            [ 'id' => 208, 'municipality_id' => 65, 'parish'=> 'Santa Catalina' ],
            [ 'id' => 209, 'municipality_id' => 66, 'parish'=> 'Cachamay' ],
            [ 'id' => 210, 'municipality_id' => 66, 'parish'=> 'Chirica' ],
            [ 'id' => 211, 'municipality_id' => 66, 'parish'=> 'Dalla Costa' ],
            [ 'id' => 212, 'municipality_id' => 66, 'parish'=> 'Once de Abril' ],
            [ 'id' => 213, 'municipality_id' => 66, 'parish'=> 'Simón Bolívar' ],
            [ 'id' => 214, 'municipality_id' => 66, 'parish'=> 'Unare' ],
            [ 'id' => 215, 'municipality_id' => 66, 'parish'=> 'Universidad' ],
            [ 'id' => 216, 'municipality_id' => 66, 'parish'=> 'Vista al Sol' ],
            [ 'id' => 217, 'municipality_id' => 66, 'parish'=> 'Pozo Verde' ],
            [ 'id' => 218, 'municipality_id' => 66, 'parish'=> 'Yocoima' ],
            [ 'id' => 219, 'municipality_id' => 66, 'parish'=> '5 de Julio' ],
            [ 'id' => 220, 'municipality_id' => 67, 'parish'=> 'Cedeño' ],
            [ 'id' => 221, 'municipality_id' => 67, 'parish'=> 'Altagracia' ],
            [ 'id' => 222, 'municipality_id' => 67, 'parish'=> 'Ascensión Farreras' ],
            [ 'id' => 223, 'municipality_id' => 67, 'parish'=> 'Guaniamo' ],
            [ 'id' => 224, 'municipality_id' => 67, 'parish'=> 'La Urbana' ],
            [ 'id' => 225, 'municipality_id' => 67, 'parish'=> 'Pijiguaos' ],
            [ 'id' => 226, 'municipality_id' => 68, 'parish'=> 'El Callao' ],
            [ 'id' => 227, 'municipality_id' => 69, 'parish'=> 'Gran Sabana' ],
            [ 'id' => 228, 'municipality_id' => 69, 'parish'=> 'Ikabarú' ],
            [ 'id' => 229, 'municipality_id' => 70, 'parish'=> 'Catedral' ],
            [ 'id' => 230, 'municipality_id' => 70, 'parish'=> 'Zea' ],
            [ 'id' => 231, 'municipality_id' => 70, 'parish'=> 'Orinoco' ],
            [ 'id' => 232, 'municipality_id' => 70, 'parish'=> 'José Antonio Páez' ],
            [ 'id' => 233, 'municipality_id' => 70, 'parish'=> 'Marhuanta' ],
            [ 'id' => 234, 'municipality_id' => 70, 'parish'=> 'Agua Salada' ],
            [ 'id' => 235, 'municipality_id' => 70, 'parish'=> 'Vista Hermosa' ],
            [ 'id' => 236, 'municipality_id' => 70, 'parish'=> 'La Sabanita' ],
            [ 'id' => 237, 'municipality_id' => 70, 'parish'=> 'Panapana' ],
            [ 'id' => 238, 'municipality_id' => 71, 'parish'=> 'Andrés Eloy Blanco' ],
            [ 'id' => 239, 'municipality_id' => 71, 'parish'=> 'Pedro Cova' ],
            [ 'id' => 240, 'municipality_id' => 72, 'parish'=> 'Raúl Leoni' ],
            [ 'id' => 241, 'municipality_id' => 72, 'parish'=> 'Barceloneta' ],
            [ 'id' => 242, 'municipality_id' => 72, 'parish'=> 'Santa Bárbara' ],
            [ 'id' => 243, 'municipality_id' => 72, 'parish'=> 'San Francisco' ],
            [ 'id' => 244, 'municipality_id' => 73, 'parish'=> 'Roscio' ],
            [ 'id' => 245, 'municipality_id' => 73, 'parish'=> 'Salóm' ],
            [ 'id' => 246, 'municipality_id' => 74, 'parish'=> 'Sifontes' ],
            [ 'id' => 247, 'municipality_id' => 74, 'parish'=> 'Dalla Costa' ],
            [ 'id' => 248, 'municipality_id' => 74, 'parish'=> 'San Isidro' ],
            [ 'id' => 249, 'municipality_id' => 75, 'parish'=> 'Sucre' ],
            [ 'id' => 250, 'municipality_id' => 75, 'parish'=> 'Aripao' ],
            [ 'id' => 251, 'municipality_id' => 75, 'parish'=> 'Guarataro' ],
            [ 'id' => 252, 'municipality_id' => 75, 'parish'=> 'Las Majadas' ],
            [ 'id' => 253, 'municipality_id' => 75, 'parish'=> 'Moitaco' ],
            [ 'id' => 254, 'municipality_id' => 76, 'parish'=> 'Padre Pedro Chien' ],
            [ 'id' => 255, 'municipality_id' => 76, 'parish'=> 'Río Grande' ],
            [ 'id' => 256, 'municipality_id' => 77, 'parish'=> 'Bejuma' ],
            [ 'id' => 257, 'municipality_id' => 77, 'parish'=> 'Canoabo' ],
            [ 'id' => 258, 'municipality_id' => 77, 'parish'=> 'Simón Bolívar' ],
            [ 'id' => 259, 'municipality_id' => 78, 'parish'=> 'Güigüe' ],
            [ 'id' => 260, 'municipality_id' => 78, 'parish'=> 'Carabobo' ],
            [ 'id' => 261, 'municipality_id' => 78, 'parish'=> 'Tacarigua' ],
            [ 'id' => 262, 'municipality_id' => 79, 'parish'=> 'Mariara' ],
            [ 'id' => 263, 'municipality_id' => 79, 'parish'=> 'Aguas Calientes' ],
            [ 'id' => 264, 'municipality_id' => 80, 'parish'=> 'City Alianza' ],
            [ 'id' => 265, 'municipality_id' => 80, 'parish'=> 'Guacara' ],
            [ 'id' => 266, 'municipality_id' => 80, 'parish'=> 'Yagua' ],
            [ 'id' => 267, 'municipality_id' => 81, 'parish'=> 'Morón' ],
            [ 'id' => 268, 'municipality_id' => 81, 'parish'=> 'Yagua' ],
            [ 'id' => 269, 'municipality_id' => 82, 'parish'=> 'Tocuyito' ],
            [ 'id' => 270, 'municipality_id' => 82, 'parish'=> 'Independencia' ],
            [ 'id' => 271, 'municipality_id' => 83, 'parish'=> 'Los Guayos' ],
            [ 'id' => 272, 'municipality_id' => 84, 'parish'=> 'Miranda' ],
            [ 'id' => 273, 'municipality_id' => 85, 'parish'=> 'Montalbán' ],
            [ 'id' => 274, 'municipality_id' => 86, 'parish'=> 'Naguanagua' ],
            [ 'id' => 275, 'municipality_id' => 87, 'parish'=> 'Bartolomé Salóm' ],
            [ 'id' => 276, 'municipality_id' => 87, 'parish'=> 'Democracia' ],
            [ 'id' => 277, 'municipality_id' => 87, 'parish'=> 'Fraternidad' ],
            [ 'id' => 278, 'municipality_id' => 87, 'parish'=> 'Goaigoaza' ],
            [ 'id' => 279, 'municipality_id' => 87, 'parish'=> 'Juan José Flores' ],
            [ 'id' => 280, 'municipality_id' => 87, 'parish'=> 'Unión' ],
            [ 'id' => 281, 'municipality_id' => 87, 'parish'=> 'Borburata' ],
            [ 'id' => 282, 'municipality_id' => 87, 'parish'=> 'Patanemo' ],
            [ 'id' => 283, 'municipality_id' => 88, 'parish'=> 'San Diego' ],
            [ 'id' => 284, 'municipality_id' => 89, 'parish'=> 'San Joaquín' ],
            [ 'id' => 285, 'municipality_id' => 90, 'parish'=> 'Candelaria' ],
            [ 'id' => 286, 'municipality_id' => 90, 'parish'=> 'Catedral' ],
            [ 'id' => 287, 'municipality_id' => 90, 'parish'=> 'El Socorro' ],
            [ 'id' => 288, 'municipality_id' => 90, 'parish'=> 'Miguel Peña' ],
            [ 'id' => 289, 'municipality_id' => 90, 'parish'=> 'Rafael Urdaneta' ],
            [ 'id' => 290, 'municipality_id' => 90, 'parish'=> 'San Blas' ],
            [ 'id' => 291, 'municipality_id' => 90, 'parish'=> 'San José' ],
            [ 'id' => 292, 'municipality_id' => 90, 'parish'=> 'Santa Rosa' ],
            [ 'id' => 293, 'municipality_id' => 90, 'parish'=> 'Negro Primero' ],
            [ 'id' => 294, 'municipality_id' => 91, 'parish'=> 'Cojedes' ],
            [ 'id' => 295, 'municipality_id' => 91, 'parish'=> 'Juan de Mata Suárez' ],
            [ 'id' => 296, 'municipality_id' => 92, 'parish'=> 'Tinaquillo' ],
            [ 'id' => 297, 'municipality_id' => 93, 'parish'=> 'El Baúl' ],
            [ 'id' => 298, 'municipality_id' => 93, 'parish'=> 'Sucre' ],
            [ 'id' => 299, 'municipality_id' => 94, 'parish'=> 'La Aguadita' ],
            [ 'id' => 300, 'municipality_id' => 94, 'parish'=> 'Macapo' ],
            [ 'id' => 301, 'municipality_id' => 95, 'parish'=> 'El Pao' ],
            [ 'id' => 302, 'municipality_id' => 96, 'parish'=> 'El Amparo' ],
            [ 'id' => 303, 'municipality_id' => 96, 'parish'=> 'Libertad de Cojedes' ],
            [ 'id' => 304, 'municipality_id' => 97, 'parish'=> 'Rómulo Gallegos' ],
            [ 'id' => 305, 'municipality_id' => 98, 'parish'=> 'San Carlos de Austria' ],
            [ 'id' => 306, 'municipality_id' => 98, 'parish'=> 'Juan Ángel Bravo' ],
            [ 'id' => 307, 'municipality_id' => 98, 'parish'=> 'Manuel Manrique' ],
            [ 'id' => 308, 'municipality_id' => 99, 'parish'=> 'General en Jefe José Laurencio Silva' ],
            [ 'id' => 309, 'municipality_id' => 100, 'parish'=> 'Curiapo' ],
            [ 'id' => 310, 'municipality_id' => 100, 'parish'=> 'Almirante Luis Brión' ],
            [ 'id' => 311, 'municipality_id' => 100, 'parish'=> 'Francisco Aniceto Lugo' ],
            [ 'id' => 312, 'municipality_id' => 100, 'parish'=> 'Manuel Renaud' ],
            [ 'id' => 313, 'municipality_id' => 100, 'parish'=> 'Padre Barral' ],
            [ 'id' => 314, 'municipality_id' => 100, 'parish'=> 'Santos de Abelgas' ],
            [ 'id' => 315, 'municipality_id' => 101, 'parish'=> 'Imataca' ],
            [ 'id' => 316, 'municipality_id' => 101, 'parish'=> 'Cinco de Julio' ],
            [ 'id' => 317, 'municipality_id' => 101, 'parish'=> 'Juan Bautista Arismendi' ],
            [ 'id' => 318, 'municipality_id' => 101, 'parish'=> 'Manuel Piar' ],
            [ 'id' => 319, 'municipality_id' => 101, 'parish'=> 'Rómulo Gallegos' ],
            [ 'id' => 320, 'municipality_id' => 102, 'parish'=> 'Pedernales' ],
            [ 'id' => 321, 'municipality_id' => 102, 'parish'=> 'Luis Beltrán Prieto Figueroa' ],
            [ 'id' => 322, 'municipality_id' => 103, 'parish'=> 'San José (Delta Amacuro)' ],
            [ 'id' => 323, 'municipality_id' => 103, 'parish'=> 'José Vidal Marcano' ],
            [ 'id' => 324, 'municipality_id' => 103, 'parish'=> 'Juan Millán' ],
            [ 'id' => 325, 'municipality_id' => 103, 'parish'=> 'Leonardo Ruíz Pineda' ],
            [ 'id' => 326, 'municipality_id' => 103, 'parish'=> 'Mariscal Antonio José de Sucre' ],
            [ 'id' => 327, 'municipality_id' => 103, 'parish'=> 'Monseñor Argimiro García' ],
            [ 'id' => 328, 'municipality_id' => 103, 'parish'=> 'San Rafael (Delta Amacuro)' ],
            [ 'id' => 329, 'municipality_id' => 103, 'parish'=> 'Virgen del Valle' ],
            [ 'id' => 330, 'municipality_id' => 10, 'parish'=> 'Clarines' ],
            [ 'id' => 331, 'municipality_id' => 10, 'parish'=> 'Guanape' ],
            [ 'id' => 332, 'municipality_id' => 10, 'parish'=> 'Sabana de Uchire' ],
            [ 'id' => 333, 'municipality_id' => 104, 'parish'=> 'Capadare' ],
            [ 'id' => 334, 'municipality_id' => 104, 'parish'=> 'La Pastora' ],
            [ 'id' => 335, 'municipality_id' => 104, 'parish'=> 'Libertador' ],
            [ 'id' => 336, 'municipality_id' => 104, 'parish'=> 'San Juan de los Cayos' ],
            [ 'id' => 337, 'municipality_id' => 105, 'parish'=> 'Aracua' ],
            [ 'id' => 338, 'municipality_id' => 105, 'parish'=> 'La Peña' ],
            [ 'id' => 339, 'municipality_id' => 105, 'parish'=> 'San Luis' ],
            [ 'id' => 340, 'municipality_id' => 106, 'parish'=> 'Bariro' ],
            [ 'id' => 341, 'municipality_id' => 106, 'parish'=> 'Borojó' ],
            [ 'id' => 342, 'municipality_id' => 106, 'parish'=> 'Capatárida' ],
            [ 'id' => 343, 'municipality_id' => 106, 'parish'=> 'Guajiro' ],
            [ 'id' => 344, 'municipality_id' => 106, 'parish'=> 'Seque' ],
            [ 'id' => 345, 'municipality_id' => 106, 'parish'=> 'Zazárida' ],
            [ 'id' => 346, 'municipality_id' => 106, 'parish'=> 'Valle de Eroa' ],
            [ 'id' => 347, 'municipality_id' => 107, 'parish'=> 'Cacique Manaure' ],
            [ 'id' => 348, 'municipality_id' => 108, 'parish'=> 'Norte' ],
            [ 'id' => 349, 'municipality_id' => 108, 'parish'=> 'Carirubana' ],
            [ 'id' => 350, 'municipality_id' => 108, 'parish'=> 'Santa Ana' ],
            [ 'id' => 351, 'municipality_id' => 108, 'parish'=> 'Urbana Punta Cardón' ],
            [ 'id' => 352, 'municipality_id' => 109, 'parish'=> 'La Vela de Coro' ],
            [ 'id' => 353, 'municipality_id' => 109, 'parish'=> 'Acurigua' ],
            [ 'id' => 354, 'municipality_id' => 109, 'parish'=> 'Guaibacoa' ],
            [ 'id' => 355, 'municipality_id' => 109, 'parish'=> 'Las Calderas' ],
            [ 'id' => 356, 'municipality_id' => 109, 'parish'=> 'Macoruca' ],
            [ 'id' => 357, 'municipality_id' => 110, 'parish'=> 'Dabajuro' ],
            [ 'id' => 358, 'municipality_id' => 111, 'parish'=> 'Agua Clara' ],
            [ 'id' => 359, 'municipality_id' => 111, 'parish'=> 'Avaria' ],
            [ 'id' => 360, 'municipality_id' => 111, 'parish'=> 'Pedregal' ],
            [ 'id' => 361, 'municipality_id' => 111, 'parish'=> 'Piedra Grande' ],
            [ 'id' => 362, 'municipality_id' => 111, 'parish'=> 'Purureche' ],
            [ 'id' => 363, 'municipality_id' => 112, 'parish'=> 'Adaure' ],
            [ 'id' => 364, 'municipality_id' => 112, 'parish'=> 'Adícora' ],
            [ 'id' => 365, 'municipality_id' => 112, 'parish'=> 'Baraived' ],
            [ 'id' => 366, 'municipality_id' => 112, 'parish'=> 'Buena Vista' ],
            [ 'id' => 367, 'municipality_id' => 112, 'parish'=> 'Jadacaquiva' ],
            [ 'id' => 368, 'municipality_id' => 112, 'parish'=> 'El Vínculo' ],
            [ 'id' => 369, 'municipality_id' => 112, 'parish'=> 'El Hato' ],
            [ 'id' => 370, 'municipality_id' => 112, 'parish'=> 'Moruy' ],
            [ 'id' => 371, 'municipality_id' => 112, 'parish'=> 'Pueblo Nuevo' ],
            [ 'id' => 372, 'municipality_id' => 113, 'parish'=> 'Agua Larga' ],
            [ 'id' => 373, 'municipality_id' => 113, 'parish'=> 'El Paují' ],
            [ 'id' => 374, 'municipality_id' => 113, 'parish'=> 'Independencia' ],
            [ 'id' => 375, 'municipality_id' => 113, 'parish'=> 'Mapararí' ],
            [ 'id' => 376, 'municipality_id' => 114, 'parish'=> 'Agua Linda' ],
            [ 'id' => 377, 'municipality_id' => 114, 'parish'=> 'Araurima' ],
            [ 'id' => 378, 'municipality_id' => 114, 'parish'=> 'Jacura' ],
            [ 'id' => 379, 'municipality_id' => 115, 'parish'=> 'Tucacas' ],
            [ 'id' => 380, 'municipality_id' => 115, 'parish'=> 'Boca de Aroa' ],
            [ 'id' => 381, 'municipality_id' => 116, 'parish'=> 'Los Taques' ],
            [ 'id' => 382, 'municipality_id' => 116, 'parish'=> 'Judibana' ],
            [ 'id' => 383, 'municipality_id' => 117, 'parish'=> 'Mene de Mauroa' ],
            [ 'id' => 384, 'municipality_id' => 117, 'parish'=> 'San Félix' ],
            [ 'id' => 385, 'municipality_id' => 117, 'parish'=> 'Casigua' ],
            [ 'id' => 386, 'municipality_id' => 118, 'parish'=> 'Guzmán Guillermo' ],
            [ 'id' => 387, 'municipality_id' => 118, 'parish'=> 'Mitare' ],
            [ 'id' => 388, 'municipality_id' => 118, 'parish'=> 'Río Seco' ],
            [ 'id' => 389, 'municipality_id' => 118, 'parish'=> 'Sabaneta' ],
            [ 'id' => 390, 'municipality_id' => 118, 'parish'=> 'San Antonio' ],
            [ 'id' => 391, 'municipality_id' => 118, 'parish'=> 'San Gabriel' ],
            [ 'id' => 392, 'municipality_id' => 118, 'parish'=> 'Santa Ana' ],
            [ 'id' => 393, 'municipality_id' => 119, 'parish'=> 'Boca del Tocuyo' ],
            [ 'id' => 394, 'municipality_id' => 119, 'parish'=> 'Chichiriviche' ],
            [ 'id' => 395, 'municipality_id' => 119, 'parish'=> 'Tocuyo de la Costa' ],
            [ 'id' => 396, 'municipality_id' => 120, 'parish'=> 'Palmasola' ],
            [ 'id' => 397, 'municipality_id' => 121, 'parish'=> 'Cabure' ],
            [ 'id' => 398, 'municipality_id' => 121, 'parish'=> 'Colina' ],
            [ 'id' => 399, 'municipality_id' => 121, 'parish'=> 'Curimagua' ],
            [ 'id' => 400, 'municipality_id' => 122, 'parish'=> 'San José de la Costa' ],
            [ 'id' => 401, 'municipality_id' => 122, 'parish'=> 'Píritu' ],
            [ 'id' => 402, 'municipality_id' => 123, 'parish'=> 'San Francisco' ],
            [ 'id' => 403, 'municipality_id' => 124, 'parish'=> 'Sucre' ],
            [ 'id' => 404, 'municipality_id' => 124, 'parish'=> 'Pecaya' ],
            [ 'id' => 405, 'municipality_id' => 125, 'parish'=> 'Tocópero' ],
            [ 'id' => 406, 'municipality_id' => 126, 'parish'=> 'El Charal' ],
            [ 'id' => 407, 'municipality_id' => 126, 'parish'=> 'Las Vegas del Tuy' ],
            [ 'id' => 408, 'municipality_id' => 126, 'parish'=> 'Santa Cruz de Bucaral' ],
            [ 'id' => 409, 'municipality_id' => 127, 'parish'=> 'Bruzual' ],
            [ 'id' => 410, 'municipality_id' => 127, 'parish'=> 'Urumaco' ],
            [ 'id' => 411, 'municipality_id' => 128, 'parish'=> 'Puerto Cumarebo' ],
            [ 'id' => 412, 'municipality_id' => 128, 'parish'=> 'La Ciénaga' ],
            [ 'id' => 413, 'municipality_id' => 128, 'parish'=> 'La Soledad' ],
            [ 'id' => 414, 'municipality_id' => 128, 'parish'=> 'Pueblo Cumarebo' ],
            [ 'id' => 415, 'municipality_id' => 128, 'parish'=> 'Zazárida' ],
            [ 'id' => 416, 'municipality_id' => 113, 'parish'=> 'Churuguara' ],
            [ 'id' => 417, 'municipality_id' => 129, 'parish'=> 'Camaguán' ],
            [ 'id' => 418, 'municipality_id' => 129, 'parish'=> 'Puerto Miranda' ],
            [ 'id' => 419, 'municipality_id' => 129, 'parish'=> 'Uverito' ],
            [ 'id' => 420, 'municipality_id' => 130, 'parish'=> 'Chaguaramas' ],
            [ 'id' => 421, 'municipality_id' => 131, 'parish'=> 'El Socorro' ],
            [ 'id' => 422, 'municipality_id' => 132, 'parish'=> 'Tucupido' ],
            [ 'id' => 423, 'municipality_id' => 132, 'parish'=> 'San Rafael de Laya' ],
            [ 'id' => 424, 'municipality_id' => 133, 'parish'=> 'Altagracia de Orituco' ],
            [ 'id' => 425, 'municipality_id' => 133, 'parish'=> 'San Rafael de Orituco' ],
            [ 'id' => 426, 'municipality_id' => 133, 'parish'=> 'San Francisco Javier de Lezama' ],
            [ 'id' => 427, 'municipality_id' => 133, 'parish'=> 'Paso Real de Macaira' ],
            [ 'id' => 428, 'municipality_id' => 133, 'parish'=> 'Carlos Soublette' ],
            [ 'id' => 429, 'municipality_id' => 133, 'parish'=> 'San Francisco de Macaira' ],
            [ 'id' => 430, 'municipality_id' => 133, 'parish'=> 'Libertad de Orituco' ],
            [ 'id' => 431, 'municipality_id' => 134, 'parish'=> 'Cantaclaro' ],
            [ 'id' => 432, 'municipality_id' => 134, 'parish'=> 'San Juan de los Morros' ],
            [ 'id' => 433, 'municipality_id' => 134, 'parish'=> 'Parapara' ],
            [ 'id' => 434, 'municipality_id' => 135, 'parish'=> 'El Sombrero' ],
            [ 'id' => 435, 'municipality_id' => 135, 'parish'=> 'Sosa' ],
            [ 'id' => 436, 'municipality_id' => 136, 'parish'=> 'Las Mercedes' ],
            [ 'id' => 437, 'municipality_id' => 136, 'parish'=> 'Cabruta' ],
            [ 'id' => 438, 'municipality_id' => 136, 'parish'=> 'Santa Rita de Manapire' ],
            [ 'id' => 439, 'municipality_id' => 137, 'parish'=> 'Valle de la Pascua' ],
            [ 'id' => 440, 'municipality_id' => 137, 'parish'=> 'Espino' ],
            [ 'id' => 441, 'municipality_id' => 138, 'parish'=> 'San José de Unare' ],
            [ 'id' => 442, 'municipality_id' => 138, 'parish'=> 'Zaraza' ],
            [ 'id' => 443, 'municipality_id' => 139, 'parish'=> 'San José de Tiznados' ],
            [ 'id' => 444, 'municipality_id' => 139, 'parish'=> 'San Francisco de Tiznados' ],
            [ 'id' => 445, 'municipality_id' => 139, 'parish'=> 'San Lorenzo de Tiznados' ],
            [ 'id' => 446, 'municipality_id' => 139, 'parish'=> 'Ortiz' ],
            [ 'id' => 447, 'municipality_id' => 140, 'parish'=> 'Guayabal' ],
            [ 'id' => 448, 'municipality_id' => 140, 'parish'=> 'Cazorla' ],
            [ 'id' => 449, 'municipality_id' => 141, 'parish'=> 'San José de Guaribe' ],
            [ 'id' => 450, 'municipality_id' => 141, 'parish'=> 'Uveral' ],
            [ 'id' => 451, 'municipality_id' => 142, 'parish'=> 'Santa María de Ipire' ],
            [ 'id' => 452, 'municipality_id' => 142, 'parish'=> 'Altamira' ],
            [ 'id' => 453, 'municipality_id' => 143, 'parish'=> 'El Calvario' ],
            [ 'id' => 454, 'municipality_id' => 143, 'parish'=> 'El Rastro' ],
            [ 'id' => 455, 'municipality_id' => 143, 'parish'=> 'Guardatinajas' ],
            [ 'id' => 456, 'municipality_id' => 143, 'parish'=> 'Capital Urbana Calabozo' ],
            [ 'id' => 457, 'municipality_id' => 144, 'parish'=> 'Quebrada Honda de Guache' ],
            [ 'id' => 458, 'municipality_id' => 144, 'parish'=> 'Pío Tamayo' ],
            [ 'id' => 459, 'municipality_id' => 144, 'parish'=> 'Yacambú' ],
            [ 'id' => 460, 'municipality_id' => 145, 'parish'=> 'Fréitez' ],
            [ 'id' => 461, 'municipality_id' => 145, 'parish'=> 'José María Blanco' ],
            [ 'id' => 462, 'municipality_id' => 146, 'parish'=> 'Catedral' ],
            [ 'id' => 463, 'municipality_id' => 146, 'parish'=> 'Concepción' ],
            [ 'id' => 464, 'municipality_id' => 146, 'parish'=> 'El Cují' ],
            [ 'id' => 465, 'municipality_id' => 146, 'parish'=> 'Juan de Villegas' ],
            [ 'id' => 466, 'municipality_id' => 146, 'parish'=> 'Santa Rosa' ],
            [ 'id' => 467, 'municipality_id' => 146, 'parish'=> 'Tamaca' ],
            [ 'id' => 468, 'municipality_id' => 146, 'parish'=> 'Unión' ],
            [ 'id' => 469, 'municipality_id' => 146, 'parish'=> 'Aguedo Felipe Alvarado' ],
            [ 'id' => 470, 'municipality_id' => 146, 'parish'=> 'Buena Vista' ],
            [ 'id' => 471, 'municipality_id' => 146, 'parish'=> 'Juárez' ],
            [ 'id' => 472, 'municipality_id' => 147, 'parish'=> 'Juan Bautista Rodríguez' ],
            [ 'id' => 473, 'municipality_id' => 147, 'parish'=> 'Cuara' ],
            [ 'id' => 474, 'municipality_id' => 147, 'parish'=> 'Diego de Lozada' ],
            [ 'id' => 475, 'municipality_id' => 147, 'parish'=> 'Paraíso de San José' ],
            [ 'id' => 476, 'municipality_id' => 147, 'parish'=> 'San Miguel' ],
            [ 'id' => 477, 'municipality_id' => 147, 'parish'=> 'Tintorero' ],
            [ 'id' => 478, 'municipality_id' => 147, 'parish'=> 'José Bernardo Dorante' ],
            [ 'id' => 479, 'municipality_id' => 147, 'parish'=> 'Coronel Mariano Peraza ' ],
            [ 'id' => 480, 'municipality_id' => 148, 'parish'=> 'Bolívar' ],
            [ 'id' => 481, 'municipality_id' => 148, 'parish'=> 'Anzoátegui' ],
            [ 'id' => 482, 'municipality_id' => 148, 'parish'=> 'Guarico' ],
            [ 'id' => 483, 'municipality_id' => 148, 'parish'=> 'Hilario Luna y Luna' ],
            [ 'id' => 484, 'municipality_id' => 148, 'parish'=> 'Humocaro Alto' ],
            [ 'id' => 485, 'municipality_id' => 148, 'parish'=> 'Humocaro Bajo' ],
            [ 'id' => 486, 'municipality_id' => 148, 'parish'=> 'La Candelaria' ],
            [ 'id' => 487, 'municipality_id' => 148, 'parish'=> 'Morán' ],
            [ 'id' => 488, 'municipality_id' => 149, 'parish'=> 'Cabudare' ],
            [ 'id' => 489, 'municipality_id' => 149, 'parish'=> 'José Gregorio Bastidas' ],
            [ 'id' => 490, 'municipality_id' => 149, 'parish'=> 'Agua Viva' ],
            [ 'id' => 491, 'municipality_id' => 150, 'parish'=> 'Sarare' ],
            [ 'id' => 492, 'municipality_id' => 150, 'parish'=> 'Buría' ],
            [ 'id' => 493, 'municipality_id' => 150, 'parish'=> 'Gustavo Vegas León' ],
            [ 'id' => 494, 'municipality_id' => 151, 'parish'=> 'Trinidad Samuel' ],
            [ 'id' => 495, 'municipality_id' => 151, 'parish'=> 'Antonio Díaz' ],
            [ 'id' => 496, 'municipality_id' => 151, 'parish'=> 'Camacaro' ],
            [ 'id' => 497, 'municipality_id' => 151, 'parish'=> 'Castañeda' ],
            [ 'id' => 498, 'municipality_id' => 151, 'parish'=> 'Cecilio Zubillaga' ],
            [ 'id' => 499, 'municipality_id' => 151, 'parish'=> 'Chiquinquirá' ],
            [ 'id' => 500, 'municipality_id' => 151, 'parish'=> 'El Blanco' ],
            [ 'id' => 501, 'municipality_id' => 151, 'parish'=> 'Espinoza de los Monteros' ],
            [ 'id' => 502, 'municipality_id' => 151, 'parish'=> 'Lara' ],
            [ 'id' => 503, 'municipality_id' => 151, 'parish'=> 'Las Mercedes' ],
            [ 'id' => 504, 'municipality_id' => 151, 'parish'=> 'Manuel Morillo' ],
            [ 'id' => 505, 'municipality_id' => 151, 'parish'=> 'Montaña Verde' ],
            [ 'id' => 506, 'municipality_id' => 151, 'parish'=> 'Montes de Oca' ],
            [ 'id' => 507, 'municipality_id' => 151, 'parish'=> 'Torres' ],
            [ 'id' => 508, 'municipality_id' => 151, 'parish'=> 'Heriberto Arroyo' ],
            [ 'id' => 509, 'municipality_id' => 151, 'parish'=> 'Reyes Vargas' ],
            [ 'id' => 510, 'municipality_id' => 151, 'parish'=> 'Altagracia' ],
            [ 'id' => 511, 'municipality_id' => 152, 'parish'=> 'Siquisique' ],
            [ 'id' => 512, 'municipality_id' => 152, 'parish'=> 'Moroturo' ],
            [ 'id' => 513, 'municipality_id' => 152, 'parish'=> 'San Miguel' ],
            [ 'id' => 514, 'municipality_id' => 152, 'parish'=> 'Xaguas' ],
            [ 'id' => 515, 'municipality_id' => 179, 'parish'=> 'Presidente Betancourt' ],
            [ 'id' => 516, 'municipality_id' => 179, 'parish'=> 'Presidente Páez' ],
            [ 'id' => 517, 'municipality_id' => 179, 'parish'=> 'Presidente Rómulo Gallegos' ],
            [ 'id' => 518, 'municipality_id' => 179, 'parish'=> 'Gabriel Picón González' ],
            [ 'id' => 519, 'municipality_id' => 179, 'parish'=> 'Héctor Amable Mora' ],
            [ 'id' => 520, 'municipality_id' => 179, 'parish'=> 'José Nucete Sardi' ],
            [ 'id' => 521, 'municipality_id' => 179, 'parish'=> 'Pulido Méndez' ],
            [ 'id' => 522, 'municipality_id' => 180, 'parish'=> 'La Azulita' ],
            [ 'id' => 523, 'municipality_id' => 181, 'parish'=> 'Santa Cruz de Mora' ],
            [ 'id' => 524, 'municipality_id' => 181, 'parish'=> 'Mesa Bolívar' ],
            [ 'id' => 525, 'municipality_id' => 181, 'parish'=> 'Mesa de Las Palmas' ],
            [ 'id' => 526, 'municipality_id' => 182, 'parish'=> 'Aricagua' ],
            [ 'id' => 527, 'municipality_id' => 182, 'parish'=> 'San Antonio' ],
            [ 'id' => 528, 'municipality_id' => 183, 'parish'=> 'Canagua' ],
            [ 'id' => 529, 'municipality_id' => 183, 'parish'=> 'Capurí' ],
            [ 'id' => 530, 'municipality_id' => 183, 'parish'=> 'Chacantá' ],
            [ 'id' => 531, 'municipality_id' => 183, 'parish'=> 'El Molino' ],
            [ 'id' => 532, 'municipality_id' => 183, 'parish'=> 'Guaimaral' ],
            [ 'id' => 533, 'municipality_id' => 183, 'parish'=> 'Mucutuy' ],
            [ 'id' => 534, 'municipality_id' => 183, 'parish'=> 'Mucuchachí' ],
            [ 'id' => 535, 'municipality_id' => 184, 'parish'=> 'Fernández Peña' ],
            [ 'id' => 536, 'municipality_id' => 184, 'parish'=> 'Matriz' ],
            [ 'id' => 537, 'municipality_id' => 184, 'parish'=> 'Montalbán' ],
            [ 'id' => 538, 'municipality_id' => 184, 'parish'=> 'Acequias' ],
            [ 'id' => 539, 'municipality_id' => 184, 'parish'=> 'Jají' ],
            [ 'id' => 540, 'municipality_id' => 184, 'parish'=> 'La Mesa' ],
            [ 'id' => 541, 'municipality_id' => 184, 'parish'=> 'San José del Sur' ],
            [ 'id' => 542, 'municipality_id' => 185, 'parish'=> 'Tucaní' ],
            [ 'id' => 543, 'municipality_id' => 185, 'parish'=> 'Florencio Ramírez' ],
            [ 'id' => 544, 'municipality_id' => 186, 'parish'=> 'Santo Domingo' ],
            [ 'id' => 545, 'municipality_id' => 186, 'parish'=> 'Las Piedras' ],
            [ 'id' => 546, 'municipality_id' => 187, 'parish'=> 'Guaraque' ],
            [ 'id' => 547, 'municipality_id' => 187, 'parish'=> 'Mesa de Quintero' ],
            [ 'id' => 548, 'municipality_id' => 187, 'parish'=> 'Río Negro' ],
            [ 'id' => 549, 'municipality_id' => 188, 'parish'=> 'Arapuey' ],
            [ 'id' => 550, 'municipality_id' => 188, 'parish'=> 'Palmira' ],
            [ 'id' => 551, 'municipality_id' => 189, 'parish'=> 'San Cristóbal de Torondoy' ],
            [ 'id' => 552, 'municipality_id' => 189, 'parish'=> 'Torondoy' ],
            [ 'id' => 553, 'municipality_id' => 190, 'parish'=> 'Antonio Spinetti Dini' ],
            [ 'id' => 554, 'municipality_id' => 190, 'parish'=> 'Arias' ],
            [ 'id' => 555, 'municipality_id' => 190, 'parish'=> 'Caracciolo Parra Pérez' ],
            [ 'id' => 556, 'municipality_id' => 190, 'parish'=> 'Domingo Peña' ],
            [ 'id' => 557, 'municipality_id' => 190, 'parish'=> 'El Llano' ],
            [ 'id' => 558, 'municipality_id' => 190, 'parish'=> 'Gonzalo Picón Febres' ],
            [ 'id' => 559, 'municipality_id' => 190, 'parish'=> 'Jacinto Plaza' ],
            [ 'id' => 560, 'municipality_id' => 190, 'parish'=> 'Juan Rodríguez Suárez' ],
            [ 'id' => 561, 'municipality_id' => 190, 'parish'=> 'Lasso de la Vega' ],
            [ 'id' => 562, 'municipality_id' => 190, 'parish'=> 'Mariano Picón Salas' ],
            [ 'id' => 563, 'municipality_id' => 190, 'parish'=> 'Milla' ],
            [ 'id' => 564, 'municipality_id' => 190, 'parish'=> 'Osuna Rodríguez' ],
            [ 'id' => 565, 'municipality_id' => 190, 'parish'=> 'Sagrario' ],
            [ 'id' => 566, 'municipality_id' => 190, 'parish'=> 'El Morro' ],
            [ 'id' => 567, 'municipality_id' => 190, 'parish'=> 'Los Nevados' ],
            [ 'id' => 568, 'municipality_id' => 191, 'parish'=> 'Andrés Eloy Blanco' ],
            [ 'id' => 569, 'municipality_id' => 191, 'parish'=> 'La Venta' ],
            [ 'id' => 570, 'municipality_id' => 191, 'parish'=> 'Piñango' ],
            [ 'id' => 571, 'municipality_id' => 191, 'parish'=> 'Timotes' ],
            [ 'id' => 572, 'municipality_id' => 192, 'parish'=> 'Eloy Paredes' ],
            [ 'id' => 573, 'municipality_id' => 192, 'parish'=> 'San Rafael de Alcázar' ],
            [ 'id' => 574, 'municipality_id' => 192, 'parish'=> 'Santa Elena de Arenales' ],
            [ 'id' => 575, 'municipality_id' => 193, 'parish'=> 'Santa María de Caparo' ],
            [ 'id' => 576, 'municipality_id' => 194, 'parish'=> 'Pueblo Llano' ],
            [ 'id' => 577, 'municipality_id' => 195, 'parish'=> 'Cacute' ],
            [ 'id' => 578, 'municipality_id' => 195, 'parish'=> 'La Toma' ],
            [ 'id' => 579, 'municipality_id' => 195, 'parish'=> 'Mucuchíes' ],
            [ 'id' => 580, 'municipality_id' => 195, 'parish'=> 'Mucurubá' ],
            [ 'id' => 581, 'municipality_id' => 195, 'parish'=> 'San Rafael' ],
            [ 'id' => 582, 'municipality_id' => 196, 'parish'=> 'Gerónimo Maldonado' ],
            [ 'id' => 583, 'municipality_id' => 196, 'parish'=> 'Bailadores' ],
            [ 'id' => 584, 'municipality_id' => 197, 'parish'=> 'Tabay' ],
            [ 'id' => 585, 'municipality_id' => 198, 'parish'=> 'Chiguará' ],
            [ 'id' => 586, 'municipality_id' => 198, 'parish'=> 'Estánquez' ],
            [ 'id' => 587, 'municipality_id' => 198, 'parish'=> 'Lagunillas' ],
            [ 'id' => 588, 'municipality_id' => 198, 'parish'=> 'La Trampa' ],
            [ 'id' => 589, 'municipality_id' => 198, 'parish'=> 'Pueblo Nuevo del Sur' ],
            [ 'id' => 590, 'municipality_id' => 198, 'parish'=> 'San Juan' ],
            [ 'id' => 591, 'municipality_id' => 199, 'parish'=> 'El Amparo' ],
            [ 'id' => 592, 'municipality_id' => 199, 'parish'=> 'El Llano' ],
            [ 'id' => 593, 'municipality_id' => 199, 'parish'=> 'San Francisco' ],
            [ 'id' => 594, 'municipality_id' => 199, 'parish'=> 'Tovar' ],
            [ 'id' => 595, 'municipality_id' => 200, 'parish'=> 'Independencia' ],
            [ 'id' => 596, 'municipality_id' => 200, 'parish'=> 'María de la Concepción Palacios Blanco' ],
            [ 'id' => 597, 'municipality_id' => 200, 'parish'=> 'Nueva Bolivia' ],
            [ 'id' => 598, 'municipality_id' => 200, 'parish'=> 'Santa Apolonia' ],
            [ 'id' => 599, 'municipality_id' => 201, 'parish'=> 'Caño El Tigre' ],
            [ 'id' => 600, 'municipality_id' => 201, 'parish'=> 'Zea' ],
            [ 'id' => 601, 'municipality_id' => 223, 'parish'=> 'Aragüita' ],
            [ 'id' => 602, 'municipality_id' => 223, 'parish'=> 'Arévalo González' ],
            [ 'id' => 603, 'municipality_id' => 223, 'parish'=> 'Capaya' ],
            [ 'id' => 604, 'municipality_id' => 223, 'parish'=> 'Caucagua' ],
            [ 'id' => 605, 'municipality_id' => 223, 'parish'=> 'Panaquire' ],
            [ 'id' => 606, 'municipality_id' => 223, 'parish'=> 'Ribas' ],
            [ 'id' => 607, 'municipality_id' => 223, 'parish'=> 'El Café' ],
            [ 'id' => 608, 'municipality_id' => 223, 'parish'=> 'Marizapa' ],
            [ 'id' => 609, 'municipality_id' => 224, 'parish'=> 'Cumbo' ],
            [ 'id' => 610, 'municipality_id' => 224, 'parish'=> 'San José de Barlovento' ],
            [ 'id' => 611, 'municipality_id' => 225, 'parish'=> 'El Cafetal' ],
            [ 'id' => 612, 'municipality_id' => 225, 'parish'=> 'Las Minas' ],
            [ 'id' => 613, 'municipality_id' => 225, 'parish'=> 'Nuestra Señora del Rosario' ],
            [ 'id' => 614, 'municipality_id' => 226, 'parish'=> 'Higuerote' ],
            [ 'id' => 615, 'municipality_id' => 226, 'parish'=> 'Curiepe' ],
            [ 'id' => 616, 'municipality_id' => 226, 'parish'=> 'Tacarigua de Brión' ],
            [ 'id' => 617, 'municipality_id' => 227, 'parish'=> 'Mamporal' ],
            [ 'id' => 618, 'municipality_id' => 228, 'parish'=> 'Carrizal' ],
            [ 'id' => 619, 'municipality_id' => 229, 'parish'=> 'Chacao' ],
            [ 'id' => 620, 'municipality_id' => 230, 'parish'=> 'Charallave' ],
            [ 'id' => 621, 'municipality_id' => 230, 'parish'=> 'Las Brisas' ],
            [ 'id' => 622, 'municipality_id' => 231, 'parish'=> 'El Hatillo' ],
            [ 'id' => 623, 'municipality_id' => 232, 'parish'=> 'Altagracia de la Montaña' ],
            [ 'id' => 624, 'municipality_id' => 232, 'parish'=> 'Cecilio Acosta' ],
            [ 'id' => 625, 'municipality_id' => 232, 'parish'=> 'Los Teques' ],
            [ 'id' => 626, 'municipality_id' => 232, 'parish'=> 'El Jarillo' ],
            [ 'id' => 627, 'municipality_id' => 232, 'parish'=> 'San Pedro' ],
            [ 'id' => 628, 'municipality_id' => 232, 'parish'=> 'Tácata' ],
            [ 'id' => 629, 'municipality_id' => 232, 'parish'=> 'Paracotos' ],
            [ 'id' => 630, 'municipality_id' => 233, 'parish'=> 'Cartanal' ],
            [ 'id' => 631, 'municipality_id' => 233, 'parish'=> 'Santa Teresa del Tuy' ],
            [ 'id' => 632, 'municipality_id' => 234, 'parish'=> 'La Democracia' ],
            [ 'id' => 633, 'municipality_id' => 234, 'parish'=> 'Ocumare del Tuy' ],
            [ 'id' => 634, 'municipality_id' => 234, 'parish'=> 'Santa Bárbara' ],
            [ 'id' => 635, 'municipality_id' => 235, 'parish'=> 'San Antonio de los Altos' ],
            [ 'id' => 636, 'municipality_id' => 236, 'parish'=> 'Río Chico' ],
            [ 'id' => 637, 'municipality_id' => 236, 'parish'=> 'El Guapo' ],
            [ 'id' => 638, 'municipality_id' => 236, 'parish'=> 'Tacarigua de la Laguna' ],
            [ 'id' => 639, 'municipality_id' => 236, 'parish'=> 'Paparo' ],
            [ 'id' => 640, 'municipality_id' => 236, 'parish'=> 'San Fernando del Guapo' ],
            [ 'id' => 641, 'municipality_id' => 237, 'parish'=> 'Santa Lucía del Tuy' ],
            [ 'id' => 642, 'municipality_id' => 238, 'parish'=> 'Cúpira' ],
            [ 'id' => 643, 'municipality_id' => 238, 'parish'=> 'Machurucuto' ],
            [ 'id' => 644, 'municipality_id' => 239, 'parish'=> 'Guarenas' ],
            [ 'id' => 645, 'municipality_id' => 240, 'parish'=> 'San Antonio de Yare' ],
            [ 'id' => 646, 'municipality_id' => 240, 'parish'=> 'San Francisco de Yare' ],
            [ 'id' => 647, 'municipality_id' => 241, 'parish'=> 'Leoncio Martínez' ],
            [ 'id' => 648, 'municipality_id' => 241, 'parish'=> 'Petare' ],
            [ 'id' => 649, 'municipality_id' => 241, 'parish'=> 'Caucagüita' ],
            [ 'id' => 650, 'municipality_id' => 241, 'parish'=> 'Filas de Mariche' ],
            [ 'id' => 651, 'municipality_id' => 241, 'parish'=> 'La Dolorita' ],
            [ 'id' => 652, 'municipality_id' => 242, 'parish'=> 'Cúa' ],
            [ 'id' => 653, 'municipality_id' => 242, 'parish'=> 'Nueva Cúa' ],
            [ 'id' => 654, 'municipality_id' => 243, 'parish'=> 'Guatire' ],
            [ 'id' => 655, 'municipality_id' => 243, 'parish'=> 'Bolívar' ],
            [ 'id' => 656, 'municipality_id' => 258, 'parish'=> 'San Antonio de Maturín' ],
            [ 'id' => 657, 'municipality_id' => 258, 'parish'=> 'San Francisco de Maturín' ],
            [ 'id' => 658, 'municipality_id' => 259, 'parish'=> 'Aguasay' ],
            [ 'id' => 659, 'municipality_id' => 260, 'parish'=> 'Caripito' ],
            [ 'id' => 660, 'municipality_id' => 261, 'parish'=> 'El Guácharo' ],
            [ 'id' => 661, 'municipality_id' => 261, 'parish'=> 'La Guanota' ],
            [ 'id' => 662, 'municipality_id' => 261, 'parish'=> 'Sabana de Piedra' ],
            [ 'id' => 663, 'municipality_id' => 261, 'parish'=> 'San Agustín' ],
            [ 'id' => 664, 'municipality_id' => 261, 'parish'=> 'Teresen' ],
            [ 'id' => 665, 'municipality_id' => 261, 'parish'=> 'Caripe' ],
            [ 'id' => 666, 'municipality_id' => 262, 'parish'=> 'Areo' ],
            [ 'id' => 667, 'municipality_id' => 262, 'parish'=> 'Capital Cedeño' ],
            [ 'id' => 668, 'municipality_id' => 262, 'parish'=> 'San Félix de Cantalicio' ],
            [ 'id' => 669, 'municipality_id' => 262, 'parish'=> 'Viento Fresco' ],
            [ 'id' => 670, 'municipality_id' => 263, 'parish'=> 'El Tejero' ],
            [ 'id' => 671, 'municipality_id' => 263, 'parish'=> 'Punta de Mata' ],
            [ 'id' => 672, 'municipality_id' => 264, 'parish'=> 'Chaguaramas' ],
            [ 'id' => 673, 'municipality_id' => 264, 'parish'=> 'Las Alhuacas' ],
            [ 'id' => 674, 'municipality_id' => 264, 'parish'=> 'Tabasca' ],
            [ 'id' => 675, 'municipality_id' => 264, 'parish'=> 'Temblador' ],
            [ 'id' => 676, 'municipality_id' => 265, 'parish'=> 'Alto de los Godos' ],
            [ 'id' => 677, 'municipality_id' => 265, 'parish'=> 'Boquerón' ],
            [ 'id' => 678, 'municipality_id' => 265, 'parish'=> 'Las Cocuizas' ],
            [ 'id' => 679, 'municipality_id' => 265, 'parish'=> 'La Cruz' ],
            [ 'id' => 680, 'municipality_id' => 265, 'parish'=> 'San Simón' ],
            [ 'id' => 681, 'municipality_id' => 265, 'parish'=> 'El Corozo' ],
            [ 'id' => 682, 'municipality_id' => 265, 'parish'=> 'El Furrial' ],
            [ 'id' => 683, 'municipality_id' => 265, 'parish'=> 'Jusepín' ],
            [ 'id' => 684, 'municipality_id' => 265, 'parish'=> 'La Pica' ],
            [ 'id' => 685, 'municipality_id' => 265, 'parish'=> 'San Vicente' ],
            [ 'id' => 686, 'municipality_id' => 266, 'parish'=> 'Aparicio' ],
            [ 'id' => 687, 'municipality_id' => 266, 'parish'=> 'Aragua de Maturín' ],
            [ 'id' => 688, 'municipality_id' => 266, 'parish'=> 'Chaguamal' ],
            [ 'id' => 689, 'municipality_id' => 266, 'parish'=> 'El Pinto' ],
            [ 'id' => 690, 'municipality_id' => 266, 'parish'=> 'Guanaguana' ],
            [ 'id' => 691, 'municipality_id' => 266, 'parish'=> 'La Toscana' ],
            [ 'id' => 692, 'municipality_id' => 266, 'parish'=> 'Taguaya' ],
            [ 'id' => 693, 'municipality_id' => 267, 'parish'=> 'Cachipo' ],
            [ 'id' => 694, 'municipality_id' => 267, 'parish'=> 'Quiriquire' ],
            [ 'id' => 695, 'municipality_id' => 268, 'parish'=> 'Santa Bárbara' ],
            [ 'id' => 696, 'municipality_id' => 269, 'parish'=> 'Barrancas' ],
            [ 'id' => 697, 'municipality_id' => 269, 'parish'=> 'Los Barrancos de Fajardo' ],
            [ 'id' => 698, 'municipality_id' => 270, 'parish'=> 'Uracoa' ],
            [ 'id' => 699, 'municipality_id' => 271, 'parish'=> 'Antolín del Campo' ],
            [ 'id' => 700, 'municipality_id' => 272, 'parish'=> 'Arismendi' ],
            [ 'id' => 701, 'municipality_id' => 273, 'parish'=> 'García' ],
            [ 'id' => 702, 'municipality_id' => 273, 'parish'=> 'Francisco Fajardo' ],
            [ 'id' => 703, 'municipality_id' => 274, 'parish'=> 'Bolívar' ],
            [ 'id' => 704, 'municipality_id' => 274, 'parish'=> 'Guevara' ],
            [ 'id' => 705, 'municipality_id' => 274, 'parish'=> 'Matasiete' ],
            [ 'id' => 706, 'municipality_id' => 274, 'parish'=> 'Santa Ana' ],
            [ 'id' => 707, 'municipality_id' => 274, 'parish'=> 'Sucre' ],
            [ 'id' => 708, 'municipality_id' => 275, 'parish'=> 'Aguirre' ],
            [ 'id' => 709, 'municipality_id' => 275, 'parish'=> 'Maneiro' ],
            [ 'id' => 710, 'municipality_id' => 276, 'parish'=> 'Adrián' ],
            [ 'id' => 711, 'municipality_id' => 276, 'parish'=> 'Juan Griego' ],
            [ 'id' => 712, 'municipality_id' => 276, 'parish'=> 'Yaguaraparo' ],
            [ 'id' => 713, 'municipality_id' => 277, 'parish'=> 'Porlamar' ],
            [ 'id' => 714, 'municipality_id' => 278, 'parish'=> 'San Francisco de Macanao' ],
            [ 'id' => 715, 'municipality_id' => 278, 'parish'=> 'Boca de Río' ],
            [ 'id' => 716, 'municipality_id' => 279, 'parish'=> 'Tubores' ],
            [ 'id' => 717, 'municipality_id' => 279, 'parish'=> 'Los Baleales' ],
            [ 'id' => 718, 'municipality_id' => 280, 'parish'=> 'Vicente Fuentes' ],
            [ 'id' => 719, 'municipality_id' => 280, 'parish'=> 'Villalba' ],
            [ 'id' => 720, 'municipality_id' => 281, 'parish'=> 'San Juan Bautista' ],
            [ 'id' => 721, 'municipality_id' => 281, 'parish'=> 'Zabala' ],
            [ 'id' => 722, 'municipality_id' => 283, 'parish'=> 'Capital Araure' ],
            [ 'id' => 723, 'municipality_id' => 283, 'parish'=> 'Río Acarigua' ],
            [ 'id' => 724, 'municipality_id' => 284, 'parish'=> 'Capital Esteller' ],
            [ 'id' => 725, 'municipality_id' => 284, 'parish'=> 'Uveral' ],
            [ 'id' => 726, 'municipality_id' => 285, 'parish'=> 'Guanare' ],
            [ 'id' => 727, 'municipality_id' => 285, 'parish'=> 'Córdoba' ],
            [ 'id' => 728, 'municipality_id' => 285, 'parish'=> 'San José de la Montaña' ],
            [ 'id' => 729, 'municipality_id' => 285, 'parish'=> 'San Juan de Guanaguanare' ],
            [ 'id' => 730, 'municipality_id' => 285, 'parish'=> 'Virgen de la Coromoto' ],
            [ 'id' => 731, 'municipality_id' => 286, 'parish'=> 'Guanarito' ],
            [ 'id' => 732, 'municipality_id' => 286, 'parish'=> 'Trinidad de la Capilla' ],
            [ 'id' => 733, 'municipality_id' => 286, 'parish'=> 'Divina Pastora' ],
            [ 'id' => 734, 'municipality_id' => 287, 'parish'=> 'Monseñor José Vicente de Unda' ],
            [ 'id' => 735, 'municipality_id' => 287, 'parish'=> 'Peña Blanca' ],
            [ 'id' => 736, 'municipality_id' => 288, 'parish'=> 'Capital Ospino' ],
            [ 'id' => 737, 'municipality_id' => 288, 'parish'=> 'Aparición' ],
            [ 'id' => 738, 'municipality_id' => 288, 'parish'=> 'La Estación' ],
            [ 'id' => 739, 'municipality_id' => 289, 'parish'=> 'Páez' ],
            [ 'id' => 740, 'municipality_id' => 289, 'parish'=> 'Payara' ],
            [ 'id' => 741, 'municipality_id' => 289, 'parish'=> 'Pimpinela' ],
            [ 'id' => 742, 'municipality_id' => 289, 'parish'=> 'Ramón Peraza' ],
            [ 'id' => 743, 'municipality_id' => 290, 'parish'=> 'Papelón' ],
            [ 'id' => 744, 'municipality_id' => 290, 'parish'=> 'Caño Delgadito' ],
            [ 'id' => 745, 'municipality_id' => 291, 'parish'=> 'San Genaro de Boconoito' ],
            [ 'id' => 746, 'municipality_id' => 291, 'parish'=> 'Antolín Tovar' ],
            [ 'id' => 747, 'municipality_id' => 292, 'parish'=> 'San Rafael de Onoto' ],
            [ 'id' => 748, 'municipality_id' => 292, 'parish'=> 'Santa Fe' ],
            [ 'id' => 749, 'municipality_id' => 292, 'parish'=> 'Thermo Morles' ],
            [ 'id' => 750, 'municipality_id' => 293, 'parish'=> 'Santa Rosalía' ],
            [ 'id' => 751, 'municipality_id' => 293, 'parish'=> 'Florida' ],
            [ 'id' => 752, 'municipality_id' => 294, 'parish'=> 'Sucre' ],
            [ 'id' => 753, 'municipality_id' => 294, 'parish'=> 'Concepción' ],
            [ 'id' => 754, 'municipality_id' => 294, 'parish'=> 'San Rafael de Palo Alzado' ],
            [ 'id' => 755, 'municipality_id' => 294, 'parish'=> 'Uvencio Antonio Velásquez' ],
            [ 'id' => 756, 'municipality_id' => 294, 'parish'=> 'San José de Saguaz' ],
            [ 'id' => 757, 'municipality_id' => 294, 'parish'=> 'Villa Rosa' ],
            [ 'id' => 758, 'municipality_id' => 295, 'parish'=> 'Turén' ],
            [ 'id' => 759, 'municipality_id' => 295, 'parish'=> 'Canelones' ],
            [ 'id' => 760, 'municipality_id' => 295, 'parish'=> 'Santa Cruz' ],
            [ 'id' => 761, 'municipality_id' => 295, 'parish'=> 'San Isidro Labrador' ],
            [ 'id' => 762, 'municipality_id' => 296, 'parish'=> 'Mariño' ],
            [ 'id' => 763, 'municipality_id' => 296, 'parish'=> 'Rómulo Gallegos' ],
            [ 'id' => 764, 'municipality_id' => 297, 'parish'=> 'San José de Aerocuar' ],
            [ 'id' => 765, 'municipality_id' => 297, 'parish'=> 'Tavera Acosta' ],
            [ 'id' => 766, 'municipality_id' => 298, 'parish'=> 'Río Caribe' ],
            [ 'id' => 767, 'municipality_id' => 298, 'parish'=> 'Antonio José de Sucre' ],
            [ 'id' => 768, 'municipality_id' => 298, 'parish'=> 'El Morro de Puerto Santo' ],
            [ 'id' => 769, 'municipality_id' => 298, 'parish'=> 'Puerto Santo' ],
            [ 'id' => 770, 'municipality_id' => 298, 'parish'=> 'San Juan de las Galdonas' ],
            [ 'id' => 771, 'municipality_id' => 299, 'parish'=> 'El Pilar' ],
            [ 'id' => 772, 'municipality_id' => 299, 'parish'=> 'El Rincón' ],
            [ 'id' => 773, 'municipality_id' => 299, 'parish'=> 'General Francisco Antonio Váquez' ],
            [ 'id' => 774, 'municipality_id' => 299, 'parish'=> 'Guaraúnos' ],
            [ 'id' => 775, 'municipality_id' => 299, 'parish'=> 'Tunapuicito' ],
            [ 'id' => 776, 'municipality_id' => 299, 'parish'=> 'Unión' ],
            [ 'id' => 777, 'municipality_id' => 300, 'parish'=> 'Santa Catalina' ],
            [ 'id' => 778, 'municipality_id' => 300, 'parish'=> 'Santa Rosa' ],
            [ 'id' => 779, 'municipality_id' => 300, 'parish'=> 'Santa Teresa' ],
            [ 'id' => 780, 'municipality_id' => 300, 'parish'=> 'Bolívar' ],
            [ 'id' => 781, 'municipality_id' => 300, 'parish'=> 'Maracapana' ],
            [ 'id' => 782, 'municipality_id' => 302, 'parish'=> 'Libertad' ],
            [ 'id' => 783, 'municipality_id' => 302, 'parish'=> 'El Paujil' ],
            [ 'id' => 784, 'municipality_id' => 302, 'parish'=> 'Yaguaraparo' ],
            [ 'id' => 785, 'municipality_id' => 303, 'parish'=> 'Cruz Salmerón Acosta' ],
            [ 'id' => 786, 'municipality_id' => 303, 'parish'=> 'Chacopata' ],
            [ 'id' => 787, 'municipality_id' => 303, 'parish'=> 'Manicuare' ],
            [ 'id' => 788, 'municipality_id' => 304, 'parish'=> 'Tunapuy' ],
            [ 'id' => 789, 'municipality_id' => 304, 'parish'=> 'Campo Elías' ],
            [ 'id' => 790, 'municipality_id' => 305, 'parish'=> 'Irapa' ],
            [ 'id' => 791, 'municipality_id' => 305, 'parish'=> 'Campo Claro' ],
            [ 'id' => 792, 'municipality_id' => 305, 'parish'=> 'Maraval' ],
            [ 'id' => 793, 'municipality_id' => 305, 'parish'=> 'San Antonio de Irapa' ],
            [ 'id' => 794, 'municipality_id' => 305, 'parish'=> 'Soro' ],
            [ 'id' => 795, 'municipality_id' => 306, 'parish'=> 'Mejía' ],
            [ 'id' => 796, 'municipality_id' => 307, 'parish'=> 'Cumanacoa' ],
            [ 'id' => 797, 'municipality_id' => 307, 'parish'=> 'Arenas' ],
            [ 'id' => 798, 'municipality_id' => 307, 'parish'=> 'Aricagua' ],
            [ 'id' => 799, 'municipality_id' => 307, 'parish'=> 'Cogollar' ],
            [ 'id' => 800, 'municipality_id' => 307, 'parish'=> 'San Fernando' ],
            [ 'id' => 801, 'municipality_id' => 307, 'parish'=> 'San Lorenzo' ],
            [ 'id' => 802, 'municipality_id' => 308, 'parish'=> 'Villa Frontado (Muelle de Cariaco)' ],
            [ 'id' => 803, 'municipality_id' => 308, 'parish'=> 'Catuaro' ],
            [ 'id' => 804, 'municipality_id' => 308, 'parish'=> 'Rendón' ],
            [ 'id' => 805, 'municipality_id' => 308, 'parish'=> 'San Cruz' ],
            [ 'id' => 806, 'municipality_id' => 308, 'parish'=> 'Santa María' ],
            [ 'id' => 807, 'municipality_id' => 309, 'parish'=> 'Altagracia' ],
            [ 'id' => 808, 'municipality_id' => 309, 'parish'=> 'Santa Inés' ],
            [ 'id' => 809, 'municipality_id' => 309, 'parish'=> 'Valentín Valiente' ],
            [ 'id' => 810, 'municipality_id' => 309, 'parish'=> 'Ayacucho' ],
            [ 'id' => 811, 'municipality_id' => 309, 'parish'=> 'San Juan' ],
            [ 'id' => 812, 'municipality_id' => 309, 'parish'=> 'Raúl Leoni' ],
            [ 'id' => 813, 'municipality_id' => 309, 'parish'=> 'Gran Mariscal' ],
            [ 'id' => 814, 'municipality_id' => 310, 'parish'=> 'Cristóbal Colón' ],
            [ 'id' => 815, 'municipality_id' => 310, 'parish'=> 'Bideau' ],
            [ 'id' => 816, 'municipality_id' => 310, 'parish'=> 'Punta de Piedras' ],
            [ 'id' => 817, 'municipality_id' => 310, 'parish'=> 'Güiria' ],
            [ 'id' => 818, 'municipality_id' => 341, 'parish'=> 'Andrés Bello' ],
            [ 'id' => 819, 'municipality_id' => 342, 'parish'=> 'Antonio Rómulo Costa' ],
            [ 'id' => 820, 'municipality_id' => 343, 'parish'=> 'Ayacucho' ],
            [ 'id' => 821, 'municipality_id' => 343, 'parish'=> 'Rivas Berti' ],
            [ 'id' => 822, 'municipality_id' => 343, 'parish'=> 'San Pedro del Río' ],
            [ 'id' => 823, 'municipality_id' => 344, 'parish'=> 'Bolívar' ],
            [ 'id' => 824, 'municipality_id' => 344, 'parish'=> 'Palotal' ],
            [ 'id' => 825, 'municipality_id' => 344, 'parish'=> 'General Juan Vicente Gómez' ],
            [ 'id' => 826, 'municipality_id' => 344, 'parish'=> 'Isaías Medina Angarita' ],
            [ 'id' => 827, 'municipality_id' => 345, 'parish'=> 'Cárdenas' ],
            [ 'id' => 828, 'municipality_id' => 345, 'parish'=> 'Amenodoro Ángel Lamus' ],
            [ 'id' => 829, 'municipality_id' => 345, 'parish'=> 'La Florida' ],
            [ 'id' => 830, 'municipality_id' => 346, 'parish'=> 'Córdoba' ],
            [ 'id' => 831, 'municipality_id' => 347, 'parish'=> 'Fernández Feo' ],
            [ 'id' => 832, 'municipality_id' => 347, 'parish'=> 'Alberto Adriani' ],
            [ 'id' => 833, 'municipality_id' => 347, 'parish'=> 'Santo Domingo' ],
            [ 'id' => 834, 'municipality_id' => 348, 'parish'=> 'Francisco de Miranda' ],
            [ 'id' => 835, 'municipality_id' => 349, 'parish'=> 'García de Hevia' ],
            [ 'id' => 836, 'municipality_id' => 349, 'parish'=> 'Boca de Grita' ],
            [ 'id' => 837, 'municipality_id' => 349, 'parish'=> 'José Antonio Páez' ],
            [ 'id' => 838, 'municipality_id' => 350, 'parish'=> 'Guásimos' ],
            [ 'id' => 839, 'municipality_id' => 351, 'parish'=> 'Independencia' ],
            [ 'id' => 840, 'municipality_id' => 351, 'parish'=> 'Juan Germán Roscio' ],
            [ 'id' => 841, 'municipality_id' => 351, 'parish'=> 'Román Cárdenas' ],
            [ 'id' => 842, 'municipality_id' => 352, 'parish'=> 'Jáuregui' ],
            [ 'id' => 843, 'municipality_id' => 352, 'parish'=> 'Emilio Constantino Guerrero' ],
            [ 'id' => 844, 'municipality_id' => 352, 'parish'=> 'Monseñor Miguel Antonio Salas' ],
            [ 'id' => 845, 'municipality_id' => 353, 'parish'=> 'José María Vargas' ],
            [ 'id' => 846, 'municipality_id' => 354, 'parish'=> 'Junín' ],
            [ 'id' => 847, 'municipality_id' => 354, 'parish'=> 'La Petrólea' ],
            [ 'id' => 848, 'municipality_id' => 354, 'parish'=> 'Quinimarí' ],
            [ 'id' => 849, 'municipality_id' => 354, 'parish'=> 'Bramón' ],
            [ 'id' => 850, 'municipality_id' => 355, 'parish'=> 'Libertad' ],
            [ 'id' => 851, 'municipality_id' => 355, 'parish'=> 'Cipriano Castro' ],
            [ 'id' => 852, 'municipality_id' => 355, 'parish'=> 'Manuel Felipe Rugeles' ],
            [ 'id' => 853, 'municipality_id' => 356, 'parish'=> 'Libertador' ],
            [ 'id' => 854, 'municipality_id' => 356, 'parish'=> 'Doradas' ],
            [ 'id' => 855, 'municipality_id' => 356, 'parish'=> 'Emeterio Ochoa' ],
            [ 'id' => 856, 'municipality_id' => 356, 'parish'=> 'San Joaquín de Navay' ],
            [ 'id' => 857, 'municipality_id' => 357, 'parish'=> 'Lobatera' ],
            [ 'id' => 858, 'municipality_id' => 357, 'parish'=> 'Constitución' ],
            [ 'id' => 859, 'municipality_id' => 358, 'parish'=> 'Michelena' ],
            [ 'id' => 860, 'municipality_id' => 359, 'parish'=> 'Panamericano' ],
            [ 'id' => 861, 'municipality_id' => 359, 'parish'=> 'La Palmita' ],
            [ 'id' => 862, 'municipality_id' => 360, 'parish'=> 'Pedro María Ureña' ],
            [ 'id' => 863, 'municipality_id' => 360, 'parish'=> 'Nueva Arcadia' ],
            [ 'id' => 864, 'municipality_id' => 361, 'parish'=> 'Delicias' ],
            [ 'id' => 865, 'municipality_id' => 361, 'parish'=> 'Pecaya' ],
            [ 'id' => 866, 'municipality_id' => 362, 'parish'=> 'Samuel Darío Maldonado' ],
            [ 'id' => 867, 'municipality_id' => 362, 'parish'=> 'Boconó' ],
            [ 'id' => 868, 'municipality_id' => 362, 'parish'=> 'Hernández' ],
            [ 'id' => 869, 'municipality_id' => 363, 'parish'=> 'La Concordia' ],
            [ 'id' => 870, 'municipality_id' => 363, 'parish'=> 'San Juan Bautista' ],
            [ 'id' => 871, 'municipality_id' => 363, 'parish'=> 'Pedro María Morantes' ],
            [ 'id' => 872, 'municipality_id' => 363, 'parish'=> 'San Sebastián' ],
            [ 'id' => 873, 'municipality_id' => 363, 'parish'=> 'Dr. Francisco Romero Lobo' ],
            [ 'id' => 874, 'municipality_id' => 364, 'parish'=> 'Seboruco' ],
            [ 'id' => 875, 'municipality_id' => 365, 'parish'=> 'Simón Rodríguez' ],
            [ 'id' => 876, 'municipality_id' => 366, 'parish'=> 'Sucre' ],
            [ 'id' => 877, 'municipality_id' => 366, 'parish'=> 'Eleazar López Contreras' ],
            [ 'id' => 878, 'municipality_id' => 366, 'parish'=> 'San Pablo' ],
            [ 'id' => 879, 'municipality_id' => 367, 'parish'=> 'Torbes' ],
            [ 'id' => 880, 'municipality_id' => 368, 'parish'=> 'Uribante' ],
            [ 'id' => 881, 'municipality_id' => 368, 'parish'=> 'Cárdenas' ],
            [ 'id' => 882, 'municipality_id' => 368, 'parish'=> 'Juan Pablo Peñalosa' ],
            [ 'id' => 883, 'municipality_id' => 368, 'parish'=> 'Potosí' ],
            [ 'id' => 884, 'municipality_id' => 369, 'parish'=> 'San Judas Tadeo' ],
            [ 'id' => 885, 'municipality_id' => 370, 'parish'=> 'Araguaney' ],
            [ 'id' => 886, 'municipality_id' => 370, 'parish'=> 'El Jaguito' ],
            [ 'id' => 887, 'municipality_id' => 370, 'parish'=> 'La Esperanza' ],
            [ 'id' => 888, 'municipality_id' => 370, 'parish'=> 'Santa Isabel' ],
            [ 'id' => 889, 'municipality_id' => 371, 'parish'=> 'Boconó' ],
            [ 'id' => 890, 'municipality_id' => 371, 'parish'=> 'El Carmen' ],
            [ 'id' => 891, 'municipality_id' => 371, 'parish'=> 'Mosquey' ],
            [ 'id' => 892, 'municipality_id' => 371, 'parish'=> 'Ayacucho' ],
            [ 'id' => 893, 'municipality_id' => 371, 'parish'=> 'Burbusay' ],
            [ 'id' => 894, 'municipality_id' => 371, 'parish'=> 'General Ribas' ],
            [ 'id' => 895, 'municipality_id' => 371, 'parish'=> 'Guaramacal' ],
            [ 'id' => 896, 'municipality_id' => 371, 'parish'=> 'Vega de Guaramacal' ],
            [ 'id' => 897, 'municipality_id' => 371, 'parish'=> 'Monseñor Jáuregui' ],
            [ 'id' => 898, 'municipality_id' => 371, 'parish'=> 'Rafael Rangel' ],
            [ 'id' => 899, 'municipality_id' => 371, 'parish'=> 'San Miguel' ],
            [ 'id' => 900, 'municipality_id' => 371, 'parish'=> 'San José' ],
            [ 'id' => 901, 'municipality_id' => 372, 'parish'=> 'Sabana Grande' ],
            [ 'id' => 902, 'municipality_id' => 372, 'parish'=> 'Cheregüé' ],
            [ 'id' => 903, 'municipality_id' => 372, 'parish'=> 'Granados' ],
            [ 'id' => 904, 'municipality_id' => 373, 'parish'=> 'Arnoldo Gabaldón' ],
            [ 'id' => 905, 'municipality_id' => 373, 'parish'=> 'Bolivia' ],
            [ 'id' => 906, 'municipality_id' => 373, 'parish'=> 'Carrillo' ],
            [ 'id' => 907, 'municipality_id' => 373, 'parish'=> 'Cegarra' ],
            [ 'id' => 908, 'municipality_id' => 373, 'parish'=> 'Chejendé' ],
            [ 'id' => 909, 'municipality_id' => 373, 'parish'=> 'Manuel Salvador Ulloa' ],
            [ 'id' => 910, 'municipality_id' => 373, 'parish'=> 'San José' ],
            [ 'id' => 911, 'municipality_id' => 374, 'parish'=> 'Carache' ],
            [ 'id' => 912, 'municipality_id' => 374, 'parish'=> 'La Concepción' ],
            [ 'id' => 913, 'municipality_id' => 374, 'parish'=> 'Cuicas' ],
            [ 'id' => 914, 'municipality_id' => 374, 'parish'=> 'Panamericana' ],
            [ 'id' => 915, 'municipality_id' => 374, 'parish'=> 'Santa Cruz' ],
            [ 'id' => 916, 'municipality_id' => 375, 'parish'=> 'Escuque' ],
            [ 'id' => 917, 'municipality_id' => 375, 'parish'=> 'La Unión' ],
            [ 'id' => 918, 'municipality_id' => 375, 'parish'=> 'Santa Rita' ],
            [ 'id' => 919, 'municipality_id' => 375, 'parish'=> 'Sabana Libre' ],
            [ 'id' => 920, 'municipality_id' => 376, 'parish'=> 'El Socorro' ],
            [ 'id' => 921, 'municipality_id' => 376, 'parish'=> 'Los Caprichos' ],
            [ 'id' => 922, 'municipality_id' => 376, 'parish'=> 'Antonio José de Sucre' ],
            [ 'id' => 923, 'municipality_id' => 377, 'parish'=> 'Campo Elías' ],
            [ 'id' => 924, 'municipality_id' => 377, 'parish'=> 'Arnoldo Gabaldón' ],
            [ 'id' => 925, 'municipality_id' => 378, 'parish'=> 'Santa Apolonia' ],
            [ 'id' => 926, 'municipality_id' => 378, 'parish'=> 'El Progreso' ],
            [ 'id' => 927, 'municipality_id' => 378, 'parish'=> 'La Ceiba' ],
            [ 'id' => 928, 'municipality_id' => 378, 'parish'=> 'Tres de Febrero' ],
            [ 'id' => 929, 'municipality_id' => 379, 'parish'=> 'El Dividive' ],
            [ 'id' => 930, 'municipality_id' => 379, 'parish'=> 'Agua Santa' ],
            [ 'id' => 931, 'municipality_id' => 379, 'parish'=> 'Agua Caliente' ],
            [ 'id' => 932, 'municipality_id' => 379, 'parish'=> 'El Cenizo' ],
            [ 'id' => 933, 'municipality_id' => 379, 'parish'=> 'Valerita' ],
            [ 'id' => 934, 'municipality_id' => 380, 'parish'=> 'Monte Carmelo' ],
            [ 'id' => 935, 'municipality_id' => 380, 'parish'=> 'Buena Vista' ],
            [ 'id' => 936, 'municipality_id' => 380, 'parish'=> 'Santa María del Horcón' ],
            [ 'id' => 937, 'municipality_id' => 381, 'parish'=> 'Motatán' ],
            [ 'id' => 938, 'municipality_id' => 381, 'parish'=> 'El Baño' ],
            [ 'id' => 939, 'municipality_id' => 381, 'parish'=> 'Jalisco' ],
            [ 'id' => 940, 'municipality_id' => 382, 'parish'=> 'Pampán' ],
            [ 'id' => 941, 'municipality_id' => 382, 'parish'=> 'Flor de Patria' ],
            [ 'id' => 942, 'municipality_id' => 382, 'parish'=> 'La Paz' ],
            [ 'id' => 943, 'municipality_id' => 382, 'parish'=> 'Santa Ana' ],
            [ 'id' => 944, 'municipality_id' => 383, 'parish'=> 'Pampanito' ],
            [ 'id' => 945, 'municipality_id' => 383, 'parish'=> 'La Concepción' ],
            [ 'id' => 946, 'municipality_id' => 383, 'parish'=> 'Pampanito II' ],
            [ 'id' => 947, 'municipality_id' => 384, 'parish'=> 'Betijoque' ],
            [ 'id' => 948, 'municipality_id' => 384, 'parish'=> 'José Gregorio Hernández' ],
            [ 'id' => 949, 'municipality_id' => 384, 'parish'=> 'La Pueblita' ],
            [ 'id' => 950, 'municipality_id' => 384, 'parish'=> 'Los Cedros' ],
            [ 'id' => 951, 'municipality_id' => 385, 'parish'=> 'Carvajal' ],
            [ 'id' => 952, 'municipality_id' => 385, 'parish'=> 'Campo Alegre' ],
            [ 'id' => 953, 'municipality_id' => 385, 'parish'=> 'Antonio Nicolás Briceño' ],
            [ 'id' => 954, 'municipality_id' => 385, 'parish'=> 'José Leonardo Suárez' ],
            [ 'id' => 955, 'municipality_id' => 386, 'parish'=> 'Sabana de Mendoza' ],
            [ 'id' => 956, 'municipality_id' => 386, 'parish'=> 'Junín' ],
            [ 'id' => 957, 'municipality_id' => 386, 'parish'=> 'Valmore Rodríguez' ],
            [ 'id' => 958, 'municipality_id' => 386, 'parish'=> 'El Paraíso' ],
            [ 'id' => 959, 'municipality_id' => 387, 'parish'=> 'Andrés Linares' ],
            [ 'id' => 960, 'municipality_id' => 387, 'parish'=> 'Chiquinquirá' ],
            [ 'id' => 961, 'municipality_id' => 387, 'parish'=> 'Cristóbal Mendoza' ],
            [ 'id' => 962, 'municipality_id' => 387, 'parish'=> 'Cruz Carrillo' ],
            [ 'id' => 963, 'municipality_id' => 387, 'parish'=> 'Matriz' ],
            [ 'id' => 964, 'municipality_id' => 387, 'parish'=> 'Monseñor Carrillo' ],
            [ 'id' => 965, 'municipality_id' => 387, 'parish'=> 'Tres Esquinas' ],
            [ 'id' => 966, 'municipality_id' => 388, 'parish'=> 'Cabimbú' ],
            [ 'id' => 967, 'municipality_id' => 388, 'parish'=> 'Jajó' ],
            [ 'id' => 968, 'municipality_id' => 388, 'parish'=> 'La Mesa de Esnujaque' ],
            [ 'id' => 969, 'municipality_id' => 388, 'parish'=> 'Santiago' ],
            [ 'id' => 970, 'municipality_id' => 388, 'parish'=> 'Tuñame' ],
            [ 'id' => 971, 'municipality_id' => 388, 'parish'=> 'La Quebrada' ],
            [ 'id' => 972, 'municipality_id' => 389, 'parish'=> 'Juan Ignacio Montilla' ],
            [ 'id' => 973, 'municipality_id' => 389, 'parish'=> 'La Beatriz' ],
            [ 'id' => 974, 'municipality_id' => 389, 'parish'=> 'La Puerta' ],
            [ 'id' => 975, 'municipality_id' => 389, 'parish'=> 'Mendoza del Valle de Momboy' ],
            [ 'id' => 976, 'municipality_id' => 389, 'parish'=> 'Mercedes Díaz' ],
            [ 'id' => 977, 'municipality_id' => 389, 'parish'=> 'San Luis' ],
            [ 'id' => 978, 'municipality_id' => 390, 'parish'=> 'Caraballeda' ],
            [ 'id' => 979, 'municipality_id' => 390, 'parish'=> 'Carayaca' ],
            [ 'id' => 980, 'municipality_id' => 390, 'parish'=> 'Carlos Soublette' ],
            [ 'id' => 981, 'municipality_id' => 390, 'parish'=> 'Caruao Chuspa' ],
            [ 'id' => 982, 'municipality_id' => 390, 'parish'=> 'Catia La Mar' ],
            [ 'id' => 983, 'municipality_id' => 390, 'parish'=> 'El Junko' ],
            [ 'id' => 984, 'municipality_id' => 390, 'parish'=> 'La Guaira' ],
            [ 'id' => 985, 'municipality_id' => 390, 'parish'=> 'Macuto' ],
            [ 'id' => 986, 'municipality_id' => 390, 'parish'=> 'Maiquetía' ],
            [ 'id' => 987, 'municipality_id' => 390, 'parish'=> 'Naiguatá' ],
            [ 'id' => 988, 'municipality_id' => 390, 'parish'=> 'Urimare' ],
            [ 'id' => 989, 'municipality_id' => 391, 'parish'=> 'Arístides Bastidas' ],
            [ 'id' => 990, 'municipality_id' => 392, 'parish'=> 'Bolívar' ],
            [ 'id' => 991, 'municipality_id' => 407, 'parish'=> 'Chivacoa' ],
            [ 'id' => 992, 'municipality_id' => 407, 'parish'=> 'Campo Elías' ],
            [ 'id' => 993, 'municipality_id' => 408, 'parish'=> 'Cocorote' ],
            [ 'id' => 994, 'municipality_id' => 409, 'parish'=> 'Independencia' ],
            [ 'id' => 995, 'municipality_id' => 410, 'parish'=> 'José Antonio Páez' ],
            [ 'id' => 996, 'municipality_id' => 411, 'parish'=> 'La Trinidad' ],
            [ 'id' => 997, 'municipality_id' => 412, 'parish'=> 'Manuel Monge' ],
            [ 'id' => 998, 'municipality_id' => 413, 'parish'=> 'Salóm' ],
            [ 'id' => 999, 'municipality_id' => 413, 'parish'=> 'Temerla' ],
            [ 'id' => 1000, 'municipality_id' => 413, 'parish'=> 'Nirgua' ],
            [ 'id' => 1001, 'municipality_id' => 414, 'parish'=> 'San Andrés' ],
            [ 'id' => 1002, 'municipality_id' => 414, 'parish'=> 'Yaritagua' ],
            [ 'id' => 1003, 'municipality_id' => 415, 'parish'=> 'San Javier' ],
            [ 'id' => 1004, 'municipality_id' => 415, 'parish'=> 'Albarico' ],
            [ 'id' => 1005, 'municipality_id' => 415, 'parish'=> 'San Felipe' ],
            [ 'id' => 1006, 'municipality_id' => 416, 'parish'=> 'Sucre' ],
            [ 'id' => 1007, 'municipality_id' => 417, 'parish'=> 'Urachiche' ],
            [ 'id' => 1008, 'municipality_id' => 418, 'parish'=> 'El Guayabo' ],
            [ 'id' => 1009, 'municipality_id' => 418, 'parish'=> 'Farriar' ],
            [ 'id' => 1010, 'municipality_id' => 441, 'parish'=> 'Isla de Toas' ],
            [ 'id' => 1011, 'municipality_id' => 441, 'parish'=> 'Monagas' ],
            [ 'id' => 1012, 'municipality_id' => 442, 'parish'=> 'San Timoteo' ],
            [ 'id' => 1013, 'municipality_id' => 442, 'parish'=> 'General Urdaneta' ],
            [ 'id' => 1014, 'municipality_id' => 442, 'parish'=> 'Libertador' ],
            [ 'id' => 1015, 'municipality_id' => 442, 'parish'=> 'Marcelino Briceño' ],
            [ 'id' => 1016, 'municipality_id' => 442, 'parish'=> 'Pueblo Nuevo' ],
            [ 'id' => 1017, 'municipality_id' => 442, 'parish'=> 'Manuel Guanipa Matos' ],
            [ 'id' => 1018, 'municipality_id' => 443, 'parish'=> 'Ambrosio' ],
            [ 'id' => 1019, 'municipality_id' => 443, 'parish'=> 'Carmen Herrera' ],
            [ 'id' => 1020, 'municipality_id' => 443, 'parish'=> 'La Rosa' ],
            [ 'id' => 1021, 'municipality_id' => 443, 'parish'=> 'Germán Ríos Linares' ],
            [ 'id' => 1022, 'municipality_id' => 443, 'parish'=> 'San Benito' ],
            [ 'id' => 1023, 'municipality_id' => 443, 'parish'=> 'Rómulo Betancourt' ],
            [ 'id' => 1024, 'municipality_id' => 443, 'parish'=> 'Jorge Hernández' ],
            [ 'id' => 1025, 'municipality_id' => 443, 'parish'=> 'Punta Gorda' ],
            [ 'id' => 1026, 'municipality_id' => 443, 'parish'=> 'Arístides Calvani' ],
            [ 'id' => 1027, 'municipality_id' => 444, 'parish'=> 'Encontrados' ],
            [ 'id' => 1028, 'municipality_id' => 444, 'parish'=> 'Udón Pérez' ],
            [ 'id' => 1029, 'municipality_id' => 445, 'parish'=> 'Moralito' ],
            [ 'id' => 1030, 'municipality_id' => 445, 'parish'=> 'San Carlos del Zulia' ],
            [ 'id' => 1031, 'municipality_id' => 445, 'parish'=> 'Santa Cruz del Zulia' ],
            [ 'id' => 1032, 'municipality_id' => 445, 'parish'=> 'Santa Bárbara' ],
            [ 'id' => 1033, 'municipality_id' => 445, 'parish'=> 'Urribarrí' ],
            [ 'id' => 1034, 'municipality_id' => 446, 'parish'=> 'Carlos Quevedo' ],
            [ 'id' => 1035, 'municipality_id' => 446, 'parish'=> 'Francisco Javier Pulgar' ],
            [ 'id' => 1036, 'municipality_id' => 446, 'parish'=> 'Simón Rodríguez' ],
            [ 'id' => 1037, 'municipality_id' => 446, 'parish'=> 'Guamo-Gavilanes' ],
            [ 'id' => 1038, 'municipality_id' => 448, 'parish'=> 'La Concepción' ],
            [ 'id' => 1039, 'municipality_id' => 448, 'parish'=> 'San José' ],
            [ 'id' => 1040, 'municipality_id' => 448, 'parish'=> 'Mariano Parra León' ],
            [ 'id' => 1041, 'municipality_id' => 448, 'parish'=> 'José Ramón Yépez' ],
            [ 'id' => 1042, 'municipality_id' => 449, 'parish'=> 'Jesús María Semprún' ],
            [ 'id' => 1043, 'municipality_id' => 449, 'parish'=> 'Barí' ],
            [ 'id' => 1044, 'municipality_id' => 450, 'parish'=> 'Concepción' ],
            [ 'id' => 1045, 'municipality_id' => 450, 'parish'=> 'Andrés Bello' ],
            [ 'id' => 1046, 'municipality_id' => 450, 'parish'=> 'Chiquinquirá' ],
            [ 'id' => 1047, 'municipality_id' => 450, 'parish'=> 'El Carmelo' ],
            [ 'id' => 1048, 'municipality_id' => 450, 'parish'=> 'Potreritos' ],
            [ 'id' => 1049, 'municipality_id' => 451, 'parish'=> 'Libertad' ],
            [ 'id' => 1050, 'municipality_id' => 451, 'parish'=> 'Alonso de Ojeda' ],
            [ 'id' => 1051, 'municipality_id' => 451, 'parish'=> 'Venezuela' ],
            [ 'id' => 1052, 'municipality_id' => 451, 'parish'=> 'Eleazar López Contreras' ],
            [ 'id' => 1053, 'municipality_id' => 451, 'parish'=> 'Campo Lara' ],
            [ 'id' => 1054, 'municipality_id' => 452, 'parish'=> 'Bartolomé de las Casas' ],
            [ 'id' => 1055, 'municipality_id' => 452, 'parish'=> 'Libertad' ],
            [ 'id' => 1056, 'municipality_id' => 452, 'parish'=> 'Río Negro' ],
            [ 'id' => 1057, 'municipality_id' => 452, 'parish'=> 'San José de Perijá' ],
            [ 'id' => 1058, 'municipality_id' => 453, 'parish'=> 'San Rafael' ],
            [ 'id' => 1059, 'municipality_id' => 453, 'parish'=> 'La Sierrita' ],
            [ 'id' => 1060, 'municipality_id' => 453, 'parish'=> 'Las Parcelas' ],
            [ 'id' => 1061, 'municipality_id' => 453, 'parish'=> 'Luis de Vicente' ],
            [ 'id' => 1062, 'municipality_id' => 453, 'parish'=> 'Monseñor Marcos Sergio Godoy' ],
            [ 'id' => 1063, 'municipality_id' => 453, 'parish'=> 'Ricaurte' ],
            [ 'id' => 1064, 'municipality_id' => 453, 'parish'=> 'Tamare' ],
            [ 'id' => 1065, 'municipality_id' => 454, 'parish'=> 'Antonio Borjas Romero' ],
            [ 'id' => 1066, 'municipality_id' => 454, 'parish'=> 'Bolívar' ],
            [ 'id' => 1067, 'municipality_id' => 454, 'parish'=> 'Cacique Mara' ],
            [ 'id' => 1068, 'municipality_id' => 454, 'parish'=> 'Carracciolo Parra Pérez' ],
            [ 'id' => 1069, 'municipality_id' => 454, 'parish'=> 'Cecilio Acosta' ],
            [ 'id' => 1070, 'municipality_id' => 454, 'parish'=> 'Cristo de Aranza' ],
            [ 'id' => 1071, 'municipality_id' => 454, 'parish'=> 'Coquivacoa' ],
            [ 'id' => 1072, 'municipality_id' => 454, 'parish'=> 'Chiquinquirá' ],
            [ 'id' => 1073, 'municipality_id' => 454, 'parish'=> 'Francisco Eugenio Bustamante' ],
            [ 'id' => 1074, 'municipality_id' => 454, 'parish'=> 'Idelfonzo Vásquez' ],
            [ 'id' => 1075, 'municipality_id' => 454, 'parish'=> 'Juana de Ávila' ],
            [ 'id' => 1076, 'municipality_id' => 454, 'parish'=> 'Luis Hurtado Higuera' ],
            [ 'id' => 1077, 'municipality_id' => 454, 'parish'=> 'Manuel Dagnino' ],
            [ 'id' => 1078, 'municipality_id' => 454, 'parish'=> 'Olegario Villalobos' ],
            [ 'id' => 1079, 'municipality_id' => 454, 'parish'=> 'Raúl Leoni' ],
            [ 'id' => 1080, 'municipality_id' => 454, 'parish'=> 'Santa Lucía' ],
            [ 'id' => 1081, 'municipality_id' => 454, 'parish'=> 'Venancio Pulgar' ],
            [ 'id' => 1082, 'municipality_id' => 454, 'parish'=> 'San Isidro' ],
            [ 'id' => 1083, 'municipality_id' => 455, 'parish'=> 'Altagracia' ],
            [ 'id' => 1084, 'municipality_id' => 455, 'parish'=> 'Faría' ],
            [ 'id' => 1085, 'municipality_id' => 455, 'parish'=> 'Ana María Campos' ],
            [ 'id' => 1086, 'municipality_id' => 455, 'parish'=> 'San Antonio' ],
            [ 'id' => 1087, 'municipality_id' => 455, 'parish'=> 'San José' ],
            [ 'id' => 1088, 'municipality_id' => 456, 'parish'=> 'Donaldo García' ],
            [ 'id' => 1089, 'municipality_id' => 456, 'parish'=> 'El Rosario' ],
            [ 'id' => 1090, 'municipality_id' => 456, 'parish'=> 'Sixto Zambrano' ],
            [ 'id' => 1091, 'municipality_id' => 457, 'parish'=> 'San Francisco' ],
            [ 'id' => 1092, 'municipality_id' => 457, 'parish'=> 'El Bajo' ],
            [ 'id' => 1093, 'municipality_id' => 457, 'parish'=> 'Domitila Flores' ],
            [ 'id' => 1094, 'municipality_id' => 457, 'parish'=> 'Francisco Ochoa' ],
            [ 'id' => 1095, 'municipality_id' => 457, 'parish'=> 'Los Cortijos' ],
            [ 'id' => 1096, 'municipality_id' => 457, 'parish'=> 'Marcial Hernández' ],
            [ 'id' => 1097, 'municipality_id' => 458, 'parish'=> 'Santa Rita' ],
            [ 'id' => 1098, 'municipality_id' => 458, 'parish'=> 'El Mene' ],
            [ 'id' => 1099, 'municipality_id' => 458, 'parish'=> 'Pedro Lucas Urribarrí' ],
            [ 'id' => 1100, 'municipality_id' => 458, 'parish'=> 'José Cenobio Urribarrí' ],
            [ 'id' => 1101, 'municipality_id' => 459, 'parish'=> 'Rafael Maria Baralt' ],
            [ 'id' => 1102, 'municipality_id' => 459, 'parish'=> 'Manuel Manrique' ],
            [ 'id' => 1103, 'municipality_id' => 459, 'parish'=> 'Rafael Urdaneta' ],
            [ 'id' => 1104, 'municipality_id' => 460, 'parish'=> 'Bobures' ],
            [ 'id' => 1105, 'municipality_id' => 460, 'parish'=> 'Gibraltar' ],
            [ 'id' => 1106, 'municipality_id' => 460, 'parish'=> 'Heras' ],
            [ 'id' => 1107, 'municipality_id' => 460, 'parish'=> 'Monseñor Arturo Álvarez' ],
            [ 'id' => 1108, 'municipality_id' => 460, 'parish'=> 'Rómulo Gallegos' ],
            [ 'id' => 1109, 'municipality_id' => 460, 'parish'=> 'El Batey' ],
            [ 'id' => 1110, 'municipality_id' => 461, 'parish'=> 'Rafael Urdaneta' ],
            [ 'id' => 1111, 'municipality_id' => 461, 'parish'=> 'La Victoria' ],
            [ 'id' => 1112, 'municipality_id' => 461, 'parish'=> 'Raúl Cuenca' ],
            [ 'id' => 1113, 'municipality_id' => 447, 'parish'=> 'Sinamaica' ],
            [ 'id' => 1114, 'municipality_id' => 447, 'parish'=> 'Alta Guajira' ],
            [ 'id' => 1115, 'municipality_id' => 447, 'parish'=> 'Elías Sánchez Rubio' ],
            [ 'id' => 1116, 'municipality_id' => 447, 'parish'=> 'Guajira' ],
            [ 'id' => 1117, 'municipality_id' => 462, 'parish'=> 'Altagracia' ],
            [ 'id' => 1118, 'municipality_id' => 462, 'parish'=> 'Antímano' ],
            [ 'id' => 1119, 'municipality_id' => 462, 'parish'=> 'Caricuao' ],
            [ 'id' => 1120, 'municipality_id' => 462, 'parish'=> 'Catedral' ],
            [ 'id' => 1121, 'municipality_id' => 462, 'parish'=> 'Coche' ],
            [ 'id' => 1122, 'municipality_id' => 462, 'parish'=> 'El Junquito' ],
            [ 'id' => 1123, 'municipality_id' => 462, 'parish'=> 'El Paraíso' ],
            [ 'id' => 1124, 'municipality_id' => 462, 'parish'=> 'El Recreo' ],
            [ 'id' => 1125, 'municipality_id' => 462, 'parish'=> 'El Valle' ],
            [ 'id' => 1126, 'municipality_id' => 462, 'parish'=> 'La Candelaria' ],
            [ 'id' => 1127, 'municipality_id' => 462, 'parish'=> 'La Pastora' ],
            [ 'id' => 1128, 'municipality_id' => 462, 'parish'=> 'La Vega' ],
            [ 'id' => 1129, 'municipality_id' => 462, 'parish'=> 'Macarao' ],
            [ 'id' => 1130, 'municipality_id' => 462, 'parish'=> 'San Agustín' ],
            [ 'id' => 1131, 'municipality_id' => 462, 'parish'=> 'San Bernardino' ],
            [ 'id' => 1132, 'municipality_id' => 462, 'parish'=> 'San José' ],
            [ 'id' => 1133, 'municipality_id' => 462, 'parish'=> 'San Juan' ],
            [ 'id' => 1134, 'municipality_id' => 462, 'parish'=> 'San Pedro' ],
            [ 'id' => 1135, 'municipality_id' => 462, 'parish'=> 'Santa Rosalía' ],
            [ 'id' => 1136, 'municipality_id' => 462, 'parish'=> 'Santa Teresa' ],
            [ 'id' => 1137, 'municipality_id' => 462, 'parish'=> 'Sucre (Catia)' ],
            [ 'id' => 1138, 'municipality_id' => 462, 'parish'=> '23 de enero' ],
        ];

        foreach ($parishes as $row) {
            App\Parish::create($row);
        }
    }
}
