<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            ['name' => 'all'],
            ['name' => 'user'],
            ['name' => 'manage_staff-access'],
            ['name' => 'manage_staff-show'],
            ['name' => 'manage_staff-add'],
            ['name' => 'manage_staff-edit'],
            ['name' => 'manage_staff-delete'],
            ['name' => 'manage_staff-status'],
            ['name' => 'permissions-access'],
            ['name' => 'permissions-show'],
            ['name' => 'permissions-add'],
            ['name' => 'permissions-edit'],
            ['name' => 'permissions-delete'],
            ['name' => 'permissions-status'],
            ['name' => 'roles-access'],
            ['name' => 'roles-show'],
            ['name' => 'roles-add'],
            ['name' => 'roles-edit'],
            ['name' => 'roles-delete'],
            ['name' => 'roles-status'],
            ['name' => 'customers-access'],
            ['name' => 'customers-show'],
            ['name' => 'customers-add', 'status_id' => 'di'],
            ['name' => 'customers-edit', 'status_id' => 'di'],
            ['name' => 'customers-delete', 'status_id' => 'di'],
            ['name' => 'customers-status'],
            ['name' => 'suppliers-access'],
            ['name' => 'suppliers-show'],
            ['name' => 'suppliers-add'],
            ['name' => 'suppliers-edit'],
            ['name' => 'suppliers-delete'],
            ['name' => 'suppliers-status'],
            ['name' => 'categories-access'],
            ['name' => 'categories-show'],
            ['name' => 'categories-add'],
            ['name' => 'categories-edit'],
            ['name' => 'categories-delete'],
            ['name' => 'categories-status'],
            ['name' => 'products-access'],
            ['name' => 'products-show'],
            ['name' => 'products-add'],
            ['name' => 'products-edit'],
            ['name' => 'products-delete'],
            ['name' => 'products-status'],
            ['name' => 'orders-access'],
            ['name' => 'orders-show'],
            ['name' => 'orders-add', 'status_id' => 'di'],
            ['name' => 'orders-edit', 'status_id' => 'di'],
            ['name' => 'orders-delete'],
            ['name' => 'orders-status'],
            ['name' => 'orders-email'],
            ['name' => 'messages-access'],
            ['name' => 'messages-show'],
            ['name' => 'messages-add'],
            ['name' => 'messages-edit'],
            ['name' => 'messages-delete'],
            ['name' => 'messages-status'],
            ['name' => 'general_settings-logo_favicon-access'],
            ['name' => 'general_settings-logo_favicon-show'],
            ['name' => 'general_settings-logo_favicon-add', 'status_id' => 'di'],
            ['name' => 'general_settings-logo_favicon-edit'],
            ['name' => 'general_settings-logo_favicon-delete', 'status_id' => 'di'],
            ['name' => 'general_settings-logo_favicon-status', 'status_id' => 'di'],
            ['name' => 'general_settings-currencies-access'],
            ['name' => 'general_settings-currencies-show'],
            ['name' => 'general_settings-currencies-add'],
            ['name' => 'general_settings-currencies-edit'],
            ['name' => 'general_settings-currencies-delete'],
            ['name' => 'general_settings-currencies-status'],
            ['name' => 'general_settings-shipping_methods-access'],
            ['name' => 'general_settings-shipping_methods-show'],
            ['name' => 'general_settings-shipping_methods-add'],
            ['name' => 'general_settings-shipping_methods-edit'],
            ['name' => 'general_settings-shipping_methods-delete'],
            ['name' => 'general_settings-shipping_methods-status'],
            ['name' => 'homepage_settings-carousel-access'],
            ['name' => 'homepage_settings-carousel-show'],
            ['name' => 'homepage_settings-carousel-add', 'status_id' => 'di'],
            ['name' => 'homepage_settings-carousel-edit'],
            ['name' => 'homepage_settings-carousel-delete', 'status_id' => 'di'],
            ['name' => 'homepage_settings-carousel-status', 'status_id' => 'di'],
            ['name' => 'homepage_settings-image-access'],
            ['name' => 'homepage_settings-image-show'],
            ['name' => 'homepage_settings-image-add', 'status_id' => 'di'],
            ['name' => 'homepage_settings-image-edit'],
            ['name' => 'homepage_settings-image-delete', 'status_id' => 'di'],
            ['name' => 'homepage_settings-image-status', 'status_id' => 'di'],
            ['name' => 'homepage_settings-personalization-access'],
            ['name' => 'homepage_settings-personalization-show'],
            ['name' => 'homepage_settings-personalization-add', 'status_id' => 'di'],
            ['name' => 'homepage_settings-personalization-edit'],
            ['name' => 'homepage_settings-personalization-delete', 'status_id' => 'di'],
            ['name' => 'homepage_settings-personalization-status', 'status_id' => 'di'],
            ['name' => 'about_us_settings-general-access'],
            ['name' => 'about_us_settings-general-show'],
            ['name' => 'about_us_settings-general-add', 'status_id' => 'di'],
            ['name' => 'about_us_settings-general-edit'],
            ['name' => 'about_us_settings-general-delete', 'status_id' => 'di'],
            ['name' => 'about_us_settings-general-status', 'status_id' => 'di'],
            ['name' => 'about_us_settings-mission_vision-access'],
            ['name' => 'about_us_settings-mission_vision-show'],
            ['name' => 'about_us_settings-mission_vision-add', 'status_id' => 'di'],
            ['name' => 'about_us_settings-mission_vision-edit'],
            ['name' => 'about_us_settings-mission_vision-delete', 'status_id' => 'di'],
            ['name' => 'about_us_settings-mission_vision-status', 'status_id' => 'di'],
            ['name' => 'about_us_settings-services-access'],
            ['name' => 'about_us_settings-services-show'],
            ['name' => 'about_us_settings-services-add'],
            ['name' => 'about_us_settings-services-edit'],
            ['name' => 'about_us_settings-services-delete'],
            ['name' => 'about_us_settings-services-status', 'status_id' => 'di'],
            ['name' => 'about_us_settings-team-access'],
            ['name' => 'about_us_settings-team-show'],
            ['name' => 'about_us_settings-team-add'],
            ['name' => 'about_us_settings-team-edit'],
            ['name' => 'about_us_settings-team-delete'],
            ['name' => 'about_us_settings-team-status', 'status_id' => 'di'],
            ['name' => 'contact_settings-general-access'],
            ['name' => 'contact_settings-general-show'],
            ['name' => 'contact_settings-general-add', 'status_id' => 'di'],
            ['name' => 'contact_settings-general-edit'],
            ['name' => 'contact_settings-general-delete', 'status_id' => 'di'],
            ['name' => 'contact_settings-general-status', 'status_id' => 'di'],
            ['name' => 'contact_settings-contact_information-access'],
            ['name' => 'contact_settings-contact_information-show'],
            ['name' => 'contact_settings-contact_information-add', 'status_id' => 'di'],
            ['name' => 'contact_settings-contact_information-edit'],
            ['name' => 'contact_settings-contact_information-delete', 'status_id' => 'di'],
            ['name' => 'contact_settings-contact_information-status', 'status_id' => 'di'],
            ['name' => 'payment_methods-access'],
            ['name' => 'payment_methods-show'],
            ['name' => 'payment_methods-add'],
            ['name' => 'payment_methods-edit'],
            ['name' => 'payment_methods-delete'],
            ['name' => 'payment_methods-status'],
            ['name' => 'social_media-access'],
            ['name' => 'social_media-show'],
            ['name' => 'social_media-add', 'status_id' => 'di'],
            ['name' => 'social_media-edit'],
            ['name' => 'social_media-delete'],
            ['name' => 'social_media-status'],
            ['name' => 'reports-access'],
            ['name' => 'reports-show'],
            ['name' => 'reports-add'],
            ['name' => 'reports-edit'],
            ['name' => 'reports-delete'],
            ['name' => 'reports-status'],
            ['name' => 'seo_tools-access'],
            ['name' => 'seo_tools-show'],
            ['name' => 'seo_tools-add'],
            ['name' => 'seo_tools-edit'],
            ['name' => 'seo_tools-delete'],
            ['name' => 'seo_tools-status'],
        ];

        foreach ($permissions as $row) {
            App\Permission::create($row);
        }
    }
}
