<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            ['name' => 'all', 'status_id' => 'ac'],
            ['name' => 'user', 'status_id' => 'ac'],
            ['name' => 'manage_staff-access', 'status_id' => 'ac'],
            ['name' => 'manage_staff-show', 'status_id' => 'ac'],
            ['name' => 'manage_staff-add', 'status_id' => 'ac'],
            ['name' => 'manage_staff-edit', 'status_id' => 'ac'],
            ['name' => 'manage_staff-delete', 'status_id' => 'ac'],
            ['name' => 'manage_staff-status', 'status_id' => 'ac'],
            ['name' => 'permissions-access', 'status_id' => 'ac'],
            ['name' => 'permissions-show', 'status_id' => 'ac'],
            ['name' => 'permissions-add', 'status_id' => 'ac'],
            ['name' => 'permissions-edit', 'status_id' => 'ac'],
            ['name' => 'permissions-delete', 'status_id' => 'ac'],
            ['name' => 'permissions-status', 'status_id' => 'ac'],
            ['name' => 'roles-access', 'status_id' => 'ac'],
            ['name' => 'roles-show', 'status_id' => 'ac'],
            ['name' => 'roles-add', 'status_id' => 'ac'],
            ['name' => 'roles-edit', 'status_id' => 'ac'],
            ['name' => 'roles-delete', 'status_id' => 'ac'],
            ['name' => 'roles-status', 'status_id' => 'ac'],
            ['name' => 'customers-access', 'status_id' => 'ac'],
            ['name' => 'customers-show', 'status_id' => 'ac'],
            ['name' => 'customers-add', 'status_id' => 'in'],
            ['name' => 'customers-edit', 'status_id' => 'in'],
            ['name' => 'customers-delete', 'status_id' => 'in'],
            ['name' => 'customers-status', 'status_id' => 'ac'],
            ['name' => 'suppliers-access', 'status_id' => 'ac'],
            ['name' => 'suppliers-show', 'status_id' => 'ac'],
            ['name' => 'suppliers-add', 'status_id' => 'ac'],
            ['name' => 'suppliers-edit', 'status_id' => 'ac'],
            ['name' => 'suppliers-delete', 'status_id' => 'ac'],
            ['name' => 'suppliers-status', 'status_id' => 'ac'],
            ['name' => 'categories-access', 'status_id' => 'ac'],
            ['name' => 'categories-show', 'status_id' => 'ac'],
            ['name' => 'categories-add', 'status_id' => 'ac'],
            ['name' => 'categories-edit', 'status_id' => 'ac'],
            ['name' => 'categories-delete', 'status_id' => 'ac'],
            ['name' => 'categories-status', 'status_id' => 'ac'],
            ['name' => 'products-access', 'status_id' => 'ac'],
            ['name' => 'products-show', 'status_id' => 'ac'],
            ['name' => 'products-add', 'status_id' => 'ac'],
            ['name' => 'products-edit', 'status_id' => 'ac'],
            ['name' => 'products-delete', 'status_id' => 'ac'],
            ['name' => 'products-status', 'status_id' => 'ac'],
            ['name' => 'orders-access', 'status_id' => 'ac'],
            ['name' => 'orders-show', 'status_id' => 'ac'],
            ['name' => 'orders-add', 'status_id' => 'in'],
            ['name' => 'orders-edit', 'status_id' => 'in'],
            ['name' => 'orders-delete', 'status_id' => 'ac'],
            ['name' => 'orders-status', 'status_id' => 'ac'],
            ['name' => 'orders-email', 'status_id' => 'ac'],
            ['name' => 'messages-access', 'status_id' => 'ac'],
            ['name' => 'messages-show', 'status_id' => 'ac'],
            ['name' => 'messages-add', 'status_id' => 'ac'],
            ['name' => 'messages-edit', 'status_id' => 'ac'],
            ['name' => 'messages-delete', 'status_id' => 'ac'],
            ['name' => 'messages-status', 'status_id' => 'ac'],
            ['name' => 'general_settings-logo_favicon-access', 'status_id' => 'ac'],
            ['name' => 'general_settings-logo_favicon-show', 'status_id' => 'ac'],
            ['name' => 'general_settings-logo_favicon-add', 'status_id' => 'in'],
            ['name' => 'general_settings-logo_favicon-edit', 'status_id' => 'ac'],
            ['name' => 'general_settings-logo_favicon-delete', 'status_id' => 'in'],
            ['name' => 'general_settings-logo_favicon-status', 'status_id' => 'in'],
            ['name' => 'general_settings-currencies-access', 'status_id' => 'ac'],
            ['name' => 'general_settings-currencies-show', 'status_id' => 'ac'],
            ['name' => 'general_settings-currencies-add', 'status_id' => 'ac'],
            ['name' => 'general_settings-currencies-edit', 'status_id' => 'ac'],
            ['name' => 'general_settings-currencies-delete', 'status_id' => 'ac'],
            ['name' => 'general_settings-currencies-status', 'status_id' => 'ac'],
            ['name' => 'general_settings-shipping_methods-access', 'status_id' => 'ac'],
            ['name' => 'general_settings-shipping_methods-show', 'status_id' => 'ac'],
            ['name' => 'general_settings-shipping_methods-add', 'status_id' => 'ac'],
            ['name' => 'general_settings-shipping_methods-edit', 'status_id' => 'ac'],
            ['name' => 'general_settings-shipping_methods-delete', 'status_id' => 'ac'],
            ['name' => 'general_settings-shipping_methods-status', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-carousel-access', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-carousel-show', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-carousel-add', 'status_id' => 'in'],
            ['name' => 'homepage_settings-carousel-edit', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-carousel-delete', 'status_id' => 'in'],
            ['name' => 'homepage_settings-carousel-status', 'status_id' => 'in'],
            ['name' => 'homepage_settings-image-access', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-image-show', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-image-add', 'status_id' => 'in'],
            ['name' => 'homepage_settings-image-edit', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-image-delete', 'status_id' => 'in'],
            ['name' => 'homepage_settings-image-status', 'status_id' => 'in'],
            ['name' => 'homepage_settings-personalization-access', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-personalization-show', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-personalization-add', 'status_id' => 'in'],
            ['name' => 'homepage_settings-personalization-edit', 'status_id' => 'ac'],
            ['name' => 'homepage_settings-personalization-delete', 'status_id' => 'in'],
            ['name' => 'homepage_settings-personalization-status', 'status_id' => 'in'],
            ['name' => 'about_us_settings-general-access', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-general-show', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-general-add', 'status_id' => 'in'],
            ['name' => 'about_us_settings-general-edit', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-general-delete', 'status_id' => 'in'],
            ['name' => 'about_us_settings-general-status', 'status_id' => 'in'],
            ['name' => 'about_us_settings-mission_vision-access', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-mission_vision-show', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-mission_vision-add', 'status_id' => 'in'],
            ['name' => 'about_us_settings-mission_vision-edit', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-mission_vision-delete', 'status_id' => 'in'],
            ['name' => 'about_us_settings-mission_vision-status', 'status_id' => 'in'],
            ['name' => 'about_us_settings-services-access', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-services-show', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-services-add', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-services-edit', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-services-delete', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-services-status', 'status_id' => 'in'],
            ['name' => 'about_us_settings-team-access', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-team-show', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-team-add', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-team-edit', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-team-delete', 'status_id' => 'ac'],
            ['name' => 'about_us_settings-team-status', 'status_id' => 'in'],
            ['name' => 'contact_settings-general-access', 'status_id' => 'ac'],
            ['name' => 'contact_settings-general-show', 'status_id' => 'ac'],
            ['name' => 'contact_settings-general-add', 'status_id' => 'in'],
            ['name' => 'contact_settings-general-edit', 'status_id' => 'ac'],
            ['name' => 'contact_settings-general-delete', 'status_id' => 'in'],
            ['name' => 'contact_settings-general-status', 'status_id' => 'in'],
            ['name' => 'contact_settings-contact_information-access', 'status_id' => 'ac'],
            ['name' => 'contact_settings-contact_information-show', 'status_id' => 'ac'],
            ['name' => 'contact_settings-contact_information-add', 'status_id' => 'in'],
            ['name' => 'contact_settings-contact_information-edit', 'status_id' => 'ac'],
            ['name' => 'contact_settings-contact_information-delete', 'status_id' => 'in'],
            ['name' => 'contact_settings-contact_information-status', 'status_id' => 'in'],
            ['name' => 'payment_methods-access', 'status_id' => 'ac'],
            ['name' => 'payment_methods-show', 'status_id' => 'ac'],
            ['name' => 'payment_methods-add', 'status_id' => 'ac'],
            ['name' => 'payment_methods-edit', 'status_id' => 'ac'],
            ['name' => 'payment_methods-delete', 'status_id' => 'ac'],
            ['name' => 'payment_methods-status', 'status_id' => 'ac'],
            ['name' => 'social_media-access', 'status_id' => 'ac'],
            ['name' => 'social_media-show', 'status_id' => 'ac'],
            ['name' => 'social_media-add', 'status_id' => 'in'],
            ['name' => 'social_media-edit', 'status_id' => 'ac'],
            ['name' => 'social_media-delete', 'status_id' => 'ac'],
            ['name' => 'social_media-status', 'status_id' => 'ac'],
            ['name' => 'reports-access', 'status_id' => 'ac'],
            ['name' => 'reports-show', 'status_id' => 'ac'],
            ['name' => 'reports-add', 'status_id' => 'ac'],
            ['name' => 'reports-edit', 'status_id' => 'ac'],
            ['name' => 'reports-delete', 'status_id' => 'ac'],
            ['name' => 'reports-status', 'status_id' => 'ac'],
            ['name' => 'seo_tools-access', 'status_id' => 'ac'],
            ['name' => 'seo_tools-show', 'status_id' => 'ac'],
            ['name' => 'seo_tools-add', 'status_id' => 'ac'],
            ['name' => 'seo_tools-edit', 'status_id' => 'ac'],
            ['name' => 'seo_tools-delete', 'status_id' => 'ac'],
            ['name' => 'seo_tools-status', 'status_id' => 'ac'],
        ];

        foreach ($permissions as $row) {
            App\Permission::create($row);
        }
    }
}
